### ISSUE TITLE
Rework site footer

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1007]
Related to #1003.

Current footer:
> <img width="529" alt="screen shot 2017-09-01 at 12 18 36" src="https://user-images.githubusercontent.com/4140793/29978560-bdaf6e6a-8f0f-11e7-96ca-494d398c5753.png">

> <img width="1164" alt="screen shot 2017-09-01 at 12 19 10" src="https://user-images.githubusercontent.com/4140793/29978577-cbf68d96-8f0f-11e7-909f-5f286e7e91da.png">

@kwalrath I really like the https://flutter.io page foot (there is an image below) as it has been stripped to bare essentials. As for the webdev foothow about:

- Dropping "Technologies"
- Dropping "Resources"

That will leave us with

 - Community
 - Problems
 - Terms | Privacy
 - And I'd like to add site version and build info.

WDYT?

**Comment by chalin** [comment]
Other examples:
- https://www.dartlang.org
> <img width="777" alt="screen shot 2017-09-01 at 12 33 03" src="https://user-images.githubusercontent.com/4140793/29979032-c553b7f0-8f11-11e7-88c2-cf02e2e33dd6.png">

- https://flutter.io
> <img width="410" alt="screen shot 2017-09-01 at 12 32 50" src="https://user-images.githubusercontent.com/4140793/29979050-df34d3ca-8f11-11e7-8325-4cff3500b45e.png">

**Comment by kwalrath** [comment]
I agree, we can drop the TECHNOLOGIES & RESOURCES lists from the footer.

I'm fine with adding a version #, but we should be clear about what it is—site version, Angular version, ...? We don't necessarily have to explain it right there, but we could link to the explanation if it's warranted.

**Comment by chalin** [comment]
Closed by #1079
