### ISSUE TITLE
API: Add entries to selected core dart libraries

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1009]
Namely for async, core, convert, html.

@kwalrath - let me know if this is still something that you would want. I believe that the main issue is that you wanted an indication that the links were external.

**Comment by chalin** [comment]
Btw, the functionality is already in place. It is just currently disabled.

**Comment by kwalrath** [comment]
I'm not sure. I like the idea of having everything in one place, a la docs.flutter.io, but I'm not sure about the usability.

Maybe we could mock it up and ask people who already use the webdev/api docs to try it out?

**Comment by chalin** [comment]
In a sense, the access is all in one place (from the API reference page). I'd rather avoid duplication if we can. Besides, I think it is good to direct folks to the canonical URL for the dart core API entires.

> we could mock it up and ask people who already use the webdev/api docs to try it out?

SGTM. To be clear, you mean to mockup the current approach (which redirects to https://api.dartlang.org)?

**Comment by kwalrath** [comment]
Yep, let's just put out what we have. We shouldn't spend a lot of time on this until it's clear that it could be very useful.
