### ISSUE TITLE
Missing angular_forms dependency in pubspec.yaml at angular/tutorial/toh-pt1

### ISSUE THREAD

**Issue by a14n** [dart-lang/site-webdev#1020]
On tutorial [The Hero Editor](https://webdev.dartlang.org/angular/tutorial/toh-pt1) it's mentioned to add the following import:

```
import 'package:angular_forms/angular_forms.dart';
```

But there's no `angular_forms` dependency in `pubspec.yaml` at that time and it leads to error.

**Comment by kwalrath** [comment]
Thanks for the report, @a14n! The tutorial code has had to change quite a bit recently, due to Angular v4 and moving code from lib to lib/src, and it's easy for us to miss all the little things that need to change. Sorry for that, and thanks again for letting us know about the issues you find.

**Comment by a14n** [comment]
No worries. I had no problem to find what to do to go ahead and I understand that codebase changes can be hard for external documentations.

I only reported those issues to avoid new users being trapped by a so little things compared with all this awesome documentation you wrote. Keep on your great work :)

**Comment by chalin** [comment]
Thank you Alexandre. Your detailed feedback concerning the tutorial is greatly appreciated!
