### ISSUE TITLE
Angular Tutorial : import issue

### ISSUE THREAD

**Issue by a14n** [dart-lang/site-webdev#1021]
In [Add the hero property](https://webdev.dartlang.org/angular/tutorial/toh-pt3#!#add-the-hero-property):

>Add the following `import` statement near the top of _both_ the `app_component.dart` and the `hero_detail_component.dart` files.

```
import 'hero.dart';
```

But `app_component.dart` and `hero_detail_component.dart` are not in the same directory and the import fails in `app_component.dart`.

**Comment by kwalrath** [comment]
Thanks for the report, @a14n.

**Comment by chalin** [comment]
Good catch, thanks!
