### ISSUE TITLE
Angular tutorial: bad location for creating hero_service.dart

### ISSUE THREAD

**Issue by a14n** [dart-lang/site-webdev#1022]
At https://webdev.dartlang.org/angular/tutorial/toh-pt4#!#create-heroservice

>Create a file in the `lib` folder called `hero_service.dart`

It should be `lib/src/` like the path in https://webdev.dartlang.org/angular/tutorial/toh-pt4#!#libsrchero_servicedart-starting-point

**Comment by a14n** [comment]
Same below for `mock_heroes.dart`

**Comment by kwalrath** [comment]
Thanks very much for letting us know about these issues, @a14n.

**Comment by kwalrath** [comment]
We should fix these when we fix the remaining issues in #1016.

**Comment by chalin** [comment]
Ah yes, this is a simple fix which I could have included in #1016, but I hadn't triaged the issues yet. A PR is on its way.
