### ISSUE TITLE
Update angular forms page

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1030]
- [x] Style guide updates are needed (e.g., this page still uses "we") - #1102
- [x] Rename the example app to avoid confusion with the AngularDart package named `angular_forms`
- [x] Ensure that mention is made about the need to include the package in the pubspec (see how this was done in toh-1).
- [ ] Adjust sample and prose to promote use of class bindings #366

Related:
- #1029
- #1106

**Comment by kwalrath** [comment]
I added checkboxes and marked a couple as complete.

**Comment by chalin** [comment]
I'm going to close this issue since all points but the last one have been addressed, and the last point has its own issue.
