### ISSUE TITLE
Http tutorial - clarify use of BrowserClient requires a real backend

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1046]
Add a note at the end of https://webdev.dartlang.org/angular/tutorial/toh-pt6#register-for-http-services, clarifying that the app can't be run at that point because we don't have a real backend.

**Comment by chalin** [comment]
@kwalrath - how about a note like this:

> **Warning:** An app provisioned with a `BrowserClient` will only run if you
have an appropriately configured backend server. You might not have access to
a backend server, or want to set one up. In the next section, you'll provision
the app with a client that mocks interaction with a backend server.

**Comment by kwalrath** [comment]
only run -> run only
(per https://developers.google.com/style/translation)
Actually, "run" is probably not the right verb here, and the text makes a lot of assumptions about "you". Maybe we could have something like this:

> **Note:** This app doesn't work yet because `BrowserClient` assumes 
an appropriately configured backend server. The next section shows how to
mock interaction with a backend server.

If it _might_ work, we could say:
> **Note:** Unless you have an appropriately configured backend server (or a mock server),
this app doesn't work. The next section shows...
