### ISSUE TITLE
Fix tutorial's discussion of angular_forms & the directives list

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1048]
See #1041 for details.

**Comment by chalin** [comment]
Here is the main part of the relevant discussion:

> Reading this through, the ordering of the angular_forms library/package discussion is a bit weird.
> 
> It says NgModel is... defined in the angular_forms library, but you haven't introduced that library. And you normally wouldn't import the library before adding the package to pubspec.
> 
> Fixing this might require some thought, since the point it's trying to illustrate (needing to list things in `directives`) is orthogonal to adding a package.

Actually, having given this some thought, I believe that the current approach has pedagogical value. Essentially, the tutorial shows the reader what can happen if you attempt to use a (non-core) Angular directive before telling Angular where to find it.

I do have a proposal to make this more obvious. I'll submit a PR.
