### ISSUE TITLE
Minor: "APP_CONFIG" const should be lowerCamelCase "appConfig"

### ISSUE THREAD

**Issue by ninachen** [dart-lang/site-webdev#1055]
Here: https://webdev.dartlang.org/angular/guide/dependency-injection#!#opaquetoken

Per Effective Dart, prefer using lowerCamelCase for consts[0]. Would be nice for the official docs to follow the style guide, although this guideline is a recommendation and not a requirement (PREFER instead of DO).

[0] https://www.dartlang.org/guides/language/effective-dart/style#prefer-using-lowercamelcase-for-constant-names

**Comment by kwalrath** [comment]
Thanks for pointing this out, Nina.
