### ISSUE TITLE
Add Google Feedback button

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-webdev#106]

**Comment by chalin** [comment]
Thanks for the issue Nate. Can you give an example of a site (preferably one of the Dart sites) where this feedback button has already been integrated?

cc @kwalrath

**Comment by natebosch** [comment]
@ferhatb do you know of any sites using the feedback button which are open source?

**Comment by natebosch** [comment]
Found one
https://source.android.com/source/building.html
See the 'Site feedback' at the bottom.

https://android.googlesource.com/platform/build/+/master/tools/droiddoc/templates-sac/footer.cs#5
https://android.googlesource.com/platform/build/+/master/tools/droiddoc/templates-sac/head_tag.cs#49

**Comment by kwalrath** [comment]
We just need to whitelist our domain, it looks like.

**Comment by chalin** [comment]
@kwalrath - will you take care of that before you take time off?

**Comment by kwalrath** [comment]
@chalin, I believe @kevmoo is taking care of whitelisting.

**Comment by chalin** [comment]
@kevmoo - how is the whitelisting coming along?

**Comment by kevmoo** [comment]
Waiting for emails.

We are not blocked on this. Include the github issue URI. This will be a nice extra for later. I think we can remove it from the milestone.

**Comment by chalin** [comment]
Move to milestone "later".

**Comment by kwalrath** [comment]
Although we'd love an easier way to provide feedback, Google Feedback isn't ideal for 2 reasons:

* It uses a completely different, Google-internal workflow that adds to the complexity of working on this site. I'd rather use a solution that ties into GitHub.
* There's an offset in many of the docs that makes the selection tool not work. (See #315.)

I'm going to close this and open a separate bug about making it easier to give feedback (and/or submit PRs).

**Comment by kwalrath** [comment]
We already have an issue open for this: #696
