### ISSUE TITLE
Make clear that the Angular pages are part of the Angular subsite

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#107]
Perhaps add the blue cityscape background in the heading, and an Angular logo somewhere.

Work we do here might also apply to other subsites of www/webdev.dartlang.org (nothing huge right now, but perhaps [code labs](https://webdev.dartlang.org/codelabs), [Effective Dart](https://www.dartlang.org/guides/language/effective-dart), ...).

cc @ferhatb

**Comment by chalin** [comment]
Reopening. Following feedback from Ferhat and team, we'll stick to the Angular logo on `h1` headings, but drop the change of color in the main nav.
