### ISSUE TITLE
Check current TOCs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1091]
Post-install message from jekyll-toc:
As of jekyll-toc 0.3, nested toc is supported! Please make sure your toc is not broken after update jekyll-toc.

**Comment by chalin** [comment]
On first inspection, our use of the toc feature seems to be working just as before.

I can look into the new "nested toc" feature (in case you want to keep this issue open for that).

**Comment by kwalrath** [comment]
Sure, I'd love to see what we can do with nested TOCs.

**Comment by chalin** [comment]
I gave the nested toc feature a try, but it isn't working so far. https://github.com/toshimaru/jekyll-toc/issues/35

**Comment by kwalrath** [comment]
Thanks for checking it out.

**Comment by chalin** [comment]
Closing this since our auto-generated TOC is working as it did before. I'll open a separate issue for nested TOCs.
