### ISSUE TITLE
toh-pt2 should tell you to remove some old code

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1092]
In [this gitter discussion](https://gitter.im/dart-lang/angular?at=59cedaa3614889d4755782a5), @RandalSchwartz reported an issue with https://webdev.dartlang.org/angular/tutorial/toh-pt2: his code wasn't working, because he wasn't told to remove some obsolete code.

**Comment by chalin** [comment]
@RandalSchwartz, thanks for pointed that out. I've updated the tutorial to read (early on) that the template needs to have its contents replaced, rather than just added to.
