### ISSUE TITLE
Remove NgControlStatus from the Forms guide

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1106]
NgControlStatus has been deprecated, so we shouldn't use it in our example. See dart-lang/site-webdev#114 and dart-lang/site-webdev#1102 for more info.

---

After some discussion we've agree to:
- [x] remove text that mentions `NgControlStatus` and its fixed set of CSS class names
- [x] change the (former `NgControlStatus `) class names (drop `ng-` prefix), and remove a few
- [x] create a changelog explaining that we've moved away from the use of `NgControlStatus` CSS class names.

**Comment by chalin** [comment]
We only refer to `NgControlStatus` in mentioning that it is deprecated. On the other hand, we can avoid mentioning this deprecated class if we drop the use of the `ng-*` CSS classes.

From https://github.com/dart-lang/site-webdev/pull/1102#discussion_r144147880:
> Btw, given that the choice of those 6 CSS classes is no longer being imposed on users, we would (eventually) simplify the page to only refer to 3 (for the states corresponding to "touched", "dirty" or "invalid").

Is that along the lines of what you had in mind?

**Comment by kwalrath** [comment]
Using simpler (non-`ng-*`) class names and fewer of them SGTM.

**Comment by chalin** [comment]
FYI, I've added items to the original comment.

**Comment by chalin** [comment]
Closed by #1117.
