### ISSUE TITLE
[ng] api filter banner style impacted by bootstrap

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#112]
Follow-up to #95.

@ericjim - `bootstrap` adds some `margin-bottom: 40px` to our ng `banner` style. What is the most appropriate way to prevent that?
![screen shot 2016-11-17 at 10 40 57 am](https://cloud.githubusercontent.com/assets/4140793/20402832/2fee3c12-acb3-11e6-8e5d-fc5f70102699.png)

**Comment by ericjim** [comment]
There is also a `.banner` defined in webdev, which probably collides with the banner defined by ng1.io

**Comment by ericjim** [comment]
fixed by https://github.com/dart-lang/site-webdev/pull/123
