### ISSUE TITLE
Typo in App Structure on Routing Basics Page

### ISSUE THREAD

**Issue by july8six** [dart-lang/site-webdev#1148]
The example app structure has a typo:
[Routing Basics](https://webdev.dartlang.org/angular/guide/router/1)

**App Structure**
router_example
lib
app_component.dart
src
crisis_center_component.dart
**heroes.component.dart**
web
index.html
main.dart
styles.css

**Should Be**
router_example
lib
app_component.dart
src
crisis_center_component.dart
**heroes_component.dart**
web
index.html
main.dart
styles.css

**Comment by chalin** [comment]
Sharp eye! Thanks for reporting this. I also found an instance of this in Milestone 2 of the router guide. Both are fixed in #1151.
