### ISSUE TITLE
app_component.dart Imports don't match file examples

### ISSUE THREAD

**Issue by july8six** [dart-lang/site-webdev#1149]
This is dealing with the example on [Routing Basics](https://webdev.dartlang.org/angular/guide/router/1):

The example files the user is supposed to create are:
- src/crisis_center_component.dart
- src/heroes_component.dart

The imports for the app_component.dart file are:
- import 'src/crisis_center_component_1.dart';
- import 'src/heroes_component_1.dart';

The imports should match the files the users need to create.

**Comment by chalin** [comment]
Thanks again for filing this issue.

For the record, I've added an extra check for the (unexpected) use of intermediate file versions, and it found these instances:

```
publish/angular/guide/router/1.html:import 'src/crisis_center_component_1.dart';
publish/angular/guide/router/1.html:import 'src/heroes_component_1.dart';
publish/angular/guide/router/2.html:import 'src/crisis_center_component_1.dart';
publish/angular/guide/router/2.html:import 'src/heroes_component_1.dart';
publish/angular/guide/router/3.html:import 'src/crisis_center_component_1.dart';
publish/angular/guide/router/3.html:import 'src/crisis_center_component_1.dart';
publish/angular/guide/router/4.html:  templateUrl: 'crisis_detail_component_1.html',
```

All these will be fixed as well.
