### ISSUE TITLE
Extra Step in Add Heroes Functionality

### ISSUE THREAD

**Issue by july8six** [dart-lang/site-webdev#1150]
The [Add Heroes Functionality](https://webdev.dartlang.org/angular/guide/router/3#add-heroes-functionality) section under Routing is unclear and includes an extra step:

**What it reads:**

> Follow these steps:
> 
> Create the lib/src/heroes folder — you’ll be adding files implementing hero management there.
> gement there.
> **Copy the following files from toh-5 lib/src into lib/src (not yet lib/src/heroes):**
> heroes.dart
> hero_detail_component.*, that is, the CSS, Dart and HTML files
> hero_service.dart
> heroes_component.*, the CSS, Dart and HTML files; 
> Note: this will overwrite the local Dart file.
> mock_heroes.dart
> **Use your IDE to refactor/move all of these newly copied files into the lib/src/heroes folder.**
> In heroes_component.html, rename the <ul> element class to items (from heroes).
> Add the HeroService to the providers list of AppComponent so that it is available everywhere in the app. This should be the result:

This adds an extra refactoring step.  The app works just fine without doing the extra refactoring.  The instructions make this confusing to someone who is learning routes.  It should be changed to:

> Create the lib/src/heroes folder — you’ll be adding files implementing hero management there.
> gement there.
> **Copy the following files from toh-5 lib/src into lib/src/heroes):**
> heroes.dart
> hero_detail_component.*, that is, the CSS, Dart and HTML files
> hero_service.dart
> mock_heroes.dart
> heroes_component.*, the CSS, Dart and HTML files; 
> In heroes_component.html, rename the \<ul> element class to items (from heroes).
> Add the HeroService to the providers list of AppComponent so that it is available everywhere in the app.  **Remove the old hero_component.dart file and change the import to reference the new hero_component.dart file.** This should be the result:

(edits by @chalin)

**Comment by chalin** [comment]
I originally thought that there were more imports to adjust than that, but I believe that you are right. Good suggestion, thanks.
