### ISSUE TITLE
Folder Structure Missing File in Child & Relative Routes Section

### ISSUE THREAD

**Issue by july8six** [dart-lang/site-webdev#1153]
The [App Code](https://webdev.dartlang.org/angular/guide/router/4#app-code) section has the following:

/..
src
crisis_center
crises_component.{css,dart,html}
crisis.dart
crisis_center_component.dart
crisis_detail_component.{css,dart,html}
crisis_service.dart
mock_crises.dart
/..

It should read:
/..
src
crisis_center
crises_component.{css,dart,html}
crisis.dart
crisis_center_component.dart
**crisis_center_home_component.dart**
crisis_detail_component.{css,dart,html}
crisis_service.dart
mock_crises.dart
/..

**Comment by chalin** [comment]
Dup of #1152?

Closed by #1159
