### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by july8six** [dart-lang/site-webdev#1167]
URL: https://webdev.dartlang.org/api/angular_components/angular_components/ClickableTooltipTargetDirective/elementRef
Expected page: elementRef property - ClickableTooltipTargetDirective class ...
--

**Comment by chalin** [comment]
Which page did you get this URL from?

**Comment by chalin** [comment]
I've searched both the main and the dev version of the webdev site and I can't find that URL.

**Comment by kwalrath** [comment]
It looks like it's a Google result. I just did a Google search for [elementref dart clickabletooltiptargetdirective], and I got to the same (bad) URL. Clicking the ["cached" link on the result page](https://webcache.googleusercontent.com/search?q=cache:MVOl3i2WLQwJ:https://webdev.dartlang.org/api/angular_components/angular_components/ClickableTooltipTargetDirective/elementRef+&cd=1&hl=en&ct=clnk&gl=us), I got to an angular_components 0.6.0 page that was cached September 14.

**Comment by kwalrath** [comment]
I'm using WebMaster tools to try to kick the cache/results.

**Comment by kwalrath** [comment]
The search still gives a bad result. Looking into this some more...

**Comment by kwalrath** [comment]
I've requested that the page be removed (using https://www.google.com/webmasters/tools/removals, which I'd forgotten about).

**Comment by chalin** [comment]
Based on my latest tests, this appears to have been fixed. If you agree, I'll let you close it @kwalrath.

**Comment by kwalrath** [comment]
Yep, looks fixed to me!
