### ISSUE TITLE
[Angular] View Explanations/Hide Explanations doesn't work

### ISSUE THREAD

**Issue by skybrian** [dart-lang/site-webdev#117]
https://angulardart-org-dev.firebaseapp.com/angular/quickstart

On this web page I see:

"Hide Explanations

Explanations describe the concepts and reasons behind the instructions. Explanations have a thin border on the left like this block of text.

Click Hide Explanations to show only the instructions. Click View Explanations to see everything again."

Clicking "Hide Explanations" toggles it to "View Explanations" and vice-versa. However, nothing else on the web page changes (at least above the fold). So it apparently does nothing.

Since it doesn't do anything, I suggest removing this toggle button; it seems like a distraction.

**Comment by chalin** [comment]
Thanks for all the issues Brian. This one is a dup though, see #96.
Quickstart will be reworked shortly.
