### ISSUE TITLE
Remove /api/dart-* entries from sitemap

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1170]
https://webdev.dartlang.org/sitemap.xml appears to list all the dart:* API reference pages that are linked to by https://webdev.dartlang.org/api. On the /api page, the URLs are correct; in the sitemap, they're incorrect. For example:

```
<url>
  <loc>
    https://webdev.dartlang.org/api/dart-async/AsyncError-class
  </loc>
  <lastmod>2017-11-09T10:33:19-08:00</lastmod>
  <changefreq>monthly</changefreq>
</url>
```

**Comment by chalin** [comment]
FYI, I've double checked, and https://webdev.dartlang.org/sitemap.xml no longer contains the Dart API entries.
