### ISSUE TITLE
[WtD] Update pages to match Google style guidelines

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1183]
**This issue is for writers participating in the Write the Docs doc sprint in Sydney on November 24.**

Our docs need copy editing! Here's how you can help:

1. Find a page you're interested in.
1. Search this issue to make sure no one else has claimed that page.
1. Add a comment claiming the page.
1. Create a PR with the improved text, using conventions established by the [Google developer doc style guide](https://developers.google.com/style/).

An example of a copyedit PR: dart-lang/site-webdev#1184

We suspect that the following pages need work:

* [x] https://webdev.dartlang.org/angular/guide/architecture
* [ ] https://webdev.dartlang.org/angular/guide/component-styles
* [ ] https://webdev.dartlang.org/angular/guide/dependency-injection
* [ ] https://webdev.dartlang.org/angular/guide/deployment
* [ ] https://webdev.dartlang.org/angular/guide/hierarchical-dependency-injection
* [ ] https://webdev.dartlang.org/angular/guide/security
* [ ] https://webdev.dartlang.org/angular/guide/server-communication
* [x] https://webdev.dartlang.org/angular/guide/setup
* [ ] https://webdev.dartlang.org/angular/guide/structural-directives
* [ ] https://webdev.dartlang.org/angular/guide/template-syntax 
* [ ] https://webdev.dartlang.org/angular/guide/testing/component 

**Note:** It’s generally OK to perform small edits on other pages, but **don’t** edit the
**angular/guide/router\*** pages. They're being rewritten.

**Comment by angelism** [comment]
I will edit the https://webdev.dartlang.org/angular/guide/server-communication page.

**Comment by 100percentlinen** [comment]
I'll work on the 'template-syntax' page

**Comment by sarahmaddox** [comment]
I'll work on https://webdev.dartlang.org/angular/guide/architecture

**Comment by jenapp** [comment]
I'll work on https://webdev.dartlang.org/angular/guide/setup

**Comment by jenapp** [comment]
Grabbing https://webdev.dartlang.org/angular/guide/testing/component

**Comment by chalin** [comment]
WtD is over. Closing.
