### ISSUE TITLE
Feedback on page: Running Component Tests (DRAFT)

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/site-webdev#1192]
how are you supposed to run tests?
URL: https://webdev.dartlang.org/angular/guide/testing/component/running-tests

says to run
`pub run angular_test --test-arg=--tags=aot --test-arg=--platform=dartium  --test-arg=--reporter=expanded`
i did that and got this error:

```
Finished compilation. Running tests...
pub run test --tags=aot --platform=dartium --reporter=expanded --pub-serve=54944
00:00 +0 -1: loading test/app_test.dart [E]
Failed to load "test/app_test.dart":
Failed to run Dartium: No such file or directory
Command: dartium --user-data-dir=/private/var/folders/00/0s41r000h01000cxqpysvccm0034h7/T/dart_test_5atdjx http://localhost:54944/packages/test/src/runner/browser/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A54946%2FjIPw5f8FpFm4c3LYdgaNs89TWIQG1t%252Bb%2F0&debug=false --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate.
```

i can't tell what it's trying to say, that it can't find test/app_test.dart or that it can't find the dartium command.  i tried both of these aliases, in turn:
```
alias dartium="open /Applications/dart/chromium/Chromium.app"
alias dartium="/Applications/dart/chromium/Chromium.app"
```
but neither altered the error i got.  the file test/app_test.dart does seem to exist:
```
> ls -l test
total 8
-rw-r--r--  1 XXXXXXXX  eng  825 Oct 25 01:22 app_test.dart
```

**Comment by chalin** [comment]
Hi @trinarytree. First a few questions, which

- OS
- Dart version
- Angular version

Are you using?

Also, did you follow the tutorial’s Starter App setup? In particular [Get prerequisites: Dart SDK, Dartium, and WebStorm](https://webdev.dartlang.org/angular/guide/setup#get-prerequisites-dart-sdk-dartium-and-webstorm)?

What is the output of `type dart` and `type dartium`? E.g., I get:

```shell
toh-0 > type dart
dart is /opt/brew/bin/dart
toh-0 > type dartium
dartium is /opt/brew/bin/dartium
```

Btw, you shouldn't need to create aliases for `dartium`.

**Comment by trinarytree** [comment]
os: mac os x
dart version: Dart VM version: 1.24.2 (Thu Jun 22 08:42:17 2017) on "macos_x64"
angular version: not sure but this was in my .packages:
```
angular:file:///Users/ccalabro/.pub-cache/hosted/pub.dartlang.org/angular-4.0.0/lib/
angular_compiler:file:///Users/ccalabro/.pub-cache/hosted/pub.dartlang.org/angular_compiler-0.3.0/lib/
angular_components:file:///Users/ccalabro/.pub-cache/hosted/pub.dartlang.org/angular_components-0.8.0/lib/
angular_forms:file:///Users/ccalabro/.pub-cache/hosted/pub.dartlang.org/angular_forms-1.0.0/lib/
angular_test:file:///Users/ccalabro/.pub-cache/hosted/pub.dartlang.org/angular_test-1.0.1/lib/
```

tutorial setup: yeah i got webstorm and had it create the starter app for me.
i ran it and it launched dartium and it worked fine.
it's just the test that doesn't work.  actually i don't understand why i can't run
tests directly from webstorm.
when i try, it says 
```
Process finished with exit code 0
Empty test suite.
```

other stuff you asked for:
```
> type dart
dart is /Applications/dart/dart-sdk/bin/dart
> type dartium    # without the alias
-bash: type: dartium: not found
```
mind you, dartium is installed at /Applications/dart/chromium/Chromium.app.

also, i found a way to make the test run, but it's kind of crappy:
```
> pub run test -p chrome --pub-serve=8081 test/app_test.dart
```
notice the use of the word 'chrome'.
it's slow (~30 sec).  i'm guessing that it invokes dart2js.

**Comment by chalin** [comment]
You are right to point out that the docs assume that on a Mac, you are using brew to install Dart and Dartium. With your currently setup you'll need to create a script. 

Somewhere in your path (maybe`~/bin`) create a script named `dartium` with the following contents:

```shell
#!/usr/bin/env bash
exec "/Applications/Chromium.app/Contents/MacOS/Chromium" "$@"
```

Then `chmod a+x ~/bin/dartium`, and finally try running tests with `--platform dartium` again.

**Comment by trinarytree** [comment]
with those suggestions, i get a slightly different error:
```
Finished compilation. Running tests...
pub run test --tags=aot --platform=dartium --reporter=expanded --pub-serve=53556
00:00 +0 -1: loading test/app_test.dart [E]
Failed to load "test/app_test.dart": Failed to run Dartium: Dartium failed with exit code 126..
```
it should be noted that with those suggestions, when i run `dartium` from the command line, i get
```
-bash: /Applications/dart/chromium/Chromium.app: is a directory
```
are you sure that bash script was right?

**Comment by chalin** [comment]
Which path did you use after the `exec` command in the script?

Sorry, path I gave earlier was actually from my environment. Given that your chromium is found under `/Applications/dart/chromium/Chromium.app` then the `dartium` script should probably be:

```shell
#!/usr/bin/env bash
exec "/Applications/dart/chromium/Chromium.app/Contents/MacOS/Chromium" "$@"
```

Double check that `/Applications/dart/chromium/Chromium.app/Contents/MacOS/Chromium` actually refers to an executable.

**Comment by chalin** [comment]
I'm going to assume that this has been resolved. If not please reopen with updated information.
