### ISSUE TITLE
'Routing' page issue: NoSuchMethodError: Class 'HeroesComponent' has no instance getter 'gotoDetail'

### ISSUE THREAD

**Issue by nbro** [dart-lang/site-webdev#1226]
From URL: https://webdev.dartlang.org/angular/tutorial/toh-pt5

I'd like to note that (provided I faithfully followed the tutorial step by step) once we get to _[this point](https://webdev.dartlang.org/angular/tutorial/toh-pt5#add-the-mini-detail)_ of the _Tour of Heroes_ tutorial, we get an error in the console of the browser, if we try to click on one of the heroes of the list of heroes, instead of seeing what we are supposed to see, that is

<img width="264" alt="screen shot 2017-12-28 at 02 39 21" src="https://user-images.githubusercontent.com/9349000/34397675-672e58e2-eb78-11e7-840b-e39064925db9.png">

after refreshing the browser, as it is suggested in the following note

> Refresh the browser. Selecting a hero from the heroes list will activate the mini detail view. The view details button doesn’t work yet.

However, I am getting the following (simplified) error

```
ORIGINAL EXCEPTION: NoSuchMethodError: Class 'HeroesComponent' has no instance getter 'gotoDetail'.
Receiver: Instance of 'HeroesComponent'
Tried calling: gotoDetail
```

and the panel 

<img width="264" alt="screen shot 2017-12-28 at 02 39 21" src="https://user-images.githubusercontent.com/9349000/34397675-672e58e2-eb78-11e7-840b-e39064925db9.png">

is not displayed.

It looks like the click event on one of the heroes of the list is propagated to the button (in the details panel we are supposed to see) to view the details. As far as I know, that behavior shouldn't occur anyway.

**Note**: _in the section after [Add the mini detail](https://webdev.dartlang.org/angular/tutorial/toh-pt5#add-the-mini-detail), that is [Update the HeroesComponent class](https://webdev.dartlang.org/angular/tutorial/toh-pt5#update-the-heroescomponent-class), the `gotoDetail()` is implemented and the error does not occur anymore. Nevertheless, there's no warning in the tutorial about the error I've just described above. I have also noticed that this "issue" also occurs in the last part of the tutorial about HTTP._

**Comment by kwalrath** [comment]
Thanks for reporting this and the other issue, @nbro.

**Comment by chalin** [comment]
@nbro - thank you for the nicely detailed issue! I confirm the problem both when using Chrome and Dartium. I'll have a fix shortly.
