### ISSUE TITLE
examples/ng/doc/quickstart

### ISSUE THREAD

**Issue by transmeta01** [dart-lang/site-webdev#1233]
Loading angular and dart_to_js_script_rewriter transformers...
Serving angular_app web  on http://localhost:9080
Serving angular_app test on http://localhost:9081
[Error from BuilderTransformer: Instance of 'LibraryBuilder' on angular|primary]:
Unable to resolve asset ID for "dart:core" 

pub serve --port=9080 was failing with the same msg during loading. Turned out my $DART_SDK env variable was pointing at an old version after a brew dart upgrade...However it seems, something more is need to test as well...I tried disabling/commenting out the testing phase, to no avail

**Comment by chalin** [comment]
Are you still having this issue? If so, can you provide more details about your environment (OS, version of Dart, Angular, etc).

**Comment by chalin** [comment]
I'm closing this for now. Feel free to reopen the issue once you have more details.
