### ISSUE TITLE
'Routing' tutorial page issue

### ISSUE THREAD

**Issue by sudolibre** [dart-lang/site-webdev#1237]
From URL: https://webdev.dartlang.org/angular/tutorial/toh-pt5

Early in the article it says to name the route the singular "/detail" 
https://webdev.dartlang.org/angular/tutorial/toh-pt5#libapp_componentdart-herodetail-route

Later in the article it provides a link that uses the plural detail**S** localhost:8080/#details/11
https://webdev.dartlang.org/angular/tutorial/toh-pt5#libsrchero_detail_componentdart-metadata

**Comment by chalin** [comment]
Thanks @sudolibre!
