### ISSUE TITLE
package vs doc link on `version` page tough to understand

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-webdev#1242]
https://webdev.dartlang.org/version

Suggestion: replace the icon w/ 'Guide' or similar.

Maybe put it on another line?

**Comment by chalin** [comment]
We've been experimenting with the version table layout for a while now. I've been trying to keep the table as compact as possible (it already doesn't fit nicely on most mobile devices, resulting in a need to scroll the page left and right). That was part of the reason for using an icon. Always forcing the icon to be placed on a new line seems to unnecessarily bloat the table. (Just sharing rational, but I'll be glad to rework it if you still feel that it is needed.)

**Comment by chalin** [comment]
@kwalrath and I discussed this: I'll submit a simple fix to start off with, and well see if that will take us in the right direction (of making the table more readable).

**Comment by kevmoo** [comment]
Thanks!

**Comment by chalin** [comment]
@kevmoo, @kwalrath: how about the following (shown for both narrow and wide displays):

<img width="300" alt="screen shot 2018-01-12 at 08 49 10" src="https://user-images.githubusercontent.com/4140793/34879182-66370976-f77a-11e7-913d-bf45ca486737.png">

<img width="651" alt="screen shot 2018-01-12 at 08 49 27" src="https://user-images.githubusercontent.com/4140793/34879218-7d9cddb6-f77a-11e7-952b-dd0f71d3086e.png">

**Comment by chalin** [comment]
> We could use bootstrap columns to take advantage of horizontal space, when it exists.

The package list isn't too long and so it reads well (IMHO) when laid out vertically. I'm not sure it would read as well if the package entries were laid out from left-to-right, with overflow entries on the next line. WDYT?

PR #1255 implements the solution illustrated above (with pub renamed to package).

**Comment by kwalrath** [comment]
I can try a column presentation (once you've committed #1255) and see what you think.

**Comment by kevmoo** [comment]
Nice! https://webdev.dartlang.org/version

**Comment by kwalrath** [comment]
Ugh, I forgot that this was all programmatically generated. I was planning to use `<div class="row">
<div class="col-md-6" markdown="1">...<div class="col-md-6" markdown="1">`, like in https://webdev.dartlang.org/angular, but the loop makes that harder than I'm willing to deal with.

**Comment by chalin** [comment]
Followup #1263
