### ISSUE TITLE
Link to 5-dev changelog from master changelog

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1246]

**Comment by kwalrath** [comment]
How about something like this at the top of the "Also see" list:

* [Changelog for the 5.0.0-alpha+2 version of this site](https://webdev-dartlang-org-dev.firebaseapp.com/changelog)

**Comment by chalin** [comment]
The Angular version number is at the top of every page of the 5-dev site. How about showing an abridged version ID instead:

* [Changelog for the 5.0 (dev) version of this site](#)
