### ISSUE TITLE
[Angular] "Organization" table rows look clickable but aren't

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/site-webdev#125]
URL: https://angulardart-org-dev.firebaseapp.com/angular/guide

The rows in the table below look clickable (they use the material [expansion panel](https://material.google.com/components/expansion-panels.html) look), but they aren't:

![organization-table](https://cloud.githubusercontent.com/assets/211513/20409393/43b37b0c-acce-11e6-9400-e4a1ded735c2.png)

**Comment by chalin** [comment]
Chapter titles are now links; fixed via #126 (which originated from https://github.com/angular/angular.io/pull/2821).
