### ISSUE TITLE
[5-dev] Upgrade to 5.0.0-alpha+3

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1253]
Waiting on angular_components, which is waiting on sass_builder :).

**Comment by kwalrath** [comment]
And... now 5.0.0-alpha+4 is out. :)

**Comment by chalin** [comment]
This is complete, modulo the use of the github_sync branch of angular_components (which is the soon-to-be-released version compatible with Angular 5.0.0-alpha+3).

Closed by #1266, #1267, #1272, #1273
