### ISSUE TITLE
Black is the new black

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/site-webdev#128]
On this page we have an IDE screenshot:

Can we change it to the black (Dracula) theme? White IDEs are so nineties!
![screen shot 2016-11-18 at 10 01 50](https://cloud.githubusercontent.com/assets/13644170/20424424/0d6dcc98-ad76-11e6-86d7-21c21e7bcfcf.png)

**Comment by chalin** [comment]
We might want to be consistent across all Dart sites.
@kwalrath @Sfshaza - any opinion about this?

**Comment by Sfshaza** [comment]
"So 90s", eh? I defer to your opinion on this, though I would either file a new bug or expand this bug. It could take some time to make everything consistent.

**Comment by lrhn** [comment]
There is the option of showing both, like https://github.com/reedes/vim-colors-pencil or similar. Take a screen-shot of both light and dark, then cut along any line through the center.

Obviously that looks even better if you use a Solarized color scheme :)

**Comment by kwalrath** [comment]
Where's the code that we used for this screenshot? @filiph, did you write it?

**Comment by kwalrath** [comment]
Oh, and to Patrice's point, I don't think we want to be consistently black across all our sites. I tried using a dark theme in one screenshot, and it was too hard to see selections.

But I don't mind using a dark theme on the homepage.

**Comment by filiph** [comment]
FWIW, all tutorials on developers.google.com have the light color theme (see any video from the [Firecasts](https://www.youtube.com/watch?v=OsWZ3vcInq8&list=PLOU2XLYxmsIKkg55tSHz0Xc8ZMVS1GJQL) series, for example). And it's not just Google: companies like [Docker](https://www.google.com/search?q=docker+tutorial&espv=2&source=lnms&tbm=isch&sa=X&ved=0ahUKEwik8IK3v47TAhVW2mMKHShEBOgQ_AUIBygC&biw=1440&bih=1014#tbm=isch&q=code+site:docker.com&*)] tend to show code screenshots and screencasts in the light color theme. I guess it's easier and looks nicer when all your surrounding text is black-on-white.

Full disclaimer: I actually _like_ the light color scheme. So I am biased.

@kwalrath: yes, that's my code (and I just realized I haven't published it to github). But we can use any project (Istvan's GWT-to-Dart demo app?).

**Comment by chalin** [comment]
I second that; I also believe that light color themes are easier to read.
