### ISSUE TITLE
Upgrading from AngularDart1

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/site-webdev#129]
I can't seem to find any docs on how to upgrade from AngularDart1 to AngularDart2?

**Comment by chalin** [comment]
FYI, at some point it was decided that there were other docs to be written that had higher priority.

**Comment by kwalrath** [comment]
If someone wrote a blog post or medium article, we'd happily point to it and, if appropriate, adapt it for use in the site.

**Comment by kwalrath** [comment]
Looks like this is not going to happen.
