### ISSUE TITLE
Make it easier to switch to 5.0 page version

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1293]
Lots of people seem to be trying Angular 5.0 now. We should make it easier for them to (1) know about and (2) open the 5.0 version of each page (and maybe example).

E.g. when I was looking at https://github.com/dart-lang/angular/issues/806, I easily found the angular_router docs at https://webdev.dartlang.org/angular/guide/router, but I wished for a one-click way to switch to the 5.0 version of the page (https://webdev-dartlang-org-dev.firebaseapp.com/angular/guide/router).

---
(Edit by @chalin)

- [x] Support switching main menu - #1341
- ~Support switching via side nav (for mobile/narrow screen devices).~ We've opted, for now, to only show the version dropdown in the main menu.

**Comment by chalin** [comment]
@kwalrath @kevmoo - for starters, how about a dropdown in the main menu. Menu entries would match stable / dev Angular versions. Such a dropdown would be visible from every page on wide displays; something that might look like this when open and closed:

---

<img width="961" alt="screen shot 2018-02-23 at 17 33 53" src="https://user-images.githubusercontent.com/4140793/36620203-ec0b071c-18bf-11e8-9e0e-ce0c81e98c20.png">

---

<img width="964" alt="screen shot 2018-02-23 at 17 34 04" src="https://user-images.githubusercontent.com/4140793/36620215-f69cf9e2-18bf-11e8-9ac0-3eccdf6f9ad8.png">

---

<img width="965" alt="screen shot 2018-02-23 at 17 29 14" src="https://user-images.githubusercontent.com/4140793/36620252-27085d1a-18c0-11e8-9f84-1e1005b214a9.png">

---

For mobile / narrow displays, I'm still exploring alternative sidenav options to help navigate between stable / dev site-webdev.

**Comment by kevmoo** [comment]
Hrm...Maybe.

Should we be clear the difference?

Stable vs preview?

**Comment by chalin** [comment]
Ok, how about this: 
> <img width="236" alt="screen shot 2018-02-23 at 18 52 06" src="https://user-images.githubusercontent.com/4140793/36622345-bb8501a0-18ca-11e8-9118-ff628d4c238b.png">

**Comment by kevmoo** [comment]
Align them vertically and I'm sold! :-D

**Comment by chalin** [comment]
Alignment "fixed" (the problem was actually with the menu title margin/padding -- FYI).

We don't have a convenient link to the site's [Versions](https://webdev.dartlang.org/version) page. This menu would seem like a good place to put it. WDYT?

<img width="409" alt="screen shot 2018-02-26 at 08 27 38" src="https://user-images.githubusercontent.com/4140793/36672877-f07c8b7a-1ace-11e8-8556-2760267a1f0b.png">

**Comment by kwalrath** [comment]
I might say just "Package versions" instead of "Site package versions", but otherwise LGTM.

**Comment by chalin** [comment]
See #1341; as mentioned in the opening comment, I've tweaked the appearance of the menu. Let me know which one you prefer.

**Comment by chalin** [comment]
@kwalrath @kevmoo - for the main site, how about also including a link to the previous docs as well?

> <img width="233" alt="screen shot 2018-02-27 at 09 47 06" src="https://user-images.githubusercontent.com/4140793/36735196-99763c60-1ba3-11e8-98f1-c5259f82c574.png">

**Comment by kevmoo** [comment]
Zero reason to point folks to 3.1.0 IMHO.

**Comment by chalin** [comment]
Ok, I'll comment out that code in my (upcoming) PR, though once work on 6-alpha starts, IMHO, it would make sense to keep a link to the last Dart 1 version of AngularDart (since not all folks migrate immediately).

**Comment by kevmoo** [comment]
SGTM

**Comment by chalin** [comment]
Both www.dartlang.org and webdev have the site version dropdown from the main nav now.
