### ISSUE TITLE
Clarify CORS headers in JSON article, fixing bug for Firefox

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#13]
_From @sethladd on January 16, 2015 23:18_

Relevant pull request: https://github.com/chrisbu/dartlang_json_webservice_article_code/pull/9

Analysis: https://code.google.com/p/dart/issues/detail?id=16127#c5

Section of doc: https://www.dartlang.org/articles/json-web-service/#a-note-on-cors-and-httprequest

Suggestion: we should make it very clear that the header's value is `"*"`

_Copied from original issue: dart-lang/www.dartlang.org#1223_

**Comment by kwalrath** [comment]
Do we really need to change the doc? It only mentions the CORS header once, with no code shown.

**Comment by kwalrath** [comment]
_From @sethladd on February 9, 2015 16:34_

Looking again, we don't need to mention '*'.

However, we should rewrite the code to use dart:js instead of package:js.

**Comment by kwalrath** [comment]
It's not a straight substitution, since the dart:js API is different from package:js. Would @chrisbu be up for updating that code? (It doesn't seem to be in the chrisbu/dartlang_json_webservice_article_code repo, but it probably should be.) If he updates the code, I'll be happy to update the article text.

**Comment by kwalrath** [comment]
_From @sethladd on February 9, 2015 17:6_

Chris merged a PR from me last week. We'll have to update the code ourselves and send the PR.

I think the conversion is pretty straight forward, but agree that it's not as simple as replacing the import.

**Comment by chalin** [comment]
The article is going to be deleted (#1634), so this is N/A.
CORS headers are covered here: https://www.dartlang.org/tutorials/dart-vm/httpserver#a-note-about-cors-headers
