### ISSUE TITLE
[ng] code excerpt boxes shift as they load (layout thrashing)

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/site-webdev#130]
Start on https://angulardart-org-dev.firebaseapp.com/angular/guide/displaying-data

Click '4. User Input'  in the leftnav

Notice how the blue boxes shift as they load.

Animated gif sample:
![shift](https://cloud.githubusercontent.com/assets/13644170/20424559/d448be86-ad76-11e6-8811-ebb18fca541f.gif)

**Comment by kwalrath** [comment]
cc @ericjim

**Comment by chalin** [comment]
Cf. https://github.com/angular/angular.io/issues/2860 - where @alexwolfe has proposed to "do something to make this less jarring".

**Comment by kwalrath** [comment]
Update: It's much improved in the newly implemented angular.io. Jules says Igor, PeteB, or maybe Filipe would know more about the solution.

See angular/angular.io#2860 for more info.
