### ISSUE TITLE
Sitemap's API URLs are wrong

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1311]
Every API doc URL from https://webdev.dartlang.org/sitemap.xml that I've tested results in 404s. It looks like we need to add the package name (angular, angular_components, angular_forms, ...) to the path.

Some examples:

* https://webdev.dartlang.org/api/angular_components/throttleStream should be
  https://webdev.dartlang.org/api/angular_components/angular_components/throttleStream
* https://webdev.dartlang.org/api/angular_forms/formDirectives-constant should be 
  https://webdev.dartlang.org/api/angular_forms/angular_forms/formDirectives-constant
* https://webdev.dartlang.org/api/angular.security/TemplateSecurityContext-class should be
  https://webdev.dartlang.org/api/angular/angular.security/TemplateSecurityContext-class
* https://webdev.dartlang.org/api/angular/disposePlatform should be https://webdev.dartlang.org/api/angular/angular/disposePlatform

/cc @kevmoo (who'd noticed this in a report)

**Comment by chalin** [comment]
#1440 proposes to use http://pub.dartlang.org/documentation instead of generating API docs on our own. This issue becomes obsolete if #1440 is resolved.

**Comment by chalin** [comment]
Actually, until we decide about #1440, I've made the fix for this issue (since it was easy enough to resolve).
