### ISSUE TITLE
'Polymer' page – we should be super clear that this is not supported

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-webdev#1336]
From URL: https://webdev.dartlang.org/guides/polymer

Should tell folks we are focused on Angular and the associated packages are no longer supported – and will likely break with Dart2

Should also change the wiki link: https://github.com/dart-archive/polymer-dart/wiki

**Comment by kwalrath** [comment]
The FAQ has a question that I don't know how to update:

#### Q. Can I use web components with Dart?

Yes! [Polymer Dart] is a port of polymer to Dart. Polymer is a set of
polyfills and usability enhancements for web components.

**Comment by kevmoo** [comment]
CC @jakemac53 @sigmundch @dgrove @terrylucas  – we haven't validated any of the work to make sure "raw" web components work. It hasn't been a priority w/ Angular

**Comment by kwalrath** [comment]
For now, I've removed the web components question.
