### ISSUE TITLE
AngularDart alpha version link is inconsistent

### ISSUE THREAD

**Issue by nshahan** [dart-lang/site-webdev#1363]
Repro:

On the main page https://webdev.dartlang.org/ click AngularDart in the upper right corner. The dropdown menu shows __5.0.0-alpha+2__.

<img width="563" alt="screen shot 2018-03-02 at 1 49 37 pm" src="https://user-images.githubusercontent.com/2498387/36923576-95fa6712-1e20-11e8-8b98-4bfff74748fc.png">

After clicking that link once you end up on the dev version of the site. If you expand that dropdown menu again you will see __5.0.0-alpha+6__.

<img width="564" alt="screen shot 2018-03-02 at 1 50 24 pm" src="https://user-images.githubusercontent.com/2498387/36923625-b4d16f1e-1e20-11e8-89f8-c223335192e4.png">

**Comment by chalin** [comment]
Thanks for pointing that out. Package versions are pinned separately in each branch, and `master` is lagging behind.
