### ISSUE TITLE
[ng] serve Angular API docs via a separate site like flutter

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#137]
Flutter API docs are served externally from the main flutter site. We should consider doing the same for Angular API docs.

---

- ![screen shot 2016-11-20 at 9 33 52 am](https://cloud.githubusercontent.com/assets/4140793/20465037/1406bd1e-af09-11e6-8179-f78fc817fcef.png)
- Served via `docs.flutter.io`:
![screen shot 2016-11-20 at 9 34 12 am](https://cloud.githubusercontent.com/assets/4140793/20465038/1c126274-af09-11e6-9051-81c36a485f3a.png)

**Comment by chalin** [comment]
@yjbanov - how are the build and deployment of the flutter API docs handled (I couldn't seem to find the repo or build scripts)?

cc @kevmoo

**Comment by yjbanov** [comment]
I believe it's this: https://github.com/flutter/flutter/blob/master/dev/bots/docs.sh

@sethladd can speak more intelligently to our API doc infra.

**Comment by sethladd** [comment]
We use Firebase Static Hosting. We deploy to Firebase from Travis, on a green build and merge to master. We generated a Firebase token and set that in the Travis environment. We use the Firebase command-line tools to run the deploy.

**Comment by chalin** [comment]
Thanks, I'll try that!

**Comment by kwalrath** [comment]
What are the benefits of serving these from a separate site? (It _is_ strange that they're on this site but don't share the navigation, but are there other benefits?)

**Comment by kevmoo** [comment]
> What are the benefits of serving these from a separate site? (It is strange that they're on this site but don't share the navigation, but are there other benefits?)

AFAICT it's just that it's easier to make sure navigation doesn't break – at least I think.

...but that's about it. I think it's good for tracking and user experience, honestly.

**Comment by sethladd** [comment]
> What are the benefits of serving these from a separate site? 

It's a little easier for us to deploy the API docs as a self-contained, atomic bundle if they are served from a separate site. We deploy the API docs after green travis builds.

**Comment by chalin** [comment]
@sethladd - have Flutter folks given thought to versioning of (API and non-API) docs?

**Comment by chalin** [comment]
Our current scheme seems to be working well so I'll close this for now.
