### ISSUE TITLE
[5-dev] ng_test/github_issues example app: drop or move to dart-lang/examples?

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1372]
The [github_issues][] app was originally the main example used to illustrate angular_test. In fact, it was originally under the angular_test repo.

We have many more examples of the use of angular_test now, and this app is a bit of a challenge to maintain, in part because `ng_bootstrap` is lagging behind.

@matanlurey, would you mind if we dropped this example? Otherwise, how about moving it to https://github.com/dart-lang/angular/tree/master/examples?

cc @kevmoo @kwalrath 

[github_issues]: https://github.com/dart-lang/site-webdev/tree/5-dev/examples/ng_test/github_issues

**Comment by matanlurey** [comment]
Yup, I'd love to move it back to examples and maintain it.

Filed https://github.com/dart-lang/angular/issues/1011 to track.

**Comment by chalin** [comment]
Closed by #1404
