### ISSUE TITLE
'Changelog' page issue: badly formatted code

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1378]
From URL: https://webdev.dartlang.org/changelog

Code appears to be formatted as text, not `<pre>` code, at the bottom of the AngularDart 3.1 section.

![image](https://user-images.githubusercontent.com/2164483/37059558-a2cde142-2142-11e8-9f7b-3a362116a4fd.png)

**Comment by chalin** [comment]
Oh, that has been there since Sept. 2017 (#1083)! Ever since we moved that page out from under /angular. The `<?code-excerpt ...?>` directives only work under /angular. I'll submit a fix now.
