### ISSUE TITLE
'Pub for the Web' - mark build/serve as deprecated

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-webdev#1392]
From URL: https://webdev.dartlang.org/tools/pub

---

(Edit by @chalin)

- [x] Create a `pub build/server` --> build_runner migration guide #1393
- [x] 'dartdevc: The Dart Dev Compiler': update references pub build/serve #1398
- [x] Sweep site pages for `pub build/server`

Related: https://github.com/dart-lang/site-www/issues/649

**Comment by kevmoo** [comment]
@chalin – this is "in progress" right?

**Comment by chalin** [comment]
Closed by #1426
