### ISSUE TITLE
Add link from 5-dev to new gallery

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1414]
https://dart-lang.github.io/angular_components_example/ has links to source code AND adds datepicker.

**Comment by chalin** [comment]
Both master and 5-dev have this link. It is in the side nav under:

- ANGULAR DART COMPONENTS
  - Example

The link is also on the ANGULAR DART COMPONENTS page: third entry under "Resources for using AngularDart Components".

Was there something else that you meant?

**Comment by kwalrath** [comment]
Ah, it sounds like they're reusing the existing link. (The implementation is completely different.) Do you think we should remove the link from master?

**Comment by chalin** [comment]
I'd vote for status quo.

**Comment by kwalrath** [comment]
I should file an issue on the gallery to make the version more obvious.

**Comment by kwalrath** [comment]
Filed https://github.com/dart-lang/angular_components_example/issues/73.
