### ISSUE TITLE
firebase and superstatic don't redirect `/angular/` to `/angular`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-webdev#1418]
https://webdev.dartlang.org/angular
https://webdev.dartlang.org/angular/

I thought the firebase settings would fix this...

https://github.com/dart-lang/site-webdev/blob/c6a6435bdeb5187405ccd2fd535eb3d558b3dd9b/firebase.json#L4-L5

**Comment by chalin** [comment]
That's right. It is as if the settings aren't being respected. This would be a firebase / superstatic issue.

**Comment by kwalrath** [comment]
I've filed an internal bug against Firebase hosting at b/77869559.

**Comment by chalin** [comment]
I've noticed the same behavior for `/angular/guide/router`.

**Comment by kevmoo** [comment]
Meaning things are fixed?

**Comment by chalin** [comment]
Apparently so.

**Comment by kevmoo** [comment]
Just checked. Cool!
