### ISSUE TITLE
Pages to review before Angular 5 final

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1422]
For @kwalrath & engineering:

- [x] Router guide (@leonsenft):
  - https://webdev.dartlang.org/angular/guide/router and following pages
  - https://github.com/angular-examples/router
- [x] Testing guide: https://webdev.dartlang.org/angular/guide/testing (@matanlurey)
- [x] Tutorial part 5 (router): https://webdev.dartlang.org/angular/tutorial/toh-pt5 (@leonsenft) - #1742
- [x] Changelog: https://webdev.dartlang.org/changelog (@alorenzen) - #1720

**Comment by kwalrath** [comment]
Closing because it looks like we're all done here.

**Comment by chalin** [comment]
I'm going to use #1789 to track implementation of the review changes.

@matanlurey, where are the Testing doc review comments?

**Comment by matanlurey** [comment]
I think this got lost.
