### ISSUE TITLE
Code missing in example libapp_componenthtml-click, Angular 5.0.0-alpha+9

### ISSUE THREAD

**Issue by Henge9** [dart-lang/site-webdev#1448]
https://webdev-dartlang-org-dev.firebaseapp.com/angular/tutorial/toh-pt2#libapp_componenthtml-click

I see the folowing code:
`<li *ngFor="let hero of heroes">`
 ` <span class="badge">{{hero.id}}</span> {{hero.name}}`
`</li>`

I think it should look like this:
`<li *ngFor="let hero of heroes" (click)="onSelect(hero)">`
 ` <span class="badge">{{hero.id}}</span> {{hero.name}}`
`</li>`

**Comment by chalin** [comment]
Thanks for the issue! A fix is on its way.

**Comment by chalin** [comment]
Closed by #1449
