### ISSUE TITLE
build_runner links to point to package site – not readme file

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-webdev#1450]
https://webdev.dartlang.org/dart-2
https://webdev-dartlang-org-dev.firebaseapp.com/tools/build_runner

These pages point to https://github.com/dart-lang/build/blob/master/build_runner/README.md

This could be in a pre-release state. It's also not helpful for someone trying to use the package.

Better to point folks to 
https://pub.dartlang.org/packages/build_runner

**Comment by kevmoo** [comment]
Thoughts @natebosch @jakemac53 ?

**Comment by chalin** [comment]
@kwalrath - this was closed by #1452, right?

**Comment by kevmoo** [comment]
This page https://webdev-dartlang-org-dev.firebaseapp.com/dart-2 still needs to be updated.

Just remove the link at the bottom to the readme – should be in the `tools/build_runner` page only

**Comment by chalin** [comment]
Just to be sure: neither /dart-2 nor /tools/build_runner have a link to the build_runner README, but they do have a link to https://github.com/dart-lang/build/blob/master/docs/getting_started.md. So you want the link to the Getting Started page to be replaced by a link to the pub package entry for build_runner?

**Comment by kevmoo** [comment]
Er, sorry.

There should be one link to docs/getting_started.md – and it should be from
tools/build_runner

Does that make sense?

**Comment by chalin** [comment]
Yes, thanks for clarifying.

**Comment by chalin** [comment]
Closed by #1463
