### ISSUE TITLE
'Dart 2 Migration Guide' page issue

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-webdev#1458]
From URL: https://webdev.dartlang.org/dart-2

Remove link to build_runner getting started markdown page from `dart-2` pages.

We should point folks to the webdev `build_runner` page first – then that page can send folks off to the readme...

**Comment by chalin** [comment]
Dup of #1460?

**Comment by kevmoo** [comment]
I'd say #1460 is a dupe of this! 😄

**Comment by kevmoo** [comment]
No. This is about linking to https://github.com/dart-lang/build/blob/master/docs/getting_started.md

**Comment by kevmoo** [comment]
This seems fixed now

https://webdev.dartlang.org/dart-2 links to
https://webdev-dartlang-org-dev.firebaseapp.com/dart-2

link to the build_runner source repo is gone.

Can close?

CC @chalin
