### ISSUE TITLE
/dart-2 should be the same in v4 & v5

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1459]
Make 5-dev /dart redirect to v4. Or just link to it?

**Comment by chalin** [comment]
Btw, they can't be the same, because there is content that exists only on one site and not the other. Ideally, we should have only one such page and redirect to the other. The most complete version is the 5-dev version.

**Comment by kwalrath** [comment]
Maybe we should gut the v4 version and link from it to the v5 version.

I just don't want to auto-switch people to a different site without letting them know that they're changing sites.

**Comment by kevmoo** [comment]
SGTM
