### ISSUE TITLE
Rename "Dart 2 Migration Guide" to include "Dart for the web"?

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1464]
Rename _Dart 2 Migration Guide_ at https://webdev.dartlang.org/dart-2 to something like

> _Dart-2-for-the-web Migration Guide_

This would help make it obvious that this page isn't trying to be a complete Dart 2 migration guide. The basic Dart 2 migration guide is on dartlang.org.

@kwalrath @kevmoo WDYT?

Make the change on both branches:

- [x] master - #1525
- [x] 4.x - #1531

**Comment by kevmoo** [comment]
SGTM

**Comment by kwalrath** [comment]
Sounds good except for all the hyphenation. How about:

Dart 2 Migration Guide for Web Apps
or
Dart 2 Web App Migration Guide

**Comment by chalin** [comment]
Closed by #1525 and #1531
