### ISSUE TITLE
Routing Overview: page-relative links don't always work

### ISSUE THREAD

**Issue by marcojakob** [dart-lang/site-webdev#1496]
From URL: https://webdev.dartlang.org/angular/guide/router/

If the menu is used in the documentation for the `AngularDart` version, the URL contains a **trailing slash**. With the trailing slash a few links lead into `404`'s. On the page above, for example, the link to *base href* details is wrong. It is https://webdev.dartlang.org/angular/guide/router/router/1#base-href instead of https://webdev.dartlang.org/angular/guide/router/1#base-href

A forwarding that removes the trailing slash would be good. Or the other way: add trailing slashes everywhere.

**Comment by chalin** [comment]
Thanks for filing an issue. This problem arises because of #1418. The specific version menu problem is marked as one of the work items in #1484. I'll keep this issue open as a separate reminder.
