### ISSUE TITLE
Examples: update min SDK to be 2.0.0-dev.48.0

### ISSUE THREAD

**Issue by SeekMyCosmic** [dart-lang/site-webdev#1534]
I cannot run it properly, pls help me. Thanks a lot.

------------------------------------------------
D:\Users\XXX\DartProject\user-input-master>**pub get**
Resolving dependencies...
Overriding the upper bound Dart SDK constraint to <=2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c for the following packages:

archive, args, bazel_worker, boolean_selector, build_barback, build_config, charcode, cli_util, code_transformers, convert, crypto, csslib, dart_style, fixnum, front_end, glob, graphs, html, http,
 http_multi_server, http_parser, intl, io, isolate, js, json_annotation, kernel, logging, matcher, meta, multi_server_socket, node_preamble, package_config, package_resolver, path, plugin, pool, p
rotobuf, pub_semver, quiver, quiver_hashcode, shelf, shelf_packages_handler, shelf_static, shelf_web_socket, source_map_stack_trace, source_maps, source_span, stack_trace, stream_channel, string_s
canner, term_glyph, tuple, typed_data, yaml

To disable this you can set the PUB_ALLOW_PRERELEASE_SDK system environment variable to `false`, or you can silence this message by setting it to `quiet`.
Got dependencies!

D:\Users\XXX\DartProject\user-input-master>**pub run build_runner serve**
[INFO] Generating build script...
[INFO] Generating build script completed, took 525ms

[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 19ms

[INFO] Waiting for all file watchers to be ready...
[INFO] Waiting for all file watchers to be ready completed, took 83ms

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 856ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 3ms

[INFO] Running build...
[INFO] 5.8s elapsed, 2/21 actions completed.
[INFO] 7.0s elapsed, 133/135 actions completed.
[INFO] 8.2s elapsed, 225/229 actions completed.
[INFO] 9.3s elapsed, 239/243 actions completed.
[INFO] 10.4s elapsed, 265/269 actions completed.
[INFO] 11.5s elapsed, 351/382 actions completed.
[SEVERE] build_web_compilers|ddc on package:meta/meta.module:

NoSuchMethodError: No static method 'tryParse' declared in class 'int'.
Receiver: int
Tried calling: tryParse("2")
[SEVERE] build_web_compilers|ddc on package:meta/meta.module:

**Log trimmed by @chalin**

**Comment by chalin** [comment]
You'll need at least sdk: '>=2.0.0-dev.48.0 <2.0.0', which reminds me that the min SDK constraint isn't correct in the pubspec.yaml. I'll fix that. Thanks for reporting the issue!

**Comment by SeekMyCosmic** [comment]
2018-04-25 22:49 GMT+08:00, Patrice Chalin <notifications@github.com>:
> You'll need at least sdk: '>=2.0.0-dev.48.0 <2.0.0', which reminds me that
> the min SDK constraint isn't correct in the pubspec.yaml. I'll fix that.
> Thanks for reporting the issue!
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dart-lang/site-webdev/issues/1534#issuecomment-384314940

Thank you for your reply so quickly!
It's my pubsepc.yaml updated from the newest example in github.
I'll try to update "environment" to "sdk: '>=2.0.0-dev.46.0 <2.0.0'"
and test it.
----------------------------
name: ChatExample
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: Cosmic <email@example.com>

environment:
  sdk: '>=2.0.0-dev.46.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  #route: ^0.4.6
  #routes: ^0.1.4

dev_dependencies:
  build_runner: ^0.8.2
  build_test: ^0.10.1
  build_web_compilers: ^0.3.6

**Comment by chalin** [comment]
You'll need at least 2.0.0-dev.**48**.0. To be clear: updating the pubspec is optional, but upgrading the version of the Dart SDK that you are using is mandatory. 2.0.0-dev.50.0 is out so you might as well get the latest.
