### ISSUE TITLE
Document use of webdev tool

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1537]
From https://github.com/dart-lang/angular/issues/1274.

@kwalrath @kevmoo: I'm assuming that we'll still want to keep the [build_runner tool page](https://webdev-dartlang-org-dev.firebaseapp.com/tools/build_runner), but promote the use of webdev?

- [x] Update site install scripts with: `pub global activate webdev`
- [x] Docs
  - [x] Add webdev tools page
  - [x] Update Setup page
  - [x] Add page for webdev under tools
  - ...
- [x] E2E: switch to using `webdev`

Related:
- Switch all docs and uses of build_runner to webdev https://github.com/dart-lang/angular/issues/1274

**Comment by kevmoo** [comment]
See also https://github.com/dart-lang/site-webdev/issues/1547
