### ISSUE TITLE
API references in sitemap.xml are sending 404s

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-webdev#1539]
https://github.com/dart-lang/site-webdev/blob/e00a6b8c277c667cf4bb8f1e9e704cfc2c74fc19/src/sitemap.xml#L27

See 
[webdev_crawl_issues.txt](https://github.com/dart-lang/site-webdev/files/1948559/webdev_crawl_issues.txt)

**Comment by chalin** [comment]
I haven't reworked the sitemap.xml for the Angular 4 version of the site. The Angular 5 version should be ok. We'll be switching sites "soon" so does this need to be fixed? /cc @kwalrath

**Comment by chalin** [comment]
Closed by 7e77261f3bdbcfb97873c76f10c2b9abfe7f30ec. E.g., https://webdev.dartlang.org/sitemap.xml now shows:

- https://webdev.dartlang.org/api/angular/angular/DecimalPipe-class

instead of the invalid

- https://webdev.dartlang.org/api/angular/DecimalPipe-class

**Comment by kevmoo** [comment]
Thanks!
