### ISSUE TITLE
Fix hrefs that use target="_blank"

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-webdev#154]
See this issue:  https://github.com/dart-lang/site-www/issues/176

On webdev, I found 62 instances.

**Comment by Sfshaza** [comment]
(I had added the file when I created the issue, but didn't notice that it rejected it without an extension, so I'm adding it again.)

[out2.txt](https://github.com/dart-lang/site-webdev/files/622447/out2.txt)

**Comment by kwalrath** [comment]
We need a macro for this.
