### ISSUE TITLE
Update design: logos, colors, etc

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1569]
- [x] Main logo: opt for **one** of the following
  - [ ] Create a "Dart for the web" logo lockup
  - [x] Base Dart logo w/o lockup
- [x] favicon: opt for **one** of the following
  - [ ] New "Dart for the web" logo
  - [x] Base Dart logo
- [x] Social media shared images: opt for **one** of the following
  - [ ] "Dart for the web", **or**
  - [x] Dart logo as og_image #832 
- [x] Frontpage:
  - [x] Color scheme: get agreement on new colors to use (no more green :)
  - [x] "Angular love" image update
  - [x] Dart icon in "Open DartPad"
  - [ ] Time permitting, address: Frontpage edits #1577
- [x] Nav bars
  - [x] Mainnav:
    - [x] Logo update
    - [x] Switch to dartlang.org color scheme
    - [x] Update dropdown color scheme
    - [x] Ensure nav has no glitches at media query transition sizes (for mobile in particular).
  - [x] Sidenav
     - [x] Logo update
- [x] Footer color like flutter.io
- [ ] All other site pages: check for uses of old logo and switch to new ones (including page-local image folders)
- [x] Examples:
  - [x] Update favicon in boilerplate folder
  - [x] Scan for use of all logos in example project folders
  - [x] ACX codelab has a few copies of the old "Angular love" image.
- [ ] Ensure submodule branch was merged and that this PR points to the updated master.

Related:
- https://github.com/dart-lang/site-www/issues/651
- https://github.com/dart-lang/site-www/pull/830

**Comment by chalin** [comment]
It's probably best for me to wait for the new "Dart for the web" logos. WDYT @kwalrath?

**Comment by kwalrath** [comment]
When we aren't directly referring to Angular, there's a material-compliant browser icon we can use. Or we can use the Dart logo, if that's appropriate.
