### ISSUE TITLE
Socket IO support

### ISSUE THREAD

**Issue by Mukhammadjon-Jalolov** [dart-lang/site-webdev#1584]
Hi everyone! I do research in JavaScript frontends and have a Socket.io Server. Now I wanted to use AngularDart for my frontend. I`m new in Dart language and need to make Socket IO work for my project...

I see there is a project [https://pub.dartlang.org/packages/socket_io_client#-readme-tab-](url) But How can I use Socket.IO in Components or in a Service? The example shows the Socket.IO client code is in Main( ) { } Dart Function. But how to make Socket.io instance available to Components? 
![image](https://user-images.githubusercontent.com/38403832/39922454-82f11194-551f-11e8-8498-5264f2a78b4c.png)

Thanks very much!

**Comment by kwalrath** [comment]
@matanlurey do you know of any examples?

**Comment by matanlurey** [comment]
No, unfortunately. You'd have to reach out to that package, we don't own it.
