### ISSUE TITLE
'Master/Detail' page issue

### ISSUE THREAD

**Issue by hltan** [dart-lang/site-webdev#1603]
From URL: https://webdev-dartlang-org-dev.firebaseapp.com/angular/tutorial/toh-pt2

typo. 
lib/app_component.css
line 43
should be.
padding: 0.8em 0.7em **0.8em** 0.7em;

**Comment by bcko** [comment]
Submitted a pull request to fix padding

**Comment by chalin** [comment]
No, this isn't a typo.
