### ISSUE TITLE
[TRIAL] Drop use of `new` from example apps

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1611]
@chalin when you get a chance, could you try creating a copy of our AngularDart example code that doesn't use `new`, so we can see what happens? (We know that omitting `const` can break things, but we haven't spotted anything with `new` yet.)

Related issues: dart-lang/angular#1313

**Comment by bcko** [comment]
@chalin @kwalrath 

I deleted all `new` instances from the master branch of [toh-6](https://github.com/angular-examples/toh-6).
`webdev serve` and `webdev build` finishes without any errors.

**Comment by chalin** [comment]
Thanks for the feedback @bcko.

**Comment by chalin** [comment]
@kwalrath - I'm hesitant to do this w/o @matanlurey's thumbs-up, given that an app may appear to work for a given +X release, but then break in unexpected ways (and cryptic error messages), for subsequent releases.

**Comment by kwalrath** [comment]
This was an action item from a meeting that included @matanlurey. :) They didn't want most people trying it, but trusted you to be able to test it and characterize any issues that came up.

**Comment by kwalrath** [comment]
To be clear, we should NOT change our committed code samples. It's easy enough to remove new, but much harder to add it back if we do find some problem.

**Comment by chalin** [comment]
Got it! Thanks for clarifying (and confirming that Matan was in the loop).

**Comment by chalin** [comment]
We're beyond the trail phase, see #1650.
