### ISSUE TITLE
'Setup for Development' page issue

### ISSUE THREAD

**Issue by chstrongsg** [dart-lang/site-webdev#1625]
From URL: https://webdev.dartlang.org/angular/guide/setup

Get Prerequisites says:
Dart SDK 1.24.3 or a compatible version

However the quickstart repo is for SDK 2 or above:
https://github.com/angular-examples/quickstart

charms:angular_tour_of_heroes$ pub get
Resolving dependencies... (2.2s)
Package angular_app requires SDK version >=2.0.0-dev.51.0 <2.0.0 but the current SDK is 1.24.3.

This is rather confusing for newbies like me. And as SDK version 2 is still in DEV and not in full release, wouldn't it make more sense, to actually keep the quickstart in this version? Or make a quickstart for SDK2 which is separate?

**Comment by chalin** [comment]
I'm sorry that you've found some parts of the Setup page unclear.

The setup page, https://webdev.dartlang.org/angular/guide/setup, carefully describes how to get the **4.x** branch of the repo. Specifically, the first two links to the quickstart repo in that page are:

- https://github.com/angular-examples/quickstart/tree/4.x
- https://github.com/angular-examples/quickstart/archive/4.x.zip

Notice the `4.x` in the URLs.

The steps under _Use WebStorm’s Git support_ state that you clone from https://github.com/angular-examples/quickstart, but immediately detail how to switch to the 4.x branch:

> <img width="500" alt="screen shot 2018-06-02 at 12 40 05" src="https://user-images.githubusercontent.com/4140793/40878662-1b10183c-6662-11e8-8ed8-fe0a47ee3565.png">

Maybe you skipped steps 6 and 7, or perhaps you were working from the command line? Is there something else that we missed on that page? Thank you in advance for clarifying.

**Comment by chstrongsg** [comment]
I'm using the command line. Apologies maybe I need to do more reading, because I don't understand yet, how the version of angular dart and angular SDK fit together.

I just followed the instructions and tripped over this.

**Comment by chalin** [comment]
No worries. If you are just starting, maybe you'd like to work through the _Get Started_ page from the AngularDart 5 / Dart 2 version of the site? Here is the URL: https://webdev-dartlang-org-dev.firebaseapp.com/guides/get-started

That version of the page was recently updated to have **complete setup instructions** for both **command-line** users and WebStorm users. If you find that anything is missing, please let us know.

**Comment by chalin** [comment]
@kwalrath - maybe we need to update the _Setup_ page, similar to what we did for the _Get Started_ page? WDYT?

**Comment by chstrongsg** [comment]
Thank you very much for your feedback chalin. I followed through the get-started guide and can confirm, that it works for the dumbest possible user (me) :)

I have seen that the documentation of the tour of heroes now has SDK version 2 mentioned.

I'll walk through the tour_of_heroes again and will provide feedback, in case i see any issues.

**Comment by chalin** [comment]
I'm glad that you like the updated _Get Started_ page. Remember that there is [no such thing as a dumb question](https://en.wikipedia.org/wiki/No_such_thing_as_a_stupid_question)! It is thanks to feedback from everyone that we can improve the docs!

**Comment by chstrongsg** [comment]
Might have found a small thing. When I built the project with the SDK 2, angular ^5.0.0 alpha was automatically in my pubspec.yml.

On following page, version ^4.0.0 is mentioned.
angular/tutorial/toh-pt5.

Section "Update Pubspec":

dependencies:
  angular: ^4.0.0
  angular_forms: ^1.0.0
  angular_router: ^1.0.2

If adding the 1.0.2 version to angular version 5.0.0-alpha, there will be an error, that the versions are incompatible.

This seems to be required for angular: ^5.0.0-alpha

dependencies:
  angular: ^5.0.0-alpha
  angular_forms: ^2.0.0-alpha
  angular_router: ^2.0.0-alpha+12

**Comment by chstrongsg** [comment]
And based on above, ROUTER_PROVIDERS doesn't seem to exist in the alpha version. When I clicked onto the documentation section of angular/guide/router, which is for Angular 4. On the top there is a link for Angular 5, but this displays the main page. 

Do you recommend downgrading to Angular 4?

**Comment by chalin** [comment]
> On following page, version ^4.0.0 is mentioned.
angular/tutorial/toh-pt5.

Can you share the full URL to the page where you are seeing this? It seems like you've fallen back to the Angular 4 version of the site. From https://webdev-dartlang-org-dev.firebaseapp.com/angular/tutorial/toh-pt5#update-the-pubspec, I see `angular: ^5.0.0-alpha` mentioned.

**Comment by chstrong** [comment]
Apologies, was travelling. I can't really reproduce what I did to land on the 4 version. I'm continuing with the 5, and if I experience anything I will let you know. Thanks for the very good support.

**Comment by chalin** [comment]
> I'm continuing with the 5, and if I experience anything I will let you know. 

Sounds good.

> Thanks for the very good support.

👍
