### ISSUE TITLE
Where is the VS Code love?

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/site-webdev#1683]
In the section “Batteries included” it _really_ should mention VS Code. It's by far the nicest environment for programming Dart thanks to @DanTup .

I would even go so far to put it on the same level as Web Storm, if not ahead of! 😉

**Comment by chalin** [comment]
I agree that the VS Code experience is great. As mentioned in #1467, we're waiting on

> ... web development isn't complete yet; see:
> 
> - Add the ability to run Dart web apps #68
> - Help unblock DartCode backlog on web integration #1025

Thanks for the ping. I'm going to close this issue in favor of #1467. Let's continue the conversation there.
