### ISSUE TITLE
Incorporate or link to dart-lang/angular/doc

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1689]
The dart-lang/angular repo's [doc directory](https://github.com/dart-lang/angular/tree/master/doc) has a bunch of good docs that need to be incorporated into or referred to by the webdev.dartlang.org docs. I'll update the deferred loading reference right now, but we need to do much more.

Related: dart-lang/angular#1452.

---

- [ ] separate the notes by subdirectory, and have descriptions of what (generally) is in each subdirectory
- [ ] link to the source directory (or directories)
- [ ] Exclude internally-focused `developing/` directory

**Comment by chalin** [comment]
I'm exploring ways to integrate and/or link to the docs under webdev (w/o moving the original sources from the angular repo).
