### ISSUE TITLE
'About AngularDart Components' page beautification

### ISSUE THREAD

**Issue by filiph** [dart-lang/site-webdev#1705]
From URL: https://webdev.dartlang.org/components/

What do y'all think about adding a screenshot to this page? And making the link to the [example page](https://dart-lang.github.io/angular_components_example/) a lot more prominent than it currently is?

 It's currently number 1 in search results for `[angulardart components]`. 

cc @kwalrath @nshahan

**Comment by kwalrath** [comment]
Absolutely right. I'll do this.

**Comment by kwalrath** [comment]
Funnily enough, we _do_ have a screenshot on that page, but it's below the fold. I think I'll replace/augment it with a picture of the gallery that's a link to the gallery.

**Comment by chalin** [comment]
Ah right, and the image is pushed further below because of this problem: #1018 (FYI).
