### ISSUE TITLE
Bad URL for:https://webdev.dartlang.org/api/angular/angular/ViewChildren-class

### ISSUE THREAD

**Issue by pslavers** [dart-lang/site-webdev#1727]
URL: https://webdev.dartlang.org/api/angular/angular/ViewChildren-class
Expected page:

**Comment by Augustpi** [comment]
please try the Url
https://webdev-angular4-dartlang-org.firebaseapp.com/api/angular/angular/ViewChildren-class

**Comment by chalin** [comment]
Thanks for filing an issue! API doc generation is broken at the moment (https://github.com/dart-lang/dartdoc/issues/1728). In the meantime, if you'd like to use the Angular 5 version of the page, see the API docs served from the pub site: for example, https://pub.dartlang.org/documentation/angular/5.0.0-beta+2/angular/ViewChildren-class.html

**Comment by chalin** [comment]
Fixed for the time being. I'll close this issue in favor of using #1729 to track the original problem.
