### ISSUE TITLE
API Reference displays no data

### ISSUE THREAD

**Issue by benmonty** [dart-lang/site-webdev#1729]
When attempting to view the API Reference at https://webdev.dartlang.org/api, I do not actually see anything displaying beneath the package/type filter.

When loading this page with the developer tools open, there appears to be some errors:

`GET https://webdev.dartlang.org/api/api-list.json 404 ()`
and
`angular.js:14642 Possibly unhandled rejection: ...`

**Comment by chalin** [comment]
Thanks, we're working on the situation (related #1727).

**Comment by chalin** [comment]
Fixed, but I'll keep this open until the original cause of the problem (https://github.com/dart-lang/dartdoc/issues/1728) is resolved.

**Comment by chalin** [comment]
Closing since #1730 is a viable solution. I'll open a followup PR to upgrade dartdoc once https://github.com/dart-lang/dartdoc/issues/1728 is fixed.
