### ISSUE TITLE
Improve styling of header and footer text under /angular

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#173]
- [x] The header links of pages under /angular are spindly, compared to the rest of the site.

For example, from angular/guide/learning-angular:
![angular_guide_learning-angular](https://cloud.githubusercontent.com/assets/2164483/20819464/4fcf4da0-b7e9-11e6-98ce-fc97e42579d5.png)

From the webdev.dartlang.org homepage:
![webdev](https://cloud.githubusercontent.com/assets/2164483/20819490/75cf5676-b7e9-11e6-8bf2-d634d5964e25.png)

- [ ] The same is true of the footer:
![image](https://cloud.githubusercontent.com/assets/2164483/20819592/2f8ff21e-b7ea-11e6-9dc2-40f6541e6c76.png)  ![image](https://cloud.githubusercontent.com/assets/2164483/20819594/360ba2b4-b7ea-11e6-9426-be0166b2b556.png)

**Comment by kwalrath** [comment]
@ericjim maybe you can figure out why this is happening?

**Comment by chalin** [comment]
Header (main nav) issue was solved via #194.
The footers also now look ok to me. @kwalrath, do you agree?

**Comment by kwalrath** [comment]
The footer links are now bold, which is not quite perfect (though better).

webdev: ![image](https://cloud.githubusercontent.com/assets/2164483/20936809/e5ed88ee-bb98-11e6-980a-61683d536322.png) &nbsp;&nbsp;&nbsp;www: ![image](https://cloud.githubusercontent.com/assets/2164483/20936840/0c561faa-bb99-11e6-9621-2f06473c3da3.png)

**Comment by chalin** [comment]
Indeed, it was the best compromise I could arrive at for the time being.

**Comment by chalin** [comment]
@kwalrath - could we close this issue an open another or at least downgrade it to a P3/4?

**Comment by kwalrath** [comment]
I'll open a new issue, since the bold font isn't just under /angular/
