### ISSUE TITLE
Tutorial(toh-4): text references "new" keyword which was removed from example

### ISSUE THREAD

**Issue by avilladsen** [dart-lang/site-webdev#1745]
The Tour of Heroes page on services (toh-4) has a section on not creating new instances of services, which talks about the "new" keyword as a stand-in for the idea of creating a new instance. That's confusing now that the new keyword is optional, especially since "new" has been removed from the related example (#1650).

Here's the relevant snippet from the page:

### Don't use *new* with the *HeroService*

How should the `AppComponent` acquire an instance of `HeroService`?

You could create a new instance of the `HeroService` with `new` like this:
```
  HeroService heroService = HeroService(); // DON'T do this
```

**Comment by chalin** [comment]
Yes, it is confusing, sorry. Thanks for filing this issue!
