### ISSUE TITLE
Fix section titles, so TOC entries are parallel

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#175]
Most noticeable in Angular docs, but other docs are inconsistent, too.

**Comment by chalin** [comment]
If this becomes a WtD issue, then we might want to clarify what makes "TOCs look good"?

**Comment by kwalrath** [comment]
How to check and fix the TOC for a page:

1. Go to the page (e.g. https://webdev.dartlang.org/guides/get-started).
2. Make sure your browser is wide enough for the TOC (if one exists) to show on the right side. Example:
![image](https://user-images.githubusercontent.com/2164483/32810832-a2477718-c951-11e7-9178-ca34df17eff1.png)
3. Are the TOC entries [parallel](http://community.copypress.com/how-parallelism-improves-writing/)? If so, you're done with this file. If not, edit the section heads so that they're parallel.

**Comment by gryclmn** [comment]
Is this no longer an issue after this repo has been split between dart.dev and angulardart.dev?

**Comment by kwalrath** [comment]
True, @gryclmn. Thanks for pointing this out. I should remove site-webdev from the good-for-beginners lists and make sure dart.dev is added.
