### ISSUE TITLE
Webdev *fails* with unexpected exception.

### ISSUE THREAD

**Issue by MrWeatherallScience** [dart-lang/site-webdev#1752]
From URL: https://webdev.dartlang.org/tools/webdev

There is a problem with the latest release of Dart SDK (2.0.0-dev.69.4). 
When running **webdev build** or **webdev serve** this error occurs: 
`Can't load Kernel binary: File size is too small to a valid kernel file.`
The command then fails with an unexpected exception.

I have completely uninstalled and reinstalled the SDK and still get the same issue.

**Comment by chalin** [comment]
This is apparently a known issue, which you can track from: "Can't load Kernel binary: File size is too small to a valid kernel file." https://github.com/dart-lang/webdev/issues/70. I'll close this issue since there is no impact on the webdev docs.
