### ISSUE TITLE
'Master/Detail' page issue: Angular Core import missing

### ISSUE THREAD

**Issue by psummo** [dart-lang/site-webdev#1754]
From URL: https://webdev.dartlang.org/angular/tutorial/toh-pt2

When You write about insert new  directives

directives: [**coreDirectives**, formDirectives]

In my case doesn't work, give me an error: I need to import
 **import 'package:angular/core.dart';**

Without this import (like first import for angular_form), app doesn't work. I use Webstorm to write dart app and don't suggest me anything to correct problem

**Comment by chalin** [comment]
Thanks for the issue. Can you share the full code that gives you that error? At that point in the tutorial, your `app_component.dart` file should already contain `import 'package:angular/angular.dart'` (from part 1 in the tutorial).

**Comment by psummo** [comment]
Sorry, I was wrong... I had miss that import, so I need to import all singular angular component. Sorry for this issue

**Comment by chalin** [comment]
No worries, I'm glad that it was only that.
