### ISSUE TITLE
'About AngularDart Components' page issue

### ISSUE THREAD

**Issue by dynaxis** [dart-lang/site-webdev#1764]
From URL: https://webdev.dartlang.org/components/

Previously there was a note saying IE is currently not supported. I see which browsers are supported on the GitHub page for Angular Dart components. So please make it clear which browsers are supported in the doc. If possible, please clarify if IE (at least 11) will be ever supported in the future.

**Comment by kwalrath** [comment]
My understanding is that AngularDart Components will never support IE. We do support Edge.

I can add back the IE note if you think it's important.

**Comment by dynaxis** [comment]
Depending on the type of applications, IE support is important. And sometimes not. So I think it's necessary to make clear that IE won't be supported. Even the previous notice was read as if IE would or mght be supported in the future.

Abandoning IEs might be a good compromise for Dart. But to me, it's a little bit unfornate since my company is struggling to persuade one of our customers to drop support for IE 9.

Anyway, the bottomline is:

Please make clear that IEs aren't and won't be supported.

Thanks.

**Comment by kwalrath** [comment]
Thanks for explaining your thought process. I agree that an unambiguous note would be helpful, so I'll add back the old note, but clarify it.
