### ISSUE TITLE
Bad URL - Angular Dart 5.0 api reference page

### ISSUE THREAD

**Issue by Augustpi** [dart-lang/site-webdev#1773]
Angular api page gives 404 error for v5.0
URL: https://webdev.dartlang.org/api/angular/angular/NgClass-class
and https://webdev.dartlang.org/api

**Comment by chalin** [comment]
Thanks for the issue. It might have been a temporary glitch. It works for me:

> <img width="828" alt="screen shot 2018-08-09 at 07 39 07" src="https://user-images.githubusercontent.com/4140793/43896600-546b17ec-9ba7-11e8-9a57-881d717d3e9d.png">

**Comment by Augustpi** [comment]
Thanks @chalin, it works now
