### ISSUE TITLE
quickstart base href markup is very scary – required? Could we improve the note or remove?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-webdev#1795]
This is super scary for someone trying to bootstrap a simple app...

https://github.com/dart-lang/site-webdev/blob/805a81708d1a11bbf79e2efa172e4e40c7fd1baa/examples/ng/doc/quickstart/web/index.html#L5-L12

**Comment by chalin** [comment]
Yes! :) A full assessment is in the works. This is adup of #1725 (which explains the origin of this script).
