### ISSUE TITLE
[master] examples/ng/doc/quickstart NoSuchMethodError on Edge when using DDC

### ISSUE THREAD

**Issue by NecroSean38** [dart-lang/site-webdev#1798]
I tried the quickstart of angular-dart, and got an error on Edge (similar things happened on IE):

> SCRIPT5022: NoSuchMethodError: method not found: 'Unexpected Null Value>' Receiver: null Arguments: []

This error only appears when using DDC, and I am not sure whether it is a bug about DDC or this example.

**Comment by kwalrath** [comment]
My understanding is that DDC is not guaranteed to work with any browser except Chrome, but @vsmenon might be able to tell us more.

**Comment by kwalrath** [comment]
@NecroSean38 can you give us links to where you looked (pages, source code, ...), so we can make it more obvious that people should use Chrome during development?

**Comment by NecroSean38** [comment]
@kwalrath I just clone the code in [https://github.com/angular-examples/quickstart](url), and run it by using `pub global run webdev serve` at local. Here is what I saw in Edge (version: 42.17134.10)

![ddc](https://user-images.githubusercontent.com/16998796/44525851-dafd0680-a714-11e8-9418-27f26f32130d.png)

Things worked well when I changed the builder from DDC to Dart2JS.

**Comment by chalin** [comment]
Quickstart works fine under Chrome. This is likely a ddc issue. I'll move this to the SDK repo.

**Comment by chalin** [comment]
This issue was moved to dart-lang/sdk#34243

**Comment by kwalrath** [comment]
We might need to make clearer in the quickstart instructions/code (if we don't already) that they should use only Chrome with webdev serve.

**Comment by kwalrath** [comment]
I'm going to clarify the instructions in https://webdev.dartlang.org/angular/guide/setup#run-the-app and anywhere else on this site that mentions webdev serve.
