### ISSUE TITLE
'Dart SDK' page issue

### ISSUE THREAD

**Issue by oneyb** [dart-lang/site-webdev#1812]
From URL: https://webdev.dartlang.org/tools/sdk/

It would be good to include complete installation information. This means adding the sdk directory to the PATH. #19926 

You know after installing the binaries:

```bash
echo 'export PATH="/usr/lib/dart/bin:$PATH"' >> $HOME/.profile
```

**Comment by kwalrath** [comment]
I think we used to do this. I don't know why we stopped, but it does seem like a good thing to do.

**Comment by kwalrath** [comment]
This issue was moved to dart-lang/site-shared#37
