### ISSUE TITLE
'Build_runner' page is out of date

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/site-webdev#1825]
From URL: https://webdev.dartlang.org/tools/build_runner

At a minimum we should remove the section about [build_config_files](https://webdev.dartlang.org/tools/build_runner#build-config-files), these should almost never be used any more.

We now have "release" mode as a real supported thing, and you can configure builders differently based on that mode with `release_options` and `debug_options`, which override `options` for their respective modes.

**Comment by kwalrath** [comment]
OK, thanks for the report. Unfortunately, our website isn't updating right now due to a broken build (dart-lang/dartdoc#1743), but I aim to fix the build_runner page soon.

**Comment by jakemac53** [comment]
> OK, thanks for the report. Unfortunately, our website isn't updating right now due to a broken build ([dart-lang/dartdoc#1743](https://github.com/dart-lang/dartdoc/issues/1743)), but I aim to fix the build_runner page soon.

If you wan't to collaborate somehow on this let me know :)
