### ISSUE TITLE
Problem in chapter 5, Splitting App Component

### ISSUE THREAD

**Issue by nathanandtech** [dart-lang/site-webdev#1826]
Steps to replicate the problem: 
Download toh-4-master, the template from the end of the last chapter.
Follow the guide from the top,
After following the 'create app component', the guide states that reload the page and the app should work, however I get the error included below. 

'''
SEVERE] build_web_compilers|entrypoint on test/app_test.dart (cached):
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'src/hero_list_component.template.dart' as _ref1;` from angular_tour_of_heroes|lib/app_component.template.dart at 13:1

[SEVERE] build_web_compilers|entrypoint on web/main.dart (cached):
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'src/hero_list_component.template.dart' as _ref1;` from angular_tour_of_heroes|lib/app_component.template.dart at 13:1

[SEVERE] build_web_compilers|entrypoint on test/app_test.dart.browser_test.dart (cached):
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'src/hero_list_component.template.dart' as _ref1;` from angular_tour_of_heroes|lib/app_component.template.dart at 13:1

[SEVERE] Failed after 943ms
Serving `web` on http://localhost:8080
Serving `test` on http://localhost:8081
'''

**Comment by kwalrath** [comment]
If you go down to https://webdev.dartlang.org/angular/tutorial/toh-pt4#the-road-youve-travelled and click view source, you can download the code you should have at this point. Does that code compile for you? If so, can you figure out what the important differences are between your code and that code?

Please let us know what happens, so we can (at the very least) improve our instructions. Thanks!

**Comment by nathlx** [comment]
Hi,
As stated, I tried using the toh-pt4 files after my own version failed, and get the above result.
Perhaps due to the Dart2.0 change?

Thanks,

**Comment by chalin** [comment]
Hi @nathlx, thanks for the issue. I followed the steps that you describe, and the app and tests run fine under Dart 2.0.0. Since this isn't a problem with the tutorial, I'm going to close this issue and suggest that you post a question to Stackoverflow. Once you've done that, share the link to your question here so that I can followup.
