### ISSUE TITLE
Turquoise on white links are hard to read on some monitors

### ISSUE THREAD

**Issue by nshahan** [dart-lang/site-webdev#183]
This is the first time I looked at the site on my desktop monitor and I find the links hard to read against the white background. The color is too bright for a screen with poor contrast.

![screen shot 2016-12-02 at 10 46 37 am](https://cloud.githubusercontent.com/assets/2498387/20846203/69fcdf6e-b87d-11e6-8a75-8ad50fc64808.png)

They are perfectly readable on my laptop.

**Comment by kwalrath** [comment]
We'd like the main site color (the homepage header, e.g.) to stay turquoise, but most linked text could use whatever color we use on www.dartlang.org. Code font also needs to be legible and distinguishable from links. We should at least pass the AA tests on http://webaim.org/resources/contrastchecker/.

@ericjim could you help with this?

**Comment by chalin** [comment]
Fixed - see Kathy's comment in https://github.com/dart-lang/site-webdev/pull/194#issuecomment-265038721
