### ISSUE TITLE
[master] examples/ng/doc/toh-5 wrong place for provider ?

### ISSUE THREAD

**Issue by manuscle** [dart-lang/site-webdev#1848]
For good practices, 
`providers: [ClassProvider(HeroService)],`
should stay in dashboard_component.dart, not in app_component.dart isn't it?
https://github.com/angular-examples/toh-5/blob/ae42b9e9c8338f43368d61ec7823b9553f41fad9/lib/app_component.dart#L21

**Comment by kwalrath** [comment]
@chalin what do you think?

**Comment by chalin** [comment]
Thanks for your issue.

> For good practices, ... not in app_component.dart

No, the hero service is used in both the dashboard and the hero-list component, so it needs to be in the app component's providers list.

Here is a relevant excerpt from the tutorial's section on [Create AppComponent](https://webdev.dartlang.org/angular/tutorial/toh-pt5#create-appcomponent):

> Perform these steps:
> - ...
> - Add `HeroService` to the  `providers` list of `AppComponent` because you'll need it in every other view.

I'll close this issue for now. If you have further doubts you can reopen and/or add further comments.

**Comment by manuscle** [comment]
Ok I understand now. Thanks for reply!
