### ISSUE TITLE
'Template Syntax' page issue: =>Seems the page requires some date setting

### ISSUE THREAD

**Issue by pet-ro** [dart-lang/site-webdev#1853]
From URL: https://webdev.dartlang.org/angular/guide/template-syntax

**In a Google search this page gets the publishing date  25.02.1970**

See attached file:

![angulardart-template-syntax--year-of-publishing-1970](https://user-images.githubusercontent.com/492177/49170112-b92aa580-f33b-11e8-99a2-1d7cfaf28282.PNG)

=> **Seems the page requires some date setting.**

**Comment by kwalrath** [comment]
Interesting! It looks like that's a side effect of the pipe operator example, which uses a birthday of Feb 25, 1970. (If you look on the page or in its source for "1970", you'll find two occurrences.)

This seems like a search engine bug to me, so I'll try reporting it.

Is there anything else we should do?

**Comment by chalin** [comment]
FYI, the sitemap has an appropriate timestamp:

```xml
<url>
  <loc>
    https://webdev.dartlang.org/angular/guide/template-syntax
  </loc>
  <lastmod>2018-11-27T17:53:22-08:00</lastmod>
  ...
</url>
```

**Comment by kwalrath** [comment]
OK, I've reported the issue using the Feedback link at the bottom of the page. I'll keep this open, for now, to remind us to check back.

**Comment by kwalrath** [comment]
Another report of this on Twitter: https://twitter.com/westoque/status/1082087657025536000. And I can't find any internal record of this bug. I'll follow up on this...

**Comment by kwalrath** [comment]
I suppose we could put a "last updated" date the bottom of every page. Is that really the best practice?

**Comment by kwalrath** [comment]
Putting the "Last updated" date at the end of the article hasn't fixed the problem. I'll try moving it up to the top.

**Comment by kwalrath** [comment]
#1894 worked!

![image](https://user-images.githubusercontent.com/2164483/51143808-477fbb80-1804-11e9-9f63-57f5b94a70f6.png)
