### ISSUE TITLE
Feedback on page: Child & Relative Routes (DRAFT)

### ISSUE THREAD

**Issue by markrchristine** [dart-lang/site-webdev#1856]
URL: https://webdev.dartlang.org/angular/guide/router/4
In this example, the parent component called CrisisListComponent  is reloading when we navigate to the child component called CrisisComponent. That seems to be the wrong behavior. Am i missing something?

**Comment by markrchristine** [comment]
As I look into it further, this issue also causes the CrisisService to reload. That's also not expected. I tested this by putting a print statement in the CrisisListComponent constructor and the CrisisService constructor. Everytime I navigated to a different crisis both of the print statements ran.

**Comment by kwalrath** [comment]
@chalin can you comment?

**Comment by markrchristine** [comment]
I've found a solution to this issue. I've implemented the CanReuse interface on the CrisisListComponent and returned true to reuse it. I think it would be beneficial to know about this interface in the tutorials.

**Comment by chalin** [comment]
(As you've probably discovered, CanReuse is describe here: https://webdev.dartlang.org/angular/guide/router/5#canreuse-interface.)
