### ISSUE TITLE
unable to build toh* examples

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1884]
_From @starbugs2008 on December 27, 2018 2:36_

Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:
name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0

* [ ] Dart SDK Version (`dart --version`)
* [ x] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
* [ x] Whether you are using Windows (if applicable)
* [ ] Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
* [ ] Any other packages or constraints we should know about

Missing some or all of the above might make the issue take longer or be impossible to act on.

----

INFO] Checking for unexpected pre-existing outputs. completed, took 2ms
[SEVERE] angular on package:angular/src/core/di.dart:

FileSystemException: Creation failed, path = 'c:\dev\dart\toh-4\.dart_tool/build/generated/angular/lib/src' (OS Error: The system cannot find the path specified.
, errno = 3)
[SEVERE] angular on package:angular/src/core/application_tokens.dart:

FileSystemException: Creation failed, path = 'c:\dev\dart\toh-4\.dart_tool/build/generated/angular/lib/src' (OS Error: The system cannot find the path specified.
, errno = 3)
[SEVERE] angular on package:angular/src/platform/dom/events/dom_events.dart:

FileSystemException: Creation failed, path = 'c:\dev\dart\toh-4\.dart_tool/build/generated/angular/lib/src/platform' (OS Error: The system cannot find the path specified.
, errno = 3)
[SEVERE] angular on package:angular/src/core/linker/app_view_utils.dart:

FileSystemException: Creation failed, path = 'c:\dev\dart\toh-4\.dart_tool/build/generated/angular/lib/src/core/linker' (OS Error: The system cannot find the path specified.
, errno = 3)
[SEVERE] angular on package:angular/src/bootstrap/modules.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AssetNotFoundException: angular_tour_of_heroes|.dart_tool/build/generated/angular/lib/src/core/di.ng_placeholder
[SEVERE] angular on package:angular/src/bootstrap/modules.dart:
Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
AssetNotFoundException: angular_tour_of_heroes|.dart_tool/build/generated/angular/lib/src/core/application_tokens.ng_placeholder
[WARNING] No actions completed for 15.1s, waiting on:
  - pageloader on test/app_test.dart

[WARNING] No actions completed for 15.1s, waiting on:
  - pageloader on test/app_test.dart

[WARNING] No actions completed for 15.1s, waiting on:
  - pageloader on test/app_test.dart

[WARNING] No actions completed for 15.0s, waiting on:
  - pageloader on test/app_test.dart

[WARNING] No actions completed for 15.1s, waiting on:
  - pageloader on test/app_test.dart

[WARNING] No actions completed for 15.1s, waiting on:
  - pageloader on test/app_test.dart

[WARNING] No actions completed for 15.1s, waiting on:
  - pageloader on test/app_test.dart

-----

_Copied from original issue: dart-lang/angular#1698_

**Comment by chalin** [comment]
Hi, thanks for filing an issue. The toh examples live in this repo, which is why the issue was moved. 
- Which version of the Dart SDK are you using?
- Are you you using the latest toh app sources (the sources changed a week or so ago, if your sources are any older, you'll need to get the updated sources).
- Which toh apps are failing. Do you get failures as early as [toh-0](https://webdev.dartlang.org/angular/tutorial/toh-pt0)?

**Comment by starbugs2008** [comment]
sdk version is 2.1.0
I download source 12/26/2018
I tried both toh-0 and toh4, have the same issue

**Comment by chalin** [comment]
Under Dart 2.1, I did the following and didn't run into any problems:

- Download the [toh-0](https://github.com/angular-examples/toh-0) zip, and unzipped, `cd` into the project folder. Then, run the following commands ...
- `pub get`
- `pub global activate webdev` # to ensure I have the latest webdev
- `webdev serve`
- Visited http://localhost:8080 and the app renders "Hello Angular"

Can you try the same steps and let me know what happens? (Btw, which OS are you under?)

**Comment by starbugs2008** [comment]
I followed your instruction and  the error is gone, but  web page stuck at Loading.... stage.

**Comment by chalin** [comment]
> I followed your instruction and the error is gone, ...

Good, then that's progress.

> but web page stuck at Loading.... stage.

Which OS and browser are you using?

**Comment by starbugs2008** [comment]
window10 and chrome

**Comment by chalin** [comment]
So, to be clear: the apps run fine when viewed in Chrome, but not when viewed from Edge? If so, which version of Edge are you using? Also, can you open the equivalent of the JavaScript console in Edge? Are there any error messages?

**Comment by chalin** [comment]
Examples are building, and successfully passing tests just fine now.
