### ISSUE TITLE
/angular looks bad on narrow screens

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#190]
When you go to https://webdev.dartlang.org/angular (or any other 2+-line titled page under /angular), the Angular icon overlaps with the header text when the screen size is very narrow. This is noticeable on a phone in portrait mode.

![image](https://cloud.githubusercontent.com/assets/2164483/20851657/983c7dda-b896-11e6-9da2-2d06396d0a92.png)

The image is smaller (and the appearance is fine) on pages like https://webdev.dartlang.org/angular/guide/user-input that have shorter titles.

cc @kasperl, @ericjim, @chalin

**Comment by kwalrath** [comment]
As the following screenshot shows, one-line titles (such as in [Component Styles](https://webdev.dartlang.org/angular/guide/component-styles)) can have this problem, too. Also, the prev/next links have too much vertical space between the lines.

![image](https://cloud.githubusercontent.com/assets/2164483/20852030/8932defe-b898-11e6-8f6c-2a9a3fec3d03.png)

**Comment by kwalrath** [comment]
But the [Attribute Directives](https://webdev.dartlang.org/angular/guide/attribute-directives) page looks fine. Maybe the problem has to do with the prev/next links being >1 line?

![image](https://cloud.githubusercontent.com/assets/2164483/20852110/e16edb68-b898-11e6-8a09-b3d3ddb6922a.png)

**Comment by kwalrath** [comment]
@ericjim might you be able to take a look at this?

**Comment by chalin** [comment]
@kwalrath - FYI, I've solved most of the issues related to this. I'll submit a PR tomorrow.

**Comment by kwalrath** [comment]
The fix is published. You might need to shift-reload or view in incognito mode to see the new version.

**Comment by kasperl** [comment]
Looks good!
