### ISSUE TITLE
Better title for Angular landing page "Documentation Overview"

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-webdev#193]
Could be "AngularDart overview or some such?"

**Comment by kwalrath** [comment]
Once we've separated from angular/angular.io, then I can improve the doc experience.

cc @chalin

**Comment by kwalrath** [comment]
I think we need an angular/index.html page. Too many people are linking directly to angular/guide.

**Comment by kevmoo** [comment]
+1

**Comment by chalin** [comment]
What would you like on this landing page?

**Comment by kwalrath** [comment]
I think a general intro to AngularDart. Kind of like https://angular.io/, but less flashy (befitting its subsite status) and perhaps with more content (perhaps some of what's on https://angular.io/features.html).

@kevmoo, what do you think?

**Comment by kevmoo** [comment]
SGMT

**Comment by kwalrath** [comment]
SGMT = Sounds Good, Me Too? :)

**Comment by kevmoo** [comment]
http://www.urbandictionary.com/define.php?term=SGTM 😄

**Comment by kwalrath** [comment]
Closed by #280.
