### ISSUE TITLE
webdev redirect is missing

### ISSUE THREAD

**Issue by isoos** [dart-lang/site-webdev#1932]
Reported on gitter:
"This results in 404 error instead of redirecting
https://webdev.dartlang.org/api/angular/angular/NgClass-class
"

https://gitter.im/dart-lang/TALK-general?at=5ced1a446366992a9436a4fe

**Comment by kwalrath** [comment]
@legalcodes do you have any ideas on the best way to fix this?

/cc @mit-mit

**Comment by kwalrath** [comment]
One thing we should consider doing is to have a single page that tells them to search dart.dev & angulardart.dev. That way, if the redirect is missing/wrong, at least they'll have some clue as to where to go next.

**Comment by mit-mit** [comment]
Initial fix in https://github.com/dart-lang/site-webdev/pull/1933. To fix wording, etc. just send a PR for the `404.html` file.

**Comment by kwalrath** [comment]
Although the initial fix is something, I think we still need to fix the API doc redirects.

**Comment by legalcodes** [comment]
Sure, I can add a glob to the firebase.json in webdev.dartlang.org for these. Thanks for catching this.

**Comment by mit-mit** [comment]
@kwalrath I think this is fixed as of https://github.com/dart-lang/site-webdev/pull/1936 ?

**Comment by kwalrath** [comment]
Yep, it’s working now.
