### ISSUE TITLE
[master] examples/ng/doc/quickstart

### ISSUE THREAD

**Issue by dewsy** [dart-lang/site-webdev#1940]
This repo as it stays stucks on "Loading..." if opened on Edge (using webdev serve)

**Comment by kwalrath** [comment]
@dewsy I think webdev serve (which uses dartdevc) is only guaranteed to work on Chrome right now, but they intend to improve support for other browsers. The docs could probably be clearer about this.

If you're able, could you please do the following:
1. Look at what the console says.
2. Look at the [known dartdevc bugs](https://github.com/dart-lang/sdk/issues?q=is%3Aissue+label%3Aweb-dev-compiler+is%3Aopen). If no bug exists, open a new one at https://github.com/dart-lang/sdk/issues.
4. In the new or existing sdk bug, add the console message, steps to reproduce, and a reference to this bug (`dart-lang/site-webdev#1940`).

Related: https://dart.dev/tools/dartdevc/faq#what-browsers-does-dartdevc-work-with

**Comment by dewsy** [comment]
Hy @kwalrath, thank you for the answer!

Yes, i found the dartdevc, and the fact that it's only for Chrome. However, the repo runs on Firefox as well as Chrome. Also, i found a list of sites that uses AngularDart, and most of them had no issue running on Edge.

As i was reading up the docs, it seemed to me that if i would build the project, nut just serve, it would go through the same pipeline, so i wonder, what the running sites know and i don't.

Console on Edge only says:
"0:  client.js (12699,6)"

The Issue finder tab (sorry, my browser isn't in English, i don't know the exact name) shows that execution stopped in main.dart at line:
"  main.main = function main$() {
    src__bootstrap__run.runApp(app_component$0.AppComponent, app_component$46template.AppComponentNgFactory);
  };"


I ran thru the open issues, did not find anything that closely resembles what i'm experiencing.

**Comment by kwalrath** [comment]
webdev build uses dart2js by default, not dartdevc. dart2js is older and works on a wider selection of browsers, so I suspect you wouldn't have this problem in a real build.

Did you try running webdev serve with the `--release` flag? It would be much slower to reflect code changes (which is why it isn't the default development compiler), but I bet it'll work.

There's more info here: https://dart.dev/tools/webdev#serve

Whatever the result, could you please file a bug on dart-lang/sdk? That's the best way to make sure this issue gets fixed. Thanks!

**Comment by dewsy** [comment]
@kwalrath 
Thank you again for the answer! The --release tag magically solved my issue, it was a great suggestion from you!

However, i'll open the issue in the repo you mentioned, just so the guys can have a chance to iron things out a bit :)

Thank you again for the suggestion!
