### ISSUE TITLE
[ng] Document how to test web apps

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#195]
This is a big topic, but we need to tackle it (both unit tests & end-to-end testing).
- ~general testing page~
- [x] component testing:
  - [x] write tests for tutorial apps - #553
  - [x] write component testing page - #621
- E2E has been moved to #895

**Comment by matanlurey** [comment]
I'd like to help here. Still working on getting `package:angular_testing` out.

**Comment by chalin** [comment]
@matanlurey - rough ETA on getting that package out?

**Comment by matanlurey** [comment]
EOY.

**Comment by chalin** [comment]
Cf. https://github.com/dart-lang/angular2_components/issues/62

**Comment by chalin** [comment]
Updating priority based on feedback from @kwalrath

**Comment by kulshekhar** [comment]
I'm starting a new project and will be using Angular. I tend to document stuff internally and would be happy to contribute if there happens to be an overlap between what I'll do and what is needed here. If this is of interest, an itemized list of parts that need documentation would be useful.

**Comment by kwalrath** [comment]
@kulshekhar thanks for the offer! @chalin can you think of anything at this point?

**Comment by chalin** [comment]
Hi @kulshekhar: I've started working on the creation of the testing docs. I don't have a list now, and we're juggling with quite a few changes at the same time, but I expect to have something to share next week or the week after.

**Comment by chalin** [comment]
Kathy, I created #895 for E2E tests, and I don't think that we'll be writing about testing in general, so the items in the original checklist for this issue are covered. Consider closing.
