### ISSUE TITLE
Bad sharing text/image

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#2]
See also https://github.com/dart-lang/site-www/issues/3 & https://github.com/dart-lang/site-www/issues/2.

Here's what happens when you try to share webdev.dartlang.org/guides/web-programming﻿ on G+:

![image](https://cloud.githubusercontent.com/assets/2164483/16821294/4175950a-490a-11e6-902e-6aaeeef949d0.png)

Instead, you should see the "description" text specified in the YAML:

```description: "What libraries are available for writing web apps in Dart?"```

**Comment by filiph** [comment]
Fixed
