### ISSUE TITLE
in Angular tutorial a snippet shouldn't mention css file

### ISSUE THREAD

**Issue by a14n** [dart-lang/site-webdev#203]
At the step [Dashboard Top Heroes](https://webdev.dartlang.org/angular/tutorial/toh-pt5#!#dashboard-top-heroes) the first snippet is :

```dart
@Component(
    selector: 'my-dashboard',
    templateUrl: 'dashboard_component.html',
    styleUrls: const ['dashboard_component.css'],
    directives: const [ROUTER_DIRECTIVES],
    )
```

The `styleUrls` attribute shouldn't be there. It leads to errors running the app until the `dashboard_component.css` file is defined at the step [Styling the app](https://webdev.dartlang.org/angular/tutorial/toh-pt5#!#styling-the-app).

/cc @chalin @kwalrath

**Comment by kwalrath** [comment]
Thanks for the report, @a14n.

**Comment by chalin** [comment]
Good catch, thanks. Yes, that was a TS-side change that hadn't been ported yet. A fix is on the way.
