### ISSUE TITLE
[ng] improve authoring experience

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#208]
Under the current authoring scheme, it takes approximately 1 min for a change to render (regardless of the size of the change). It would be more efficient to have a scheme similar to use of the Jade server feature used under ng.io.

**Comment by kwalrath** [comment]
I'd love this, but since it only affects a few people, I wouldn't spend too much time on it unless (1) it'll save you more time than implementing it would take or (2) the delay makes your work on site-webdev infeasible/horrible.

**Comment by chalin** [comment]
Right, my plan was to do a quick test of a few alternatives and otherwise sticking to the current scheme for now.

**Comment by chalin** [comment]
Converting all of our docs to markdown and upgrading to the latest Jekyll seem to have addressed this issue. An incremental rebuild of the site after changing a single page takes a few seconds now.
