### ISSUE TITLE
[ng] fix code in hero tutorial - routing part

### ISSUE THREAD

**Issue by Janamou** [dart-lang/site-webdev#211]
Hi!

I have found a little bug in the code of the Heroes tutorial. It's in the [HeroesComponent rename code](https://webdev.dartlang.org/angular/tutorial/toh-pt5#!#splitting-the-appcomponent) - there is some weird constructor :-)

```dart
@Component(
    selector: 'my-heroes',
)
class HeroesComponent implements OnInit {
  HeroesComponent(this._heroService,
                  );
}
```

**Comment by chalin** [comment]
Hi Jana: that is actually legal syntax now (that is, having an extra trailing comma in an argument/parameter list). The layout is a bit funny because we're only showing annotation and constructor arguments that are relevant up to that point.
