### ISSUE TITLE
Displayed text overruns display area in Pirate Convention Code Lab

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#22]
July 2017 update: This issue is visible at both https://webdev.dartlang.org/codelabs/darrrt and https://webdev.dartlang.org/codelabs/ng2.

_From @nicolasgarnier on August 26, 2014 15:20_

_From [daniel.s...@gmail.com](https://code.google.com/u/117036693528125723667/) on January 22, 2014 11:24:23_

What steps will reproduce the problem? 1.Enter the allowed 15 characters for a name in the Pirate Convention Code Lab example. 2. 3. What is the expected output? What do you see instead? Expect the name and the appellation will both be displayed on the name tag. Instead, the text overruns the display area and only part of the appellation is displayed. Either the maxlength in the HTML file should be less than 15 characters or there should be code to resize the text to fit the display area. What version of the product are you using? On what operating system? Current version of the Pirate Convention Code Lab at https://www.dartlang.org/codelabs/darrrt/ using version 1.1.1 of the Dart Editor on Mac OS. Please provide any additional information below.

**Attachment:** [Screen Shot 2014-01-21 at 4.38.36 PM.png](http://code.google.com/p/dart/issues/detail?id=16247)

_Original issue: http://code.google.com/p/dart/issues/detail?id=16247_

_Copied from original issue: dart-lang/www.dartlang.org#816_

**Comment by kwalrath** [comment]
_From @nicolasgarnier on August 26, 2014 15:20_

_From [lrn@google.com](https://code.google.com/u/lrn@google.com/) on January 22, 2014 08:49:07_

**Status:** Triaged  
  **Labels:** Area-Samples

**Comment by kwalrath** [comment]
_From @nicolasgarnier on August 26, 2014 15:20_

_From [sethladd@google.com](https://code.google.com/u/sethladd@google.com/) on March 07, 2014 08:18:57_

**Cc:** mcampi...@google.com  
  **Labels:** -Area-Samples Area-Documentation Docs-CodeLab

**Comment by kwalrath** [comment]
_From @nicolasgarnier on August 26, 2014 15:20_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on March 07, 2014 09:44:46_

**Cc:** shailent...@google.com

**Comment by kwalrath** [comment]
_From @nicolasgarnier on August 26, 2014 15:20_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on June 04, 2014 14:53:22_

**Labels:** -Area-Documentation Area-Site

**Comment by chalin** [comment]
The Pirate codelabs have been deprecated.
