### ISSUE TITLE
[ng] Search broken in Angular API Reference

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/site-webdev#220]
The search bar in the top right on API pages doesn't work. It just displays 'Loading Search' and can't be interacted with. I checked the console and there appears to be the same error on every page.

<img width="1440" alt="screen shot 2016-12-12 at 10 55 33 am" src="https://cloud.githubusercontent.com/assets/1916163/21112159/8a664658-c059-11e6-8fe5-d618e73f2546.png">

**Comment by kwalrath** [comment]
Thanks very much for the report, @leonsenft. We'll try to fix this ASAP.

Until this is fixed, the best API search options are the **Filter** field in https://webdev.dartlang.org/angular/api and the **Search** field that's at the upper right of all webdev pages _except_ the pages under /angular/api/.
