### ISSUE TITLE
[ng] eliminate build script dependency on repo alias angular-dart -> angular2

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#226]
Some build scripts copied from ng.io assumed that the name of the Angular Dart repo was `angular-dart`. Currently, the script that fetches the `angular2` repo also creates the `angular-dart` alias. Eventually, we should just drop the alias from all scripts.

**Comment by chalin** [comment]
@kwalrath - what will the pub package `angular2` name be replaced with once v3 comes out? Might it happen to be `angular_dart`?

**Comment by kwalrath** [comment]
I'll check tomorrow, but I doubt it'd be angular_dart, since it's already under dart-lang.

**Comment by chalin** [comment]
I had started working on this but I think that I'll just wait for the renaming of `angular2` to happen, and clean it all up at the same time.

**Comment by kwalrath** [comment]
Makes sense.
