### ISSUE TITLE
move source code for /angular examples

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#240]
It's currently under /public/docs/_examples (e.g. [/public/docs/_examples/architecture](https://github.com/dart-lang/site-webdev/tree/master/public/docs/_examples/architecture) and [/public/docs/_examples/attribute-directives](https://github.com/dart-lang/site-webdev/tree/master/public/docs/_examples/attribute-directives)).

I expected it to (1) have `angular` in the path and (2) be under `/src/(something)`. Maybe just `/src/angular/architecture`, `/src/angular/attribute-directives`, .... In site-www, similar code (used for testing but NOT auto-included) is under `/src/tests/site`.

**Comment by chalin** [comment]
The example code isn't included as part of the site so I'd keep it out of `/src`. How about `/examples/angular`?

**Comment by chalin** [comment]
I assume that relocating the example sources to a folder like `/examples/angular` under _this_ repo can wait given that the sources might actually be moving to _another_ repo?

**Comment by chalin** [comment]
Fixed by #468
