### ISSUE TITLE
[ng] migrate issues from ng.io

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#242]
@kwalrath - I’ve seen Dart issues migrated in bulk before. Is this something we can do for migrating issues from ng.io to site-webdev? I.e., are you aware of the tools that have been used in the past?

**Comment by kwalrath** [comment]
I've done it using https://github.com/google/github-issue-mover. It should work for this, too.

**Comment by chalin** [comment]
Done with the migration of issues.
