### ISSUE TITLE
html_proof reports incorrect link on error

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#245]
See [this Travis log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/184012225/log.txt) as an example. Here is a relevant excerpt:
```
/home/travis/tmp/___angular___guide___dependency-injection_____20161214-5477-cn0789.html
  *  External link https://www.dartlang.org/docs/dart-up-and-running/ch02.html#cascade failed: http://shop.oreilly.com/product/0636920025719.do exists, but the hash 'cascade' does not
```

Note that the error is reported over `dartlang.org` and yet the error detail makes reference to `shop.oreilly.com`.

**Comment by filiph** [comment]
Yes, the original Ruby-based html_proof is broken beyond repair. It's designed to work on the filesystem, so no redirects work.

How about we use linkcheck instead? It's less work to add ignores there. The big caveat is that linkcheck either needs Dart installed or it needs to be built as a standalone 'binary'. I can work on this (actually, I already started).

**Comment by kwalrath** [comment]
Related: https://github.com/dart-lang/site-www/pull/202

**Comment by chalin** [comment]
@filiph - I all for using `linkcheck` instead. Under Travis, we have Dart installed, so I won't need a standalone version for that.

**Comment by filiph** [comment]
@chalin Great, I didn't know we have dart installed.

Can we just add

    pub global activate linkcheck
    linkcheck :4000 -i deploy/urls/old_site_urls.txt

and check for errors only (exit code == 2)? Or do we need to introduce the 'ignore' feature?

**Comment by chalin** [comment]
Yes I can add something along those lines.
And yes, it would be nice to soon have addressed the [currently open linkcheck issues](https://github.com/filiph/linkcheck/issues).

I'll close the `html_proof` related issues and create a new one for replacing its use with `linkcheck`.

**Comment by chalin** [comment]
Superseded by #247.
