### ISSUE TITLE
[ng] switch to HashLocationStrategy as routing strategy for doc samples

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#252]
_From @challe on July 18, 2016 21:16_

Pub serve doesn't support `PathLocationStragety`, which is the angular2 default routing strategy, and because of that, reloading a routed page gets you a 404. I think this should be documented somewhere.

I encountered this a when staring out with angular2, Here is a stackoverflow question with an accepted answer that also mentions a pub package that could solve this: http://stackoverflow.com/questions/36780516/routing-doesnt-work-for-me-when-doing-a-hard-refresh.

_Copied from original issue: angular/angular.io#1919_

Edits (by @chalin):

Update:
- [ ] toh-5 & toh-6
- [ ] router example and prose

**Comment by chalin** [comment]
_From @kwalrath on July 18, 2016 21:20_

@chalin: My first thought is that we might want to cover this in the guide somewhere, and then refer to that coverage in the API reference docs. What do you think?

**Comment by chalin** [comment]
As a means of addressing this issue, a [PR enhancing `pub serve`](https://github.com/dart-lang/pub/pull/1437) has been submitted.

**Comment by chalin** [comment]
Btw, @kwalrath, I'm unsure why this was tagged with `api`. Maybe drop the `api` label and remove `[API]` from the title since this issue applies to a few chapters in the docs, though not to API docs themselves.

**Comment by chalin** [comment]
_From @kwalrath on August 8, 2016 22:29_

Talking with an engineer today, he suggested that `#` mode should perhaps be the default for Dart.

**Comment by tanelainla** [comment]
Any update on that? I still cannot find any hint about this behaviour in latest angular dart documentation? Is there any clear guide how to solve this in development environment?

**Comment by chalin** [comment]
Actually, we'll soon be serving examples from https://webdev.dartlang.org/ through firebase (#578). Firebase nicely supports rewrites and works just as well locally.

**Comment by chalin** [comment]
Update: after some discussion we've decided to go along with the original intent of this issue: i.e., use `HashLocationStrategy` in the doc samples. A deployment guide is being written (#660), and it will cover how to use `PathLocationStrategy` on a production server.

**Comment by chalin** [comment]
Work is underway for this: i.e., making hash location strategy the default in the tutorial. Will tackle the router example after.

Related issue: https://github.com/dart-lang/pub/issues/1374
