### ISSUE TITLE
Cheat Sheet: `HostBinding` example is incorrect

### ISSUE THREAD

**Issue by mehaase** [dart-lang/site-webdev#265]
The [cheat sheet](https://webdev.dartlang.org/angular/cheatsheet) shows the following syntax for `HostBinding`:

    @HostBinding('[class.valid]') isValid;

But actually the square brackets are not supposed to be there. It should be:

    @HostBinding('class.valid') isValid;

The API docs for `HostBinding` show the correct syntax, which is how I figured this out.

**Comment by kwalrath** [comment]
Thanks for the report, @mehaase! I've created an internal change list to fix this.
