### ISSUE TITLE
Bad URL: Trailing slash on codelabs and articles

### ISSUE THREAD

**Issue by challe** [dart-lang/site-webdev#27]
URL: https://webdev.dartlang.org/codelabs/
Expected page: https://webdev.dartlang.org/codelabs

URL: https://webdev.dartlang.org/articles/
Expected page: https://webdev.dartlang.org/articles

URL: https://webdev.dartlang.org/codelabs/darrrt/
Expected page: https://webdev.dartlang.org/codelabs/darrrt

Found via a Google search

**Comment by kwalrath** [comment]
These are all fixed now. (Thanks very much for the report, @challe!)
