### ISSUE TITLE
[ng] angular/api/angular2.compiler/NgContentAst/index.html issues

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#271]
The [angular2.compiler/NgContentAst class](https://webdev.dartlang.org/angular/api/angular2.compiler/NgContentAst-class) has a property named `index`.  The page generated for it is https://webdev.dartlang.org/angular/api/angular2.compiler/NgContentAst/index.html, but firebase rewrites this to just https://webdev.dartlang.org/angular/api/angular2.compiler/NgContentAst which invalidates the pages base href
```
<base href="../..">
```
As a result, page links, including to style files, are off by one level:
![screen shot 2016-12-20 at 5 45 36 pm](https://cloud.githubusercontent.com/assets/4140793/21374528/32527bb0-c6dc-11e6-9367-c5959b829b8d.png)

cc @kwalrath

**Comment by chalin** [comment]
@jcollins-g - I was just wondering if you were aware of this issue or had come across the problem it reports elsewhere -- namely, the consequences of the current dartdoc file naming scheme when there is a class property named `index`.

I address the issue here by adjusting the `<base href>` value, but it would be nice to have dartdoc handle it properly in the first place. Let me know if you think that the overhaul has addressed this, and if not, whether you would like for me to open an issue over dartdoc.

cc @kwalrath

**Comment by jcollins-g** [comment]
The canonicalization overhaul fixed which things named index we might write out, but not that we do it.  Why wouldn't this be a firebase bug?  Presumably it should know that if it rewrites a link this way that the base href might need adjusting?

In any event, happy to track this in dartdoc if it is causing trouble for you.
