### ISSUE TITLE
[ng] constrain minor version number of angular2 in pubspec of sample code

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#276]
Requested from https://github.com/dart-lang/angular2_api_examples/pull/4#discussion_r93547177. E.g.,
```
  angular2: '>=2.2.0 <2.3.0'
```

matching [web-angular/pubspec.yaml](https://github.com/google/stagehand/blob/master/templates/web-angular/pubspec.yaml).

@kwalrath - do you want me to make the change now or wait for 2.3.0 to come out?

**Comment by kwalrath** [comment]
@chalin let's make the change now.

**Comment by chalin** [comment]
As of 3.x, AngularDart will be respecting semver. So, I guess that we can put a hold on this?

**Comment by kwalrath** [comment]
Yep, we can close this.
