### ISSUE TITLE
"Low-Level HTML Pirate Code Lab" can't load piratenames.json ('Access-Control-Allow-Origin)

### ISSUE THREAD

**Issue by challe** [dart-lang/site-webdev#28]
What steps will reproduce the problem? 
Go to https://webdev.dartlang.org/codelabs/darrrt and open the Chrome DevTools. You can see that the piratenames.json can not be loaded because it tries to fetch it from dartlang.org. The input and button in the Pirate Badge iframe are also disabled, and I'm guessing it's because of this error.

XMLHttpRequest cannot load https://www.dartlang.org/codelabs/darrrt/files/piratenames.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://webdev.dartlang.org' is therefore not allowed access.
Error initializing pirate names: Instance of 'ProgressEvent'

**Comment by challe** [comment]
I initially tried looking at #22, but this is probably blocking a fix there.

**Comment by kwalrath** [comment]
At least part of the fix is in https://github.com/dart-lang/one-hour-codelab/commit/a6f676c5f0f4c23742a30c52218fbd80479f43db?

**Comment by Sfshaza** [comment]
I fixed this several days ago. I've left this open because Kathy is reviewing the repo for some changes.

**Comment by Sfshaza** [comment]
The repo is updated and the PR is merged. [PR 23](https://github.com/dart-lang/one-hour-codelab/pull/23)
