### ISSUE TITLE
Cheat sheet doesn't highlight code

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#281]
In the cheat sheets on angular.io, such as https://angular.io/docs/ts/latest/guide/cheatsheet.html, the important syntax is highlighted. The highlight is specified using `all code | highlighted code` syntax.

The highlight doesn't appear on webdev.dartlang.org. We should probably either highlight the specified code or remove the `| highlighted code` part of the cheat sheet code.

For example, the entry `@Input() myproperty;` (where `@Input` is bold) is specified like so in the [TS](https://github.com/angular/angular/blob/master/modules/@angular/docs/cheatsheet/directive-and-component-decorators.md) & [Dart](https://github.com/dart-lang/angular2/blob/master/doc/cheatsheet/directive-and-component-decorators.md) source files:

```
@cheatsheetItem
syntax:
`@Input() myProperty;`|`@Input()`
```

In https://angular.io/docs/ts/latest/guide/cheatsheet.html, @Input is bold.

![image](https://cloud.githubusercontent.com/assets/2164483/21534337/40f03290-cd1a-11e6-86a8-df4c996fcc4e.png)

In https://webdev.dartlang.org/angular/cheatsheet, it isn't:

![image](https://cloud.githubusercontent.com/assets/2164483/21534333/33a6cc48-cd1a-11e6-87ff-facf98f9a40b.png)

**Comment by chalin** [comment]
I can't see anything obvious that would explain the difference in behavior. I'll investigate further later.
