### ISSUE TITLE
[ng] user input guide - missing quotes

### ISSUE THREAD

**Issue by Janamou** [dart-lang/site-webdev#285]
Hi,

link: https://webdev.dartlang.org/angular/guide/user-input#!#put-it-all-together
Not a bug but for consistency - the click handler is missing quotes:

```dart
<button (click)=addHero(newHero.value)>Add</button>
```

thx :-)

**Comment by kwalrath** [comment]
Makes sense to me. Any reason we didn't do this, @chalin?

**Comment by chalin** [comment]
Thanks for the nice catch Jana.

@kwalrath - That was apparently just a carry over from the TS sample.
