### ISSUE TITLE
[ng] template syntax - component's name differ in text and example

### ISSUE THREAD

**Issue by Janamou** [dart-lang/site-webdev#286]
Hi,

in the two-way binding here: https://webdev.dartlang.org/angular/guide/template-syntax#!#two-way-binding
There is a component with the class name `MySizerComponent`, but in the text is written `SizerComponent` always. For example:

> Here's a SizerComponent that fits the pattern. It has a size value property and a companion sizeChange event

Thx :-)

**Comment by kwalrath** [comment]
@chalin it looks like the TS source code changed. Should we change ours to match?

**Comment by chalin** [comment]
Ah yes, I forgot to propagate the final round of changes I made to the TS example. A minor PR is forthcoming.
