### ISSUE TITLE
Increase the font weight of the p-tags

### ISSUE THREAD

**Issue by challe** [dart-lang/site-webdev#29]
The font-weight on the p-tags on https://webdev.dartlang.org/ are 300. I feel like the font is too narrow. Or like the contrast is too low. It's a bit hard to read. I tried mucking about in the DevTools and increasing the weight to 400 really makes a big difference. It's a lot easier for me to read after that change. This also makes it looks a lot more like dartlang,org.

Try comparing these two and maybe you'll see:
https://webdev.dartlang.org/
https://www.dartlang.org/

**Comment by kwalrath** [comment]
@challe, what OS are you using?

I agree that on a Mac, webdev looks too spindly. I've heard that on a PC, www looks too bold.

The 300 weight is defined in src/_assets/stylesheets/_overwrites.scss.

cc @Sfshaza

**Comment by challe** [comment]
@kwalrath I'm currently on Windows.
