### ISSUE TITLE
[ng] glossary - typescript is the preferred language

### ISSUE THREAD

**Issue by Janamou** [dart-lang/site-webdev#293]
Hi,

link: https://webdev.dartlang.org/angular/glossary#!#typescript

> ...
**TypeScript is the preferred language for Angular development although you can use other JavaScript dialects such as ES5.**

Sounds a little weird in the official AngularDart documentation + Dart is not mentioned...

**Comment by kwalrath** [comment]
Heh, can't believe we didn't catch that! Thanks for the report.

**Comment by kwalrath** [comment]
Ah, it wasn't supposed to show up in the Dart version, but a blank line hurt us.
