### ISSUE TITLE
404 when referencing https://angulardart.org/

### ISSUE THREAD

**Issue by JavaScriptDude** [dart-lang/site-webdev#299]
[Code Lab: AngularDart Components](https://webdev.dartlang.org/codelabs/angular2_components) refers to angulardart.org which returns a 404. I tested http://angulardart.org and it redirects to https://webdev.dartlang.org/angular.

Please fix this by either:

1. Get https working on angulardart.org.
2. Fix any references to Angular Dart information pages to https://webdev.dartlang.org/angular

If doing 2, please scrape all docs to fix same links.

**Comment by kwalrath** [comment]
Oops, I'll definitely fix this on our site.

I've also filed an internal bug about the https redirect issue. Thanks!
