### ISSUE TITLE
Polymer Dart link in the footer leads no where

### ISSUE THREAD

**Issue by robbecker-wf** [dart-lang/site-webdev#3]
Clicking on the Polymer Dart link in the footer simply brings you to the same page but at the top. Hovering it reveals that the link *seems* correct, but doesn't load correctly.

![image](https://cloud.githubusercontent.com/assets/6053699/16842813/0876a70c-499c-11e6-8764-b989f6ebfa89.png)

**Comment by Sfshaza** [comment]
Oops! Thanks for catching that. Fixed.
