### ISSUE TITLE
Make it easy and intuitive to download Dart SDK and Dartium

### ISSUE THREAD

**Issue by adaojunior** [dart-lang/site-webdev#30]
IMHO since the last version of dartlang.org it has been unintuitive to download the dart SDK and Dartium. This version did not make it easy, I spent some time looking for a download button on the home page.

A list of tools with an easy "Install" or "Download" link.
- [NodeJS](https://nodejs.org/en/)
- [Python](https://www.python.org/)
- [Ruby](https://www.ruby-lang.org/en/)
- [Sass](http://sass-lang.com/)

I also saw some folks in the dartlang slack complaining about it.

**Comment by adaojunior** [comment]
![dartlang](https://cloud.githubusercontent.com/assets/4921294/17272179/22bc829a-5666-11e6-8876-42613869c967.PNG)

I'll leave this suggestion but I'm pretty sure someone else will come with a better idea.

**Comment by filiph** [comment]
Thanks Adao. Your mock is close to what I have in mind. The problem is that we don't currently have a single download destination. There's https://www.dartlang.org/install, https://flutter.io/setup/#get-the-flutter-sdk, and https://dartino.org/getting-started/.

I hope to remake the 'Install' page into something that leads you on the right track no matter what you're trying to use. When that's ready, I'll put up the Download button.

**Comment by adaojunior** [comment]
:D But I think most people that land in the dartlang.org would be interested in learning about dart (language), downloading the dart SDK and do some coding. People that are most interested on flutter would search for flutter and go to the flutter webpage, same for dartino. What worries me is that a new user would have to consume a lot of information just to install dart. Maybe instead of adding a `Download` button we could add an `Install` link and have a very simple page offering the dart SDK, dartino and flutter as well. It should also make it clear that flutter and dartino are optional.

**Comment by adaojunior** [comment]
BTW, when flutter and dartino required the dart SDK to be installed right ?

**Comment by filiph** [comment]
>  Maybe instead of adding a Download button we could add an Install link and have a very simple page offering the dart SDK, dartino and flutter as well. 

Yes, that's actually exactly what I was hoping to do.

> BTW, when flutter and dartino required the dart SDK to be installed right ?

Yes, but my understanding is that they install it separately.

But thanks for prodding. I agree, this definitely needs to be fixed soon.

**Comment by filiph** [comment]
Ok, quick fix: https://github.com/dart-lang/site-www/commit/de908526de9190227fae646cc1358eb5f82b10be

Thanks Adao for the nudge! I'll work on making /install a lot more straightforward.

**Comment by chalin** [comment]
I believe that this issue should have been open over https://github.com/dart-lang/site-www. Anyhow, it seems to have been addressed. If not, please reopen over site-www.
