### ISSUE TITLE
Add ellipsis to code sample

### ISSUE THREAD

**Issue by JavaScriptDude** [dart-lang/site-webdev#300]
On page [Step 6: Read a JSON File](https://webdev.dartlang.org/codelabs/ng2/6-readjsonfile), in the code sample after the line "At startup, disable the button and input field", please add an ellipsis after the line `bool isInputEnabled = false;`

**Comment by kwalrath** [comment]
Thanks for the feedback!

**Comment by kwalrath** [comment]
If someone else going through this codelab could confirm that this is correct, I'd be happy to make the fix. (Or you could.)

**Comment by chalin** [comment]
I confirm, there should be ellipses there.

**Comment by chalin** [comment]
PR #822 submitted.
