### ISSUE TITLE
Remove @Component line 

### ISSUE THREAD

**Issue by JavaScriptDude** [dart-lang/site-webdev#301]
On the page [Step 4: Add a Button](https://webdev.dartlang.org/codelabs/ng2/4-buttonbadge), after the line "Add a generateBadge() function.", remove the first line `@Component(selector: 'pirate-badge', templateUrl: 'badge_component.html')`.

This line is not show in other code blocks in the same page and since the code is not being changed, best to leave out.

**Comment by kwalrath** [comment]
Thanks for the feedback, this is really helpful.
