### ISSUE TITLE
Unclear why Template Syntax has 2 lines for NgForTrackBy

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#303]
https://webdev.dartlang.org/angular/guide/template-syntax says:

Now set the NgForTrackBy directive to that tracking function.

```
<div *ngFor="let hero of heroes; trackBy:trackByHeroes">({{hero.id}}) {{hero.fullName}}</div>
<div *ngFor="let hero of heroes" *ngForTrackBy="trackByHeroes">({{hero.id}}) {{hero.fullName}}</div>
```

It's a little strange to show 2 lines of code that seem to do the same thing, and there's no explanation.

The equivalent section in the [TS page](https://angular.io/docs/ts/latest/guide/template-syntax.html) has only one line of code:

```
<div *ngFor="let hero of heroes; trackBy:trackByHeroes">({{hero.id}}) {{hero.fullName}}</div>
```

**Comment by chalin** [comment]
The two lines of code are equivalent; and both work for AngularDart (and might still work for Angular TS too).

The example using `*ngForTrackBy` was removed by @filipesilva when the TS examples were migrated to rc.4; see https://github.com/angular/angular.io/commit/aa8ab52937694b0c360707c6952634cb029eab74#diff-f447cce4c09bd663a5c3bd048c280b6eL595.

No explanation was given in that PR, and I don't see any comment in the [angular changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md) stating that support for `*ngForTrackBy` was dropped, so my guess is that we simply don't want to encourage the use of `*ngForTrackBy`. So, like for the TS docs, I'll just remove it.

Cf. https://github.com/angular/angular/pull/6779, https://github.com/angular/angular/issues/6872#issuecomment-179469415.
