### ISSUE TITLE
Bad URL : https://webdev.dartlang.org/get-started

### ISSUE THREAD

**Issue by joeblew99** [dart-lang/site-webdev#31]
URL:  https://webdev.dartlang.org/get-started
Expected page:  Something, but hard to tell since i cant see it :)

The parent page is here: https://webdev.dartlang.org/guides.
So this is where the URL link is wrong

**Comment by kwalrath** [comment]
It should go to https://webdev.dartlang.org/guides/get-started. Thanks for the report, @joeblew99.

**Comment by kwalrath** [comment]
Fixed by @Sfshaza in 8192ce1dcf5e8c45c0ea04393818d380726b3e43.
