### ISSUE TITLE
[ng] docs doesn't scroll to the appropriate section

### ISSUE THREAD

**Issue by Janamou** [dart-lang/site-webdev#315]
1. Open new tab in Chrome
2. Paste any url which has the hash part (this type of url is generated when clicking through the right navigation - for example https://webdev.dartlang.org/angular/guide/template-syntax#!#two-way-binding-with-ngmodel (or any other))
3. It doesn't scroll to the appropriate part of the page

Seems to be problematic only in Angular docs.

**Comment by chalin** [comment]
@Janamou - try dropping the `!#` (which is an artifact of AngularJS); e.g., try https://webdev.dartlang.org/angular/guide/template-syntax#two-way-binding-with-ngmodel

**Comment by Janamou** [comment]
@chalin That works but the links generated in the url bar by default (when navigating) are not directly usable/shareable/etc. :-)

**Comment by chalin** [comment]
Hmm, actually, I'm quite sure that this was not a problem before (and it isn't a problem for angular.io). I'll have to investigate further.

For the record, when referencing pages from posts, etc. it is best to drop the `!#`.

**Comment by kwalrath** [comment]
I've seen a similar issue—only in Angular pages—when trying to integrate the Google Feedback button (#106).
