### ISSUE TITLE
get started - "Angular Web Application" template no longer suitable as base

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#317]
https://webdev.dartlang.org/guides/get-started#4-create-and-run-a-web-app suggests using the stagehand web-angular template (via WebStorm's _New Project_ **Angular Web Application** template).

But that stagehand template has been updated to make use of angular components, and so is no longer a suitable base. The **Angular Quickstart** template is likely the proper base.

**Comment by kwalrath** [comment]
I should have a PR today.

**Comment by kwalrath** [comment]
I decided to keep using the web-angular template, but adjust the screenshots and instructions a bit.
