### ISSUE TITLE
Dart polymer breaks with 10 iOS update 

### ISSUE THREAD

**Issue by aslanvaroqua** [dart-lang/site-webdev#33]
New iOS update broke all our apps: dart polymer.

**Comment by kwalrath** [comment]
Yikes, that sounds bad.

@aslanvaroqua, could you please file a bug at https://github.com/dart-lang/polymer-dart/issues, and then close this bug with a link to that one?

(If that doesn't happen, I'll move this bug, but then it'll be under my name, not yours.)

**Comment by aslanvaroqua** [comment]
closing this.
