### ISSUE TITLE
Create Angular version note

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#330]
Every webdev/angular page needs some kind of note that (1) says what version it describes and (2) links to where the reader can find more information about [changes between] versions.

For now, the version is 2.2, and more info is available at https://pub.dartlang.org/packages/angular2/versions/3.0.0-alpha#changelog.

To avoid the churn of updating that link and to be able to give more context, we might want to have an intermediate page, rather than just linking to the latest changelog.

**Comment by chalin** [comment]
How about this organization for the version page table:
> ![screen shot 2017-01-26 at 9 17 05 am](https://cloud.githubusercontent.com/assets/4140793/22342238/89c308f4-e3a8-11e6-8b2f-dd3113f072af.png)

Regarding the examples: while we will have a branch of webdev for the dev stream, I don't recommend that we create a dev branch in each individual sample repo. IMHO, it's not worth the trouble of setting it up (including changes to the dart-doc-syncer).

**Comment by kwalrath** [comment]
I like separating the version info into its own column. Much clearer.

Re: the examples, I'd like readers to be able to find the dev versions, which is why I went into the weeds about the examples being generated from the site's source code—so I could link to the v3 branch of webdev.

But now I'm thinking that I should drop the "Examples" column and just have a paragraph dedicated to the examples. That way I can explain it more clearly, without gumming up the table.

**Comment by chalin** [comment]
+1 to dropping the Examples column in favor of a paragraph of explanatory text.

**Comment by kwalrath** [comment]
Fixed by #344.
