### ISSUE TITLE
[ng] update HTTP / server-communication to at least match the tutorial HTTP page

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#334]
While the tutorial section on HTTP has evolved, the server-communication has some outdated sections.

It might be a good idea to at least mark the section as outdated and to refer the reader to the tutorial HTTP section in the meantime. @kwalrath, thought?

- [x] adjust headings - the page contains more than one level-1 heading.
- [x] update prose and example to match newer material in toh-6

**Comment by kwalrath** [comment]
Agreed. Perhaps we could add to the note at the top of the page? Is this page completely useless, or does it have some information that's useful? If the latter, can you tell me which parts are use(ful|less)?

I can do the note and the heading adjustments.

**Comment by chalin** [comment]
Most of it is valid, it is just that it is out-of-date with toh-6 (which is now more fully developed). We should come up with a plan offline and summarize a proposed strategy here.
