### ISSUE TITLE
`<` but no link if prevpage not defined

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#339]
On Angular pages like that have a nextpage but no prevpage, a `<` appears has no title or link. This isn't an issue in non-Angular pages (such as tutorials) because they don't use the `<`.

For example, here's a screenshot from https://webdev.dartlang.org/angular/guide, with the offending `<` circled:

![image](https://cloud.githubusercontent.com/assets/2164483/22357416/bf029c7a-e3ec-11e6-9a7f-395bee6ecab5.png)

Although much less likely to be encountered, something similar happens for pages like https://webdev.dartlang.org/angular/guide/structural-directives with a prevpage but no nextpage:

![image](https://cloud.githubusercontent.com/assets/2164483/22357451/0065d876-e3ed-11e6-95ff-5c00096939db.png)

**Comment by kwalrath** [comment]
The relevant file: `_includes/navigation-sub.html`

**Comment by chalin** [comment]
WAI. There is no text because there is nothing to link to. This was a design alternative vs what we had before where the prev/next navigation links that would word-wrap etc. The current scheme works regardless of the display width. The lone "<" isn't active -- i.e., it can't be clicked.

We can do better (e.g., if we resort to using Angular :) ... but I'd prioritize other parts of the docs.

**Comment by kwalrath** [comment]
Perhaps we could ALWAYS have a previous file—/angular/guide or /angular or if nothing else is appropriate.

**Comment by chalin** [comment]
That is an interesting proposal. Would you like for me to implement that as a solution to this issue?

**Comment by chalin** [comment]
Ok, but some of it is setup automatically, so if you make manual modifications, I'll still have to do some script adjustments.

**Comment by kwalrath** [comment]
Now that I've added a previous page to https://webdev.dartlang.org/angular/guide, this issue isn't very noticeable. It still rubs me the wrong way, but I'm closing this because we're unlikely to ever get to it.
