### ISSUE TITLE
Fix wrapping of Angular page titles

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#345]
From a review by @chalin of #344 (screenshots are from https://webdev.dartlang.org/angular/guide/):

> ...The old CSS resulted in "clean" title wrapping for narrow displays, like this:
>> ![screen shot 2017-01-28 at 10 58 00 am](https://cloud.githubusercontent.com/assets/4140793/22399046/cd2731c8-e548-11e6-9e1c-3fef88d3cb9d.png)
>
> On the other hand, the new titles look like this:
>> ![screen shot 2017-01-28 at 10 57 44 am](https://cloud.githubusercontent.com/assets/4140793/22399043/ba8b20d8-e548-11e6-9e97-ca3bff0555a4.png)

Patrice suggested going back to a background image, but I don't know how to do that while making the image a link. I tried a bit to make this work (see the following code) but it didn't, for some reason:

```
.ng-page-title {
  margin-left: 3.1em;
  text-indent: -5.3em;
}
```

**Comment by cgomezmendez** [comment]
I think I got it.
make the text of the title be inside a p element, and add float:left to the image, but I could only test it with chrome inspect element, I'm on a windows enviroment and I haven't be able to run the project.

**Comment by kwalrath** [comment]
Thanks, @cgomezmendez! Sorry about the lack of instructions/support for windows... As you might be able to tell, the people who normally work on this site use Macs.
