### ISSUE TITLE
Add a "components" entry to the LH menu for Angular?

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/site-webdev#352]
In addition to 

ANGULAR
About
Guide 
Tutorial 
Advanced 
API Reference
Cheat Sheet
Glossary

Maybe we could add an entry "Components" linking to, e.g., https://dart-lang.github.io/angular2_components_example/

**Comment by kwalrath** [comment]
Yes we should. I'm working on the sidenav right now, so I can do this now. If git stops fighting me... (fatal: cache-tree: internal error).
