### ISSUE TITLE
[ng] API docs, router OnActivate and other interfaces: create examples?

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#367]
The relevant file is [src/router/interfaces.dart](https://github.com/dart-lang/angular2/blob/master/lib/src/router/interfaces.dart), that defines interfaces like `OnActivate`. The API docs for these interfaces currently have `@disabled-source` entries.

- [x] `CanDeactivate` - #375, https://github.com/dart-lang/angular2/pull/283
- [x] `OnDeactivate` - #424, https://github.com/dart-lang/angular2/pull/290
- [x] `CanReuse` - #424, https://github.com/dart-lang/angular2/pull/290
- [ ] `OnActivate` - #530, https://github.com/dart-lang/angular2/pull/338
- [x] `OnReuse` - #424, https://github.com/dart-lang/angular2/pull/290

**Comment by chalin** [comment]
@henrysenger @potato620 @matanlurey - before I create Dart specific examples for interfaces like `OnActivate` defined in [src/router/interfaces.dart](https://github.com/dart-lang/angular2/blob/master/lib/src/router/interfaces.dart), I'd like to know:
- Are these interfaces currently being used?
- As I understand, router changes are on their way. Will these interfaces still be relevant under the new router?

cc @kwalrath

**Comment by potato620** [comment]
Yes they are still being used and the new API will be more or less the same for these interfaces. Just a few small name changes.

**Comment by chalin** [comment]
@potato620 - do you know if there is an ngDart equivalent to the [RouterLinkActive directive](https://angular.io/docs/ts/latest/api/router/index/RouterLinkActive-directive.html)? If not, is there a coding idiom that is recommended to emulate it?

**Comment by potato620** [comment]
You mean in the new API? RouterLink / RouterLinkActive will both exist. The routing on RouterLink may be slightly different but mostly the same.
