### ISSUE TITLE
material-expansionpanel-set seems not to work under a material-tab

### ISSUE THREAD

**Issue by PeterWillems** [dart-lang/site-webdev#378]
The problem is rather simple, see the template below:

```
<material-tab-panel>
  <material-tab label="test">
    <material-expansionpanel-set>
      <material-expansionpanel name="panel  #1">
        Test 1
      </material-expansionpanel>
      <material-expansionpanel name="panel 2">
        Test 2
      </material-expansionpanel>
    </material-expansionpanel-set>
  </material-tab>
</material-tab-panel>
```
The Dartium browser renders nothing. If I remove the surrounding material-tab-panel and material-tab the expansion-panels are rendered with the expected accordion behavior. In reverse without the expensionpanel-set the tab is rendered correctly. It seems that the combination causes the problem. Compiling to JavaScript does not change this outcome.

**Comment by kwalrath** [comment]
This seems to belong under https://github.com/dart-lang/angular2_components/issues. Could you file a bug there? (I could move it, but then you'd lose some of the benefits GitHub gives you when you file it yourself.)

**Comment by PeterWillems** [comment]
Sorry for posting this issue in the wrong GitHub section.
I have moved it a few days ago to dart-lang/angular2_components and there it was recognized to be repaired in the next release.

**Comment by PeterWillems** [comment]
Dear Kathy,

Sorry for posting this issue into the wrong GitHub category.
I have moved it a few days ago to dart-lang/angular2_components and there it was recognized to be repaired in the next release.

Regards,
Peter



Dr. ir. P.H. (Peter) Willems
Research Scientist
Structural Reliability

T +31 (0)88 866 31 39
M +31 (0)61 026 94 70
E peter.willems@tno.nl<mailto:peter.willems@tno.nl>

Location<http://www.tno.nl/locaties/DTM>



[cid:image001.gif@01D28CDF.546645B0]<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.






Van: Kathy Walrath [mailto:notifications@github.com]
Verzonden: dinsdag 21 februari 2017 22:21
Aan: dart-lang/site-webdev <site-webdev@noreply.github.com>
CC: Willems, P.H. (Peter) <peter.willems@tno.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [dart-lang/site-webdev] material-expansionpanel-set seems not to work under a material-tab (#378)


This seems to belong under https://github.com/dart-lang/angular2_components/issues. Could you file a bug there? (I could move it, but then you'd lose some of the benefits GitHub gives you when you file it yourself.)

**Comment by kwalrath** [comment]
No worries, I see it at dart-lang/angular2_components/issues/54. Thanks for filing bugs!
