### ISSUE TITLE
Can't download Dartium for Mac

### ISSUE THREAD

**Issue by patlillis** [dart-lang/site-webdev#39]
On https://webdev.dartlang.org/tools/dartium, clicking the "Dartium for Mac" link goes to an error page that says "NoSuchKeyThe specified key does not exist."

Tried on Chrome, Firefox, and Safari, all went to an error page and did not download Dartium.

Below screenshot is from Chrome:
![image](https://cloud.githubusercontent.com/assets/2921735/19859573/6312a01c-9f4b-11e6-9d5a-0a089ee43c5e.png)

**Comment by kwalrath** [comment]
@whesse are you the person to help with this?

**Comment by kwalrath** [comment]
@patlillis Thanks for reporting this outage. The workaround would be to use Homebrew `brew install dart --with-dartium` to download the software.

**Comment by whesse** [comment]
The Dartium build for mac is now 64-bit, and its address has changed.  We changed the download links in the archive page, but didn't see these links.  The link target just needs to be changed from 

https://storage.googleapis.com/dart-archive/channels/stable/release/latest/dartium/dartium-macos-ia32-release.zip 
to
https://storage.googleapis.com/dart-archive/channels/stable/release/latest/dartium/dartium-macos-x64-release.zip

**Comment by kwalrath** [comment]
Now I remember Shams mentioning that. Ok, that I can fix.

**Comment by kwalrath** [comment]
Fixed in 62d854c7d4edf76974c4873bec2c12a06da21285. Should be visible on the site within 15 minutes or so.

**Comment by patlillis** [comment]
Thanks! Link is now working.
