### ISSUE TITLE
Add "Code Lab" as entry under RESOURCES

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#400]
There is no longer a **Code Lab** entry in the side nav, so when we visit the Darrrt code labs, no side nav entry is highlighted. Consider adding a "Code Lab" as entry under RESOURCES.

**Comment by kwalrath** [comment]
I think we left it out on purpose, since the code labs were rather old. That was before we added the AngularDart Components code lab, which _is_ in the sidenav. So... WAI?

**Comment by chalin** [comment]
In the [What next?](https://webdev.dartlang.org/guides/get-started#what-next) section of the "Get Started" page, one of the places we suggest readers visit is Code Labs.  If we think that the code labs are outdated, then:
- We should label them as such
- Not direct readers to them at the end of "Get Started"

I think that all the code labs are ok.

Reopening because I think that _some_ action needs to be taken.

**Comment by chalin** [comment]
I believe that the latest decision has been to add a comment(s) to the individual code labs. So, closing this for now since @kwalrath will be updating the code labs.

cc @Sfshaza
