### ISSUE TITLE
tutorial/toh-6 example just says "loading" 

### ISSUE THREAD

**Issue by lymp** [dart-lang/site-webdev#412]
Hi,
My first day with AngularDart (but I know Polymer Dart). I downloaded this zip, and ran it in WebStorm, but it just says "loading" in the webpage.
It also doesn't show the dart analyzer. I created a new [stagehand] project, which does run, and also shows the dart analyser, so I copied the lib folder etc from **toh** to the new project. It still doesn't do anything...
cheers
Steve

**Comment by kwalrath** [comment]
@lymp, I suspect you're running into a base href issue, which we're in the process of fixing. Try changing the base href code (in the `<head>`) to this code [from Stagehand's latest web-angular template](https://github.com/google/stagehand/blob/master/templates/web-angular/web/index.html):

```
    <script>
        // WARNING: DO NOT set the <base href> like this in production!
        // Details: https://webdev.dartlang.org/angular/guide/router
        (function () {
            // App being served out of web folder (like WebStorm does)?
            var match = document.location.pathname.match(/^\/[_\w]+\/web\//);
            var href = match ? match[0] : '/';
            document.write('<base href="' + href + '" />');
        }());
    </script>
```

cc @chalin

**Comment by kwalrath** [comment]
PS: Thanks for filing this issue! I'll leave it open until we've fixed this everywhere.

**Comment by lymp** [comment]
Hi Kathy,

I've created a new project (myheroes) in Webstorm, replaced the script, and
imported the toh lib etc. No Dart errors. But when I run I get:

The requested built-in library is not available on
Dartium.'package:http/src/io_client.dart': error: line 6 pos 1: library
handler failed
import 'dart:io';
^: package:http/src/io_client.dart
GET
http://localhost:63342/myheroes/web/packages/myheroes/hero_service.template.dart

An error occurred loading file: package:myheroes/hero_service.template.dart

What do I do please?

cheers
Steve

**Comment by kwalrath** [comment]
What imports dart:io? It doesn't work in web apps (i.e. with dart:html and libraries that depend on dart:html).

**Comment by chalin** [comment]
I don't believe that there is any pending issue with the toh-6 example code or the docs so I'll close this. @lymp, if you have further questions you might consider posting them to the [Angular Gitter](https://gitter.im/dart-lang/angular2) room.
