### ISSUE TITLE
Move "Common problem: registering the wrong component" closer to the import

### ISSUE THREAD

**Issue by saeedbinhamad** [dart-lang/site-webdev#43]
the image in the codelab shows <acx-scorecard> which is wrong, please update image to show  <acx-scoreboard> which is working, because its confusing people, specially beginners like me.

<img width="604" alt="screen shot 2016-11-06 at 7 55 41 pm" src="https://cloud.githubusercontent.com/assets/18968640/20039780/0b175aaa-a45b-11e6-81eb-f82c406acbad.png">
.

**Comment by kwalrath** [comment]
The code is actually `<acx-scorecard>`: https://github.com/dart-lang/one-hour-codelab/blob/master/angular2_components/4-final/lib/scores/scores.html.

Does the 4-final version of the sample work for you?

**Comment by saeedbinhamad** [comment]
Thanks for your reply. Yeah i had a look later on at 4-final and it worked. But strangely if you follow from the beginnig it doesnt work/fit as shown in step by step codelab. I went ahead and copied 4-final code into where im at now and it worked. 

Maybe we should revise and correct the early steps since we are trying to learn here.

**Comment by kwalrath** [comment]
I wonder if you accidentally imported the class for <acx-scoreboard> instead of <acx-scorecard>.

**Comment by kwalrath** [comment]
I bet the problem is in this line:

```
  directives: const [ScorecardComponent],
```

**Comment by kwalrath** [comment]
In fact, I noticed that once going through the code lab, I imported the wrong component, so I called that out as a common problem. (See below.) But maybe I should move/copy that box to be earlier, just after the import.

![image](https://cloud.githubusercontent.com/assets/2164483/20070111/138f844a-a4d4-11e6-8508-5201f7fcdc56.png)
