### ISSUE TITLE
[ng] doc request: lazy fetching

### ISSUE THREAD

**Issue by Janamou** [dart-lang/site-webdev#436]
Hi,

Angular has a lot of documentation about module lazy loading (for example https://angular.io/docs/ts/latest/guide/ngmodule.html#!#lazy-load).

@matanlurey wrote a tutorial how to do something similar in Dart. I think this should be definitely part of the documentation: https://medium.com/@matanlurey/lazy-loading-with-angular-dart-14f58004f988#.fy46zk7bx

Thanks! :-)

**Comment by chalin** [comment]
Folding this issue into #582 (since there is a bit more discussion already over it).
