### ISSUE TITLE
Clarify on the homepage "webdev" vs AngularDart

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-webdev#443]
In discussions with @lukechurch 

Folks are confused by what "webdev" means vs AngularDart.

We could explain that Dart has a webdev story w/ dart2js, pub etc
...and we have a recommended Framework: AngularDart

Maybe?

**Comment by kwalrath** [comment]
@kevmoo & @lukechurch, we should talk about this. Do we need to restructure the hompage, or is this just a tweak to the wording? (I tried tweaking the wording, but I couldn't see a good way to do the job within the first screenful.)

**Comment by filiph** [comment]
Proposal (focused on the minimal diffs with maximum impact -- we should follow up with word-smithing):

Remove 'About AngularDart' here. Instead, just provide 'Get Started' as a single golden path.

![screen shot 2017-03-16 at 14 22 25](https://cloud.githubusercontent.com/assets/919717/24019134/07a604b6-0a54-11e7-86d8-f7b56decdcf7.png)

In Get Started, in [step 4](https://webdev.dartlang.org/guides/get-started#4-create-and-run-a-web-app) (Create and run a web app), provide a 'safety hatch' for people who don't want AngularDart. Also, provide explanation why we're recommending AngularDart. Something like this:

> We recommend using Angular for your Dart web apps, as it's the easiest way to get started and build large web apps. That being said, there are [other web frameworks](https://pub.dartlang.org/search?q=web+framework) and you can also [build web apps in Dart without one](https://webdev.dartlang.org/tutorials/low-level-html/connect-dart-html) while still reaping the language's benefits.
> 
> Here’s how to use WebStorm to create a web app that uses Angular:
>
> * ...

@lukechurch, does this feel like it would address the issue?

**Comment by lukechurch** [comment]
@filiph Thanks for the suggestion, I think it's a step in the right direction, however I think we need to do something deeper than this. I think I'll file seperate bugs to keep the number of places each issue touches and use this as a tracking location for each of them.

I'm going to make a fairly bold proposal, and let's see if we want to dial it back from there.

**Comment by chalin** [comment]
@kwalrath - anything left to do for this issue?

**Comment by kwalrath** [comment]
I think we're done. Closing it.
