### ISSUE TITLE
Requesting example of Strong Mode type inference with Maps

### ISSUE THREAD

**Issue by sethladd** [dart-lang/site-webdev#467]
I checked out https://www.dartlang.org/guides/language/sound-dart#type-inference and I was hoping to find more examples of inference with collections and generics.

For example, how would I rewrite this code in strong mode? `Map<String, dynamic> arguments = { 'argA': 'hello', 'argB': 42 };`

and:

```
 Map<String, dynamic> message = {
      'method': 'someMethod',
      'args': <Map<String, dynamic>>[arguments],
    };
```

and:

```
List<dynamic> arguments = methodCall['args'];
```

Can I use var in all those cases, and get the same variable type as what's explicitly annotated?

**Comment by chalin** [comment]
Hi Seth. Did you really intend to open this issue here over webdev? Or was it meant for `site-www`?

cc @kwalrath

**Comment by sethladd** [comment]
oops! sorry. I meant site-www. I'll move it. Thanks!

**Comment by sethladd** [comment]
This issue was moved to dart-lang/site-www#257
