### ISSUE TITLE
Update screenshots to reflect new template

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#476]
As of Stagehand 1.1, we have a new template (StageXL), which means that all WebStorm screenshots that show the WebStorm **New Project** window are slightly obsolete.

I'm marking this a P3 because (1) it's a pain to update these screenshots (you don't just take a new screenshot, you edit it so the displayed home directory is `/Users/me`) and (2) I don't think it's too confusing. But I could be wrong about (2).

For a list of which docs depend on the template list, see https://github.com/google/stagehand/wiki/Docs-that-depend-on-stagehand#pages-that-depend-on-the-list-of-templates.

**Comment by chalin** [comment]
I believe that this had been resolved (as we did other cleanup).
