### ISSUE TITLE
Consider s/webdev/Dart for web/ on the homepage of DartLang

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/site-webdev#489]
Please see internal email.

As per https://github.com/dart-lang/site-webdev/issues/443 we're seeing confusion between AngularDart and WebDev. To address this confusion on the homepage of dartlang.org let's consider:

- Replacing the gray box 'Dart webdev' with 'Dart for the web'
- Replacing the text in the footer link with 'Dart for the web'
- Replacing the icon in the header bar with 'Dart for the web'
- Deleting the footer link to 'AngularDart'

**Comment by kwalrath** [comment]
All done, except for removing the footer link to AngularDart. @lukechurch do you still want us to do that?

**Comment by kwalrath** [comment]
Closing. We can open a new bug for any future changes.
