### ISSUE TITLE
Angular vs AngularDart is used inconsistently on the site

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/site-webdev#490]
We use 'Angular' and 'AngularDart' in a way that may cause some confusion in studies. Consider replacing:

- [x] "Angular" from the black header bar with "AngularDart"
- [x] "ANGULAR" from the LHS menu with "ANGULAR DART" (Visual distinguishability amongst MULTIPLEWORDBLOCKCAPS is too poor to just use one word)
- [x] "ANGULAR COMPONENTS" -> "ANGULAR DART COMPONENTS" (Sorry I know it flows onto two lines, but that's probably better than confusion)
- [ ] Replace the name of the sample application template Angular Web Application with "AngularDart Web Application" and "Simple Angular Example" with "Simple AngularDart Example"
- [x] Replace the link text for "Setup for Angular development" with "Setup for AngularDart development"

On https://webdev.dartlang.org/guides/web-programming

- [x] Replace "Angular" header with "AngularDart"

On https://webdev.dartlang.org/codelabs/ng2

- [x] Replace "Angular App" with "AngularDart App"
- [x] Replace "simple web app with Dart and Angular" with "simple web app with AngularDart"

On https://webdev.dartlang.org/codelabs

- [x] Replace "Angular 2 for Dart" with "AngularDart"
- [x] Replace "Beautify an Angular web app" with "Beautify a web app"

**Comment by filiph** [comment]
Which reminds me that our stagehand template is called 'Angular Web App'. It should probably be AngularDart Web App.

**Comment by kwalrath** [comment]
Yep, I filed a bug about that.

**Comment by kwalrath** [comment]
Closing, since all the webdev issues have been addressed in #517 . The stagehand issue is tracked here: https://github.com/google/stagehand/issues/387

**Comment by kwalrath** [comment]
Note that the webdev site is currently frozen due to angular v3 work. These changes will be visible once a stable version of v3 ships.

**Comment by kwalrath** [comment]
I've staged the latest version of the site here:

https://webdev-angular3-dartlang-org.firebaseapp.com
