### ISSUE TITLE
Tweak scaffolding of Get Started path

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/site-webdev#493]
I think we can afford to put in a bit more text in the 'Getting Started' block, something along the lines of a better wordsmithed version of:

"Follow these steps to start using Dart to develop web apps. We'll start with a mini example in your browser, and then build a small app using the AngularDart framework"

As @filiph suggests here: https://github.com/dart-lang/site-webdev/issues/443

We could then add some bailout text in section 4 for people who don't want to use AngularDart. This would also mean that we could delete the "More information: Dart tools for the web" link. We may wish to adopt the terminology that we introduce in the codelab of "low level HTML" as an alternative to AngularDart

**Comment by kwalrath** [comment]
The "Dart tools for the web" link is for alternatives to WebStorm, not alternatives to AngularDart. I don't see those "more information" links as a problem. Do you?
