### ISSUE TITLE
Introduce better linking of the CodeLabs page into LHS of WebDev

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/site-webdev#494]
The available code labs (https://webdev.dartlang.org/codelabs) page is a bit tricky to find. 

Consider: 
 - adding a link under the ANGULAR section 'Code Lab' that links to https://webdev.dartlang.org/codelabs/ng2
 - adding a link under the RESOURCES section 'Low level Code Lab' that links to https://webdev.dartlang.org/codelabs/darrrt

**Comment by kwalrath** [comment]
This was somewhat intentional. We didn't want to remove the code labs, but they're not exactly our recommended path. We should have a new AngularDart code lab soon, which could replace the ng2 one.

I'll leave this open because I'm still pondering...

**Comment by kwalrath** [comment]
Fixed by #801.
