### ISSUE TITLE
angular landing page - image clear issue

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#50]
### Narrow view is fine
![screen shot 2016-11-11 at 11 13 01 am](https://cloud.githubusercontent.com/assets/4140793/20227159/f3767f4a-a7ff-11e6-8707-1430caf4b601.png)
### Wide view
Scrolling down will make text re-appear below the image, but we shouldn't have this glitch.
![screen shot 2016-11-11 at 11 13 29 am](https://cloud.githubusercontent.com/assets/4140793/20227168/075b62e6-a800-11e6-9304-8bbe3132c77b.png)

**Comment by chalin** [comment]
Reopening. I made changes to the originating ng.io sources; namely replaced the clear=all by:
```
<br style="clear:left;">
```
which seems to work fine under ng.io, but we have the same wide-view issue as illustrated above. @ericjim - your fu is needed here :)

**Comment by chalin** [comment]
It seems that the wide-view problem is related to the presence or not of the `fixed_nav` class being applied to the `body`.

**Comment by ericjim** [comment]
I'll have a look today.

**Comment by chalin** [comment]
Also see #95
