### ISSUE TITLE
404 for ChangeDetectionStrategy

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#509]
Figure out why people are getting to https://webdev.dartlang.org/angular/api/angular2/ChangeDetectionStrategy-class instead of https://webdev.dartlang.org/angular/api/angular2.core/ChangeDetectionStrategy-class. (Google search returns the latter). Redirect if necessary.

**Comment by kwalrath** [comment]
fyi @kevmoo, I looked into this a bit but couldn't figure out where people were getting this link.

**Comment by chalin** [comment]
Is this something you want me to investigate? If so, please provide more context: how are folks getting to the invalid link (from where)? Or are you seeing this link in the analytics?

**Comment by kwalrath** [comment]
I'm seeing this in the analytics for the 404 page. Don't worry about it... it's not many people. I just wanted to record what I knew, so far.

**Comment by kwalrath** [comment]
I don't think this is an issue any more.
