### ISSUE TITLE
add a diName attribute to @Component

### ISSUE THREAD

**Issue by ziedHamdi** [dart-lang/site-webdev#514]
I have a component which contains a generic popup, it implements therefore the interface **PopupParent**

```
@Component(
    //...
)
class SubjectListComponent implements PopupParent {
}

```
The generic class **InfoPopup** needs to deal abstractly with its parent (that implements PopupParent), so I would like to get the parent injected by its interface (instead of being injected by its concrete class **SubjectListComponent**)

```
class InfoPopup {
  final PopupParent _parent;

  InfoPopup(this._parent);
  //...non relevant code
}
```
The issue is that the SubjectListComponent was registred by class in the injector, so the injector won't find what to inject into the InfoPopup class.

If I try to declare my SubjectListComponent manually, I found that it has to be done in the providers constants. but I still don't have my instance of SubjectListComponent when I declare my component...

Here's the so discussion about it : [http://stackoverflow.com/questions/43185353/dependency-injection-for-interfaces]

I think there should be a way to declare the component injection name to use it selectively in the hosts eg:
```
@Component(
  diName: "PopupParent",
  //...
)
```

The in the host specify the di by name
```
@Component(
  providers: [
      const Provider(PopupParent, useExisting: "PopupParent"),
  ]
)
class InfoPoupup {}
```

**Comment by zoechi** [comment]
Can you please move the issue to the https://github.com/dart-lang/angular repository ?

**Comment by kwalrath** [comment]
I could do the move for you, @ziedHamdi, but then you'd lose credit/notifications.

**Comment by chalin** [comment]
@ziedHamdi - we'll let you move this to the angular2 repo if you still think it is relevant. Closing it here.
