### ISSUE TITLE
the keyword 'this' is not supported in the templates

### ISSUE THREAD

**Issue by ziedHamdi** [dart-lang/site-webdev#515]
Hi,

There's an issue when I try to use the component's instance as an input of another component

```
<div>
  <info-popup [parent]="this"></info-popup>
</div>
```

Actually the template engine complains that there is no property named 'this' in the component

**Comment by zoechi** [comment]
Can you please move the issue to the https://github.com/dart-lang/angular repository ?

**Comment by chalin** [comment]
Thanks @zoechi. Closing.
