### ISSUE TITLE
Angular docs must integrate with floating table of content

### ISSUE THREAD

**Issue by ericjim** [dart-lang/site-webdev#52]
![screen shot 2016-11-11 at 3 27 10 pm](https://cloud.githubusercontent.com/assets/1329167/20229243/55aeb65a-a823-11e6-9cb3-9648ba5e4fd1.png)

^the "On this page" should be able to jump around the doc

**Comment by chalin** [comment]
Fixed a day or two ago.

**Comment by chalin** [comment]
Reopening because the TOC appears for all pages but the Guide landing page.

**Comment by chalin** [comment]
The issues with the guide landing page was that there were no `<h2>` headings :).
