### ISSUE TITLE
The canonical JSON+Dart+Webapp article is referencing a probably-unmaintained library

### ISSUE THREAD

**Issue by sethladd** [dart-lang/site-webdev#526]
https://webdev.dartlang.org/articles/get-data/json-web-service is referencing a library that is probably unmaintained. (JsonObject) . Should we update the article?

**Comment by kwalrath** [comment]
@chrisbu, would you be interested in updating this article?

**Comment by chalin** [comment]
@chrisbu, you are more than welcome to make the updates, but in case you are busy, I can do them. I need to update a page with similar content anyways.

**Comment by kwalrath** [comment]
Closing in favor of a more up-to-date bug, #1634.
