### ISSUE TITLE
[ng] API docs: hide @source directives

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#551]
See https://github.com/dart-lang/angular2/pull/338#issuecomment-293085513 for the initial thread of discussion.

**Comment by chalin** [comment]
@kwalrath - I've made some progress on this. An example is staged at: https://angulardart-org-dev.firebaseapp.com/angular/api/angular2.common/NgClass-class

Which you can contrast with: https://webdev.dartlang.org/angular/api/angular2.common/NgClass-class.

It _is_ much nicer w/o the `{@source}`!

**Comment by kwalrath** [comment]
Yes, much nicer!

**Comment by chalin** [comment]
Resolved by https://github.com/dart-lang/angular2/pull/371
