### ISSUE TITLE
Don't depend on web-angular-simple template

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#591]
(I thought we already had a bug for this, but I can't find it.)

We have too many stagehand templates (https://github.com/google/stagehand/issues/390).

We need to have just one AngularDart template, so web-angular-simple has to go. We can add some/all of its features (e.g. test/) to web-angular. We can modify web-angular, but it needs to still feature material design and be simple yet interactive.

cc @chalin @filiph

**Comment by filiph** [comment]
Yes, this closely relates to https://github.com/google/stagehand/issues/390. What are the next steps? Does someone need to rewrite the web-angular template over at stagehand first? Any takers?

**Comment by chalin** [comment]
Here is a proposal:

## stagehand
- Drop `web-angular-simple`.
- `web-angular`
  - Drop the `<script>` dynamically setting `<base href>`.
  - Optional: add basic tests.
## webdev/angular docs
- [**Get started** page](https://webdev.dartlang.org/guides/get-started) stays as is, built off of `web-angular`.
- [**Setup** page](https://webdev.dartlang.org/angular/guide/setup) is changed to use [WS's integrated support](https://www.jetbrains.com/help/webstorm/2017.1/using-github-integration.html) for [**creating a project from a git repo**](https://www.jetbrains.com/help/webstorm/2017.1/setting-up-a-local-git-repository.html#cloneExistingRepository). We can either give the link to the [quickstart git](https://github.com/angular-examples/quickstart.git) directly in the page, or show users how to find it:
    > ![screen shot 2017-05-01 at 5 38 23 pm](https://cloud.githubusercontent.com/assets/4140793/25597329/22eb20e6-2e9c-11e7-96b2-5f749e4cdec0.png)

  If we show readers where to get the git URL from, then they'll be able to create projects from any one of the [Angular example repos](https://github.com/angular-examples/).

**Comment by kwalrath** [comment]
I didn't know WS had that support! How easy is it to use? The less setup, the better.

**Comment by chalin** [comment]
Almost as easy as using a template:

- Choose "**Checkout from Version Control > Git**" from either the **startup window**, or the **VCS** menu:
  > ![screen shot 2017-05-01 at 7 05 26 pm](https://cloud.githubusercontent.com/assets/4140793/25598184/90c78b90-2ea1-11e7-951f-3c9610bba7b5.png)

- In the dialog that pops up, enter the repo URL, parent directory and project name, then click Clone:
  > ![screen shot 2017-05-01 at 7 06 03 pm](https://cloud.githubusercontent.com/assets/4140793/25598206/aae03cf2-2ea1-11e7-81e0-c6d364179ffe.png)

- Answering "yes" to this dialog opens the freshly cloned project:
  > ![screen shot 2017-05-01 at 7 15 39 pm](https://cloud.githubusercontent.com/assets/4140793/25598365/a0da3ec8-2ea2-11e7-8bf9-1009910c196e.png)


- Then open `pubspec.yaml`, Enable Dart for this project, and that brings us back to where we would be if we'd have created it using one of the templates:
  > ![screen shot 2017-05-01 at 7 15 54 pm](https://cloud.githubusercontent.com/assets/4140793/25598369/a579e8ac-2ea2-11e7-80ae-0c443bc74128.png)

**Comment by kwalrath** [comment]
Works for me.

I'd still like the templates to be as close to each other as possible (e.g. add testing to web-angular, have the same pubspec & analysis options), but it does seem silly to require the template to be all things to all people.

@filiph what do you think?

**Comment by chalin** [comment]
Ok, I'll look into adding basic tests to `web-angular`.

**Comment by kwalrath** [comment]
The Git support is asking me for my github credentials. I shouldn't need those to be able to clone a project.

**Comment by chalin** [comment]
Right: choose "**Checkout from Version Control > Git**" (not GitHub).

**Comment by kwalrath** [comment]
It doesn't matter whether I choose Git or GitHub, they both ask for my credentials.

![image](https://cloud.githubusercontent.com/assets/2164483/25631654/e4778432-2f25-11e7-82e2-01ecfb8d09d3.png)

When I click the Test button, that too asks for my credentials.

![image](https://cloud.githubusercontent.com/assets/2164483/25631717/13ac5e94-2f26-11e7-9883-7f3ba9bedd72.png)

**Comment by kwalrath** [comment]
Ha! I think I mistyped angular-exampleS.

**Comment by kwalrath** [comment]
Starting the doc work now... Let me know if I should hold off, @chalin.

**Comment by kwalrath** [comment]
I can now remove the web-angular-simple template from Stagehand, as there are no more references to it on webdev (except in images that I'll have to retake once Stagehand is updated).

**Comment by filiph** [comment]
I love this! We just need to make sure we don't exclude non-WebStorm users too much ("Of course, you can clone the repository even if you don't use WebStorm, by doing ...."). 

Let me know if there's anything I should work on, on the stagehand repo or here.

I assume the work is split into these parts:

* Add a blurb about the `<base href>` workaround to each relevant place of the documentation.
* then: Remove the workaround from the web-angular stagehand template

And parallel to that

* Create new repo that holds the web-simple template.
* then: Change the tutorial docs to point to the repo instead of the template
* then: Delete web-simple template.

Is that right?

**Comment by kwalrath** [comment]
We've already done the "parallel to that" part! You can see the PR here: https://github.com/dart-lang/site-webdev/pull/596. The relevant text is in https://webdev.dartlang.org/angular/guide/setup and https://webdev.dartlang.org/codelabs/ng2/1-skeleton. They give both Webstorm and non-Webstorm instructions/links for downloading the example.

**Comment by chalin** [comment]
Right. https://github.com/angular-examples/quickstart is once again the `web-angular-simple`-like repo that the [Setup page](https://webdev.dartlang.org/angular/guide/setup) is based on -- #596.

I'm reworking web-angular. I'm essentially done with the app. I need to finalize the tests. I'll send screenshots or a link to a sample app shortly.

**Comment by chalin** [comment]
The screen shots are here: https://github.com/google/stagehand/issues/396

**Comment by kwalrath** [comment]
#596 removed the usage of web-angular-simple, so I'll close this.

(#602 will update web-angular, but that's a separate thing.)
