### ISSUE TITLE
Add README.md to examples/ng/doc

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#598]
From @kwalrath's comment https://github.com/dart-lang/site-webdev/pull/597#pullrequestreview-36071137: 
> We should probably mention these files and their location in a (new) README.md file in the examples/ng/doc directory.
>
> What else should we mention in the README? We should use strings that'll help us find the README whenever we're doing a search for related things that need to change globally. E.g., mention LICENSE and .gitignore and dart-doc-syncer by name.

**Comment by chalin** [comment]
This issue was originally prompted by #597, which moved boilerplate files out-of-sight into the DDS repo. Now, _all_ boilerplate files are in this repo. I think that we can close this issue. WDYT?

**Comment by kwalrath** [comment]
I'm fine with closing it.
