### ISSUE TITLE
Confusion in Master/Detail tutorial

### ISSUE THREAD

**Issue by LindaLawton** [dart-lang/site-webdev#601]
I will be referring to this page. [Master/Detail](https://webdev.dartlang.org/angular/tutorial/toh-pt2)

There are several places in the tutorial where the code location is pointed to `lib/app_component.html (hero list property)`  The issue i have with this is that at this point in the series we have not gone into creating app_components.html and at the end of the tutorial all of the html is placed in @Component(    template: ' ') as a beginner to Dart this caused me a few minutes of confusion but as an expected developer I was able to figure out the problem quickly. 

Options:

 - Either remove the  `lib/app_component.html (hero list property)`  and explain it differently.
 - Show the reader how to create and use app_component.html  at the beginning of the tutorial.  

Personally I like the second option I think having the that much html in the template parm is messy.

**Comment by kwalrath** [comment]
Agreed. It seems like we should have separate .css & .html files from the start. @chalin, is there a good reason (any more) to have everything in the .dart file?

**Comment by LindaLawton** [comment]
Give me a few days to go through the series I may have more comments. No reason for you guys to go through it more than once. 

I haven't done much web development in the last five years so I am doing this from the complete novice state.

**Comment by kwalrath** [comment]
OK, we'll hold off on changes for now. Thanks for taking the time to give us feedback!

**Comment by LindaLawton** [comment]
Defines AppComponent tests. While testing isn't covered in this tutorial, you can learn how to test the Tour of Heroes app from the Testing page.

If you aren't covering tests in the tutorial and they aren't required. Why even include this?

**Comment by LindaLawton** [comment]
[Multiple Components](https://webdev.dartlang.org/angular/tutorial/toh-pt3)   I think the order you are explaining things here is a little confusing.   

1. create hero_detail_component.dart 
2. Add hero property
3. create hero.dart.
4. import hero.dart
5. Add the template and change selectedHero to hero 

>The hero property is an input

Its a little confusing where this needs to go but i think that will be fixed when you add the .html file and get all the template stuff out of the dart file.

**Comment by LindaLawton** [comment]
[Services](https://webdev.dartlang.org/angular/tutorial/toh-pt4)
>Inject the HeroService
Three lines replace the one line of new:

I am only seeing two lines  
```
final HeroService _heroService;
AppComponent(this._heroService);
```

>Angular has to get that instance from somewhere. That's the role of the Angular Dependency Injector. The Injector has a container of previously created services. Either it finds and returns a pre-existing HeroService from its container or it creates a new instance, adds it to the container, and returns it to Angular.

This is an Angular Dart tutorial I understand that.  However I question wither or not you need to go into advanced Angular topics like Dependency injection in a beginner tutorial. 

That being said i don't have a problem with explaining why you have an _ in front of some parameters  `_heroService` a little bit of info on proper naming conversions could be considered ok.  

You have forgotten to tell the user they need to add import 'dart:async'

**Comment by chalin** [comment]
Thanks for the feedback.

> You have forgotten to tell the user they need to add import 'dart:async'

#585 is open to track that.

**Comment by chalin** [comment]
Thank you for the detailed feedback.

> There are several places in the tutorial where the code location is pointed to lib/app_component.html (hero list property)

I've chosen, for now, to keep the template in the `app_component.dart` file. I've fixed the excerpt titles to refer to the `.dart` file.

> If you aren't covering tests in the tutorial and they aren't required. Why even include this?

Because it calls attention to the presence of test files and is a segway to the Testing guide. I've added `app_test.dart` to file list of each tutorial part.

> Keep the app compiling and running

This was fixed a while ago (we now refers to the instructions given on the Setup page).

> Multiple Components I think the order you are explaining things here is a little confusing. I would move things around

I believe that this has been partly addressed by prior edits.

> How about a GitHub Repo with the full source have a branch for each tutorial. ?

We currently have one repo with the full source for each tutorial part. I'm not sure that we would benefit by having a single repo with multiple branches per part.

> Service ... I am only seeing two lines

Was fixed a while ago.

> I question wither or not you need to go into advanced Angular topics like Dependency injection in a beginner tutorial.

The tutorial prose was trimmed back in this regards.
