### ISSUE TITLE
Remove references to "directive's context object" in template syntax article

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/site-webdev#622]
In the [template syntax guide](https://webdev.dartlang.org/angular/guide/template-syntax) in the "Expression Context" section we say:

> The context for terms in an expression is a blend of the template variables, <b>the directive's context object (if it has one)</b>, and the component's members.

Directives do not have context objects. We should change this to just say the context is a blend of the template variables and the component's members.

**Comment by kwalrath** [comment]
Thanks for filing the issue, Harry.
