### ISSUE TITLE
Typo in 2-easystart.html

### ISSUE THREAD

**Issue by Lance-Inman** [dart-lang/site-webdev#628]
The **Use acx-scorecard** section of [webdev.dartlang.org/codelabs/angular_components/2-easystart ](webdev.dartlang.org/codelabs/angular_components/2-easystart)mentions "score.dart", "score.html", and "score.css" in lib/scores, when the actual filenames are "scores.dart", "scores.html", and "scores.css".

**Comment by chalin** [comment]
Thank you for filing an issue!
