### ISSUE TITLE
style fixes needed for code-example, code-pane, file-tree, etc

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#63]
- [x] API reference page formatting (api-list)
- [ ] main prose style
- [ ] prose headings styles
- [x] `alert is-important`, and a bunch of other related classes: should have a colored bounding box
  - [x] `callout is-helpful`
- [x] code-example
  - [x] Match background color (gray) of other Dart code samples - #134
- [x] cheatsheet styles
- [x] search text box text can't be seen (unless selected) -- see screen shot below
- [x] `<blockquote>` test is much bigger than the rest.
  - font-size seems to be fixed at 20 by bootstrap. How do we undo that?
- [x] code-pane
- [x] file-tree
- [x] code-shell
- [x] tables in general

E.g. 
-  ![screen shot 2016-11-14 at 12 40 36 pm](https://cloud.githubusercontent.com/assets/4140793/20282000/abbddbca-aa67-11e6-857c-c84c473933d3.png)
- ![screen shot 2016-11-14 at 6 17 39 am](https://cloud.githubusercontent.com/assets/4140793/20267995/1763850e-aa32-11e6-851f-936d1941b1c2.png)

**Comment by chalin** [comment]
Could you make the background of a code-example (non-code-shell) the same grey as code samples shown elsewhere on the site?

**Comment by ericjim** [comment]
For the API reference page consider grabbing the https://github.com/angular/angular.io/blob/master/public/resources/css/module/_api.scss file

**Comment by ericjim** [comment]
For alerts get these files
https://github.com/angular/angular.io/blob/master/public/resources/css/module/_alert.scss
https://github.com/angular/angular.io/blob/master/public/resources/css/module/_callout.scss

**Comment by ericjim** [comment]
For the cheatsheet get
https://github.com/angular/angular.io/blob/master/public/resources/css/module/_cheatsheet.scss

**Comment by ericjim** [comment]
code-example styles are the ones from ng1.io which come from https://github.com/angular/angular.io/blob/master/public/resources/css/module/_code.scss

If we want to use the dart ones, then consider using https://github.com/dart-lang/site-webdev/blob/ng-docs/src/_assets/stylesheets/_code.scss under `/angular` I think these two files are interexchangeable since they use prettyprint
