### ISSUE TITLE
[ng] don't wrap code

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#643]
This seems to be inherited from angular.io, but the code excerpt lines are wrapped. E.g.,
> ![screen shot 2017-05-20 at 11 43 45 am](https://cloud.githubusercontent.com/assets/4140793/26277052/53b63b6a-3d52-11e7-96ca-1e58dbbc52ac.png)

But, on narrow displays this generally reads much better when not wrapped:
> ![screen shot 2017-05-20 at 11 43 31 am](https://cloud.githubusercontent.com/assets/4140793/26277056/6ac4251a-3d52-11e7-9625-8edc04edde4b.png)

In fact, this is what is done on dartlang.org, e.g.:
> ![screen shot 2017-05-20 at 11 50 33 am](https://cloud.githubusercontent.com/assets/4140793/26277062/8e857e2c-3d52-11e7-8dc8-7c62d74d115c.png)

@kwalrath do you agree?

**Comment by chalin** [comment]
Notes: should probably change
- `prettyprint` `white-space` to `pre`
- `code` `white-space` to `pre`
- and ensure that `pre` `white-space` isn't set to wrapped

**Comment by kwalrath** [comment]
Yes, I agree that it's better to scroll than to wrap. (And better to have a shorter line length than to scroll.)
