### ISSUE TITLE
chore: firebase deployment is still broken

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#657]
As https://github.com/firebase/firebase-tools/issues/302 explains, starting with firebase-tools 3.6, `firebase serve` will require authentication credentials.

A first attempt at fixing this was done in #654. But deployment is still failing; see this [Travis log](https://travis-ci.org/dart-lang/site-webdev/jobs/235735143):
> > firebase serve --port 4001 --token [secure] --project dev
>
> Error: This command requires new authorization scopes not granted to your current session. Please run firebase login --reauth
>
> For CI servers and headless environments, generate a new token with firebase login:ci

**Comment by chalin** [comment]
As the message implied, all we needed was a new token. The build is now fixed, see: https://travis-ci.org/dart-lang/site-webdev/jobs/235735143

cc @kwalrath @filiph

**Comment by kwalrath** [comment]
Here's how we added the FIREBASE_TOKEN so travis could serve locally:

1. Visit https://travis-ci.org/dart-lang/site-www.
2. Click More options >> Settings.
3. Add FIREBASE_TOKEN under the Environment Variables section.
