### ISSUE TITLE
Update examples to use dartdevc+Chrome workflow

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#676]
After 1.24, we should start using the dartdevc+Chrome workflow everywhere. Tasks:

* [x] Test all of our examples with dartdevc+Chrome.
* Keep an eye out for dartdevc issues.
* Once we're sure everything is good:
  * [x] Update Stagehand templates to use dartdevc+Chrome.
  * [x] Update webdev examples to use dartdevc+Chrome  - #1267.
  * [x] Search for Dartium, update to Chrome (except in pages that are really Dartium-specific).

/cc @filiph, @kevmoo, @jakemac53, @chalin

**Comment by chalin** [comment]
@kwalrath - we can't really update Stagehand templates unless we create a 2-dev branch. Do you want me to do that?

**Comment by chalin** [comment]
We're done with this issue, right?

**Comment by kwalrath** [comment]
Yep, all done.
