### ISSUE TITLE
curate codelabs, their repos and where live examples are run from

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#680]
@kwalrath @kevmoo @filiph: we are gradually accumulating various codelabs for AngularDart and ACX. Some seem to be falling into disfavor, so we should decide which ones we really want to keep and retire the others.

We have the following codelabs:

- Those documented via https://webdev.dartlang.org/codelabs, with source under https://github.com/dart-lang/one-hour-codelab/:

  - [**Low-Level HTML Pirate codelab**](https://webdev.dartlang.org/codelabs/darrrt).
     While "low-level", this codelab is _entirely DartPad driven_.
     A live example is also run from webdev (but there is no script in place to update it).

  - AngularDart [**Avast, Ye Pirates** codelab](https://webdev.dartlang.org/codelabs/ng2)
     A live example is also run from webdev (but there is no script in place to update it).

  - ACX [**AngularDart Components lottery codelab**](https://webdev.dartlang.org/codelabs/angular_components).
     A live example is run from https://filiph.github.io/components_codelab/.

- From https://codelabs.developers.google.com/codelabs/, new I/O 2017 codelabs:

  * [Write a Material Design AngularDart Web App](https://codelabs.developers.google.com/codelabs/your-first-angulardart-web-app/); with source under https://github.com/dart-lang/io_2017_components_codelab/tree/1_basic.

  * [Build an AngularDart & Firebase Web App](https://codelabs.developers.google.com/codelabs/angulardart-firebase-web-app/); with source under https://github.com/Janamou/firebase-counter-steps

@kwalrath, @Sfshaza are there others?

AngularDart and ACX are evolving rapidly enough and we don't want obsolete / broken code lying around. For those codelabs that we do decide to keep, we should have a (semi-)automated process to update them, and a minimal set of tests.

Thoughts?

**Comment by kwalrath** [comment]
I think you got them all. (All the codelabs I know of are listed on https://webdev.dartlang.org/codelabs.)

My only correction: the source code for the I/O 2017 Material Design codelab is under https://github.com/dart-lang/io_2017_components_codelab, with the final codelab code under the [4_property branch](https://github.com/dart-lang/io_2017_components_codelab/tree/4_property) (not the 1_basic branch). The master branch has some additional improvements not explicitly covered by the codelab. We have an internal doc with all this info (along with links to the internal files used to generate the codelabs), but perhaps I should put this in the wiki and link to that from the internal doc.

Now that we have better codelabs, we could easily drop the AngularDart Avast, Ye Pirates codelab. It's much better explained than our new codelabs (main(), filename conventions, etc.), and we should make sure all that key info is covered somewhere. But it needn't hold up dropping the codelab.

The other codelabs I'm less sure of. It's nice to have an all DartPad codelab to introduce Dart & web concepts. And the lottery simulator is cool and covers more components than the I/O 2017 codelab does. @filiph what do you think?

Looking at analytics, the angular_components and ng2 codelabs are about equal in popularity, despite ng2 not being pointed to by the left nav. We should probably redirect /codelabs/ng2/* to /codelabs, and making /codelabs present a brief, highly visual intro to the codelabs. (See also #663.)

**Comment by chalin** [comment]
I'm ok with keeping all the codelabs, if that is what we prefer (I agree that they all currently have value). I might just suggest a better strategy for keeping them up-to-date, ... and for hosting them all from webdev.

**Comment by kwalrath** [comment]
Definitely I'd like a better strategy for keeping them up-to-date. I don't mind hosting them on webdev, as long as it's easy to see and download the files (both individual files and all the files for each step of an example).

**Comment by filiph** [comment]
I think we could:

* Slash one or two of the codelabs
* Automatically run a batch each week that ensures that [level 1] pub get works, [level 2] pub build works, [level 3] tests work (need to write those tests first), [level 4] have some kind of sanity check integration test. (Levels 1-3 could be part of a travis cron job.)

As for slashing: 

* Jana's codelab is great and I want to keep it updated, but only on best-effort basis. Unless we can get Firebase folks to somehow commit to help us with that.
* Lottery vs Startup namer — I can imagine we only need one of those

I'm obviously biased, so I'd like others to vote on which codelab to potentially get rid of.

**Comment by chalin** [comment]
Just a clarification: by "hosting [app] on webdev" I meant the live examples. The sources can stay in a separate repo.

**Comment by kwalrath** [comment]
I don't see this recorded anywhere, but I believe we've decided to **delete both pirate codelabs** (https://webdev.dartlang.org/codelabs/darrrt, https://webdev.dartlang.org/codelabs/ng2).

They don't get many visitors, comparatively, and it'd be good to have a non-web-specific place to learn Dart coding concepts.

**Comment by chalin** [comment]
> ... delete both pirate codelabs (https://webdev.dartlang.org/codelabs/darrrt, https://webdev.dartlang.org/codelabs/ng2).

Done via #979

**Comment by chalin** [comment]
Done: we've dropped all the "old" codelabs except for the [ACX lottery codelab](https://webdev.dartlang.org/codelabs/angular_components).
