### ISSUE TITLE
[ng] lifecycle-hooks example app: E2E fail under Dart 1.24-dev

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#686]
E2E fail for examples/ng/doc/lifecycle-hooks under Dart 1.24-dev

All e2e tests pass under Dart 1.23. But under 1.24-dev, all e2e tests pass except for one:
```nocode
Suites passed:
  examples/ng/doc/architecture
  examples/ng/doc/attribute-directives
  examples/ng/doc/component-styles
  examples/ng/doc/dependency-injection
  examples/ng/doc/displaying-data
  examples/ng/doc/forms
  examples/ng/doc/hierarchical-dependency-injection
  examples/ng/doc/pipes
  examples/ng/doc/quickstart
  examples/ng/doc/router
  examples/ng/doc/security
  examples/ng/doc/server-communication
  examples/ng/doc/structural-directives
  examples/ng/doc/template-syntax
  examples/ng/doc/toh-1
  examples/ng/doc/toh-2
  examples/ng/doc/toh-3
  examples/ng/doc/toh-4
  examples/ng/doc/toh-5
  examples/ng/doc/toh-6
  examples/ng/doc/user-input
Suites failed:
  examples/ng/doc/lifecycle-hooks
```
The lifecycle-hooks failure:
```nocode
Suite: Lifecycle hooks
  passed - should open correctly
  passed - should support peek-a-boo
  passed - should support OnChanges hook
  passed - should support DoCheck hook
  failed - should support AfterView hooks
  Expected 11 to equal 10, '7 additional log messages should have been added'.
  passed - should support AfterContent hooks
  passed - should support spy's OnInit & OnDestroy hooks
  passed - should support "spy counter"
Suite failed: Lifecycle hooks
```

Specifically, I've been using
> Dart VM version: 1.24.0-dev.6.6 (Fri Jun  2 01:54:31 2017) on "macos_x64"

I'll share more details after I've investigated further.

cc @kwalrath @matanlurey

**Comment by chalin** [comment]
For comparison see the TS version of the app: https://aio-staging.firebaseapp.com/generated/live-examples/lifecycle-hooks/eplnkr.html
- Then click on the "AfterViewInit & AfterViewChecked" link
- Click the AfterView "Reset" button.
- Notice that three log messages result:
  ```
  AfterView constructor: no child view
  AfterViewInit: Magneta child view
  AfterViewChecked: Magneta child view
  ```

The AngularDart version is https://webdev.dartlang.org/examples/ng/doc/lifecycle-hooks/#after-view. Perform the same actions and the log will **only show**:
```
AfterView constructor: no child view
```
If I print log messages to the console as they are logged, I can see all three messages being logged, but the log display isn't being refreshed.

Relevant info:
 - [AngularDart docs on AfterView](https://webdev.dartlang.org/angular/guide/lifecycle-hooks#afterview)
 - [Lifecycle hooks example sources](https://github.com/angular-examples/lifecycle-hooks)

**Comment by kwalrath** [comment]
I'm seeing the same behavior for 1.24.0-dev.6.8 and when I switch back to 1.23.0.

**Comment by chalin** [comment]
Btw, the last log entry I have with the tests passing used AngularDart **3.0.0-alpha+1** (back on March 17). Note that I don't consistently log my local test runs so I might have run them more recently, but I don't have a log to prove it.

**Comment by chalin** [comment]
I'm still seeing this issue under 1.24.0.

**Comment by chalin** [comment]
Interestingly enough, now that the [Travis Ubuntu images have been updated](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch), the lifecycle-hooks test is failing on Travis too. For an example, see [this log](https://travis-ci.org/dart-lang/site-webdev/jobs/245512765). Here is an excerpt:
```nocode
[[90m20:00:01[39m] AppDir: examples/ng/doc/lifecycle-hooks
[[90m20:00:02[39m]   Suite: Lifecycle hooks
[[90m20:00:02[39m]     passed - should open correctly
[[90m20:00:03[39m]     passed - should support peek-a-boo
[[90m20:00:03[39m]     passed - should support OnChanges hook
[[90m20:00:04[39m]     passed - should support DoCheck hook
[[90m20:00:04[39m]     failed - should support AfterView hooks
[[90m20:00:04[39m]     Expected 11 to equal 10, '7 additional log messages should have been added'.
[[90m20:00:05[39m]     passed - should support AfterContent hooks
[[90m20:00:05[39m]     passed - should support spy's OnInit & OnDestroy hooks
[[90m20:00:05[39m]     passed - should support "spy counter"
[[90m20:00:05[39m]   Suite failed: Lifecycle hooks
[[90m20:00:05[39m] [20:00:05] I/launcher - 0 instance(s) of WebDriver still running
[[90m20:00:05[39m] [20:00:05] I/launcher - chrome #01 failed 1 test(s)
[[90m20:00:05[39m] [20:00:05] I/launcher - overall: 1 failed spec(s)
[[90m20:00:05[39m] [20:00:05] E/launcher - Process exited with error code 1
```
