### ISSUE TITLE
Fix structural-directives example

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#693]
When you click the links near the top of https://webdev.dartlang.org/angular/guide/structural-directives, it's apparent that something's wrong with the example:

* The hosted app hangs.
* The source code hasn't been updated since May 20, 2016.

@chalin thinks it's missing the dds sync config file.

**Comment by chalin** [comment]
#708 added the necessary config file. Ran DDS which updated the repo.
The [app runs fine now](https://webdev.dartlang.org/examples/ng/doc/structural-directives).
