### ISSUE TITLE
Update the webdev FAQ and link to it more prominently

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#694]
https://webdev.dartlang.org/faq hasn't been updated since January, and probably hasn't been reviewed since it was created in July 2016.

We should:
- [x] give it a once-over,
- [x] fixing #683,
- [x] adding dartdevc, and making sure it's up to date.
- [x] Q. Isn’t Dart a lot like JavaScript? (see `update-for-dart-2` marker)

/cc @filiph @kevmoo

**Comment by kwalrath** [comment]
Also, we should link to it more prominently.

**Comment by chalin** [comment]
I've updated the opening comment, creating a todo list. I've addressed all but one `update-for-dart-2` marker. @kwalrath, might you be willing to handle the last one?

**Comment by kwalrath** [comment]
Looks like #1787 addressed this.
