### ISSUE TITLE
Consider adding edit/issue links to each page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#696]
See https://github.com/flutter/flutter/issues/10416 & https://github.com/flutter/website/pull/592.

**Comment by chalin** [comment]
From @kevmoo - https://github.com/dart-lang/site-webdev/issues/845#issue-244167434: 
> We could auto-populate the page URL
> 
> If we're smart, we could populate the deployment date
> 
> See https://kevmoo.github.io/better_issue/
