### ISSUE TITLE
Travis: switch to using firebase/superstatic

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#698]
Contributes to #697.

A recent update to firebase-tools introduced the need for authentication even to locally serve files (https://github.com/firebase/firebase-tools/issues/302). We updated our build scripts to accommodate this (#654), but the approach has drawbacks like:
- We can't use firebase to serve on PR builds because [tokens aren't available for PR builds](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions).
- This, in particular, will mean that community contributions builds won't have link-checking run.

https://github.com/firebase/firebase-tools/issues/302 suggests the use of https://github.com/firebase/superstatic as an alternative.

**Comment by sethladd** [comment]
I'm not sure what superstatic does (their homepage 404's for me).

@FaisalAbid had an idea for how to do auto-staging for PRs that come from outside our project. If you want to prototype that design, I'm sure Faisal will give you a braindump. If it works for you, Flutter could implement it :)

**Comment by chalin** [comment]
My understanding is that, superstatic is to firebase what chromium is to chrome.

Thanks for the offer, but at this point, we're not looking into auto-staging PRs, but rather just run a local link checker over the site build.
