### ISSUE TITLE
API docs: live examples should point to webdev now

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#774]
Some API pages, like
- http://localhost:4001/angular/api/angular2.core/OnInit-class

still link to http://angular-examples.github.io; e.g.,
- http://angular-examples.github.io/lifecycle-hooks#spy.

Live examples are now hosted via webdev, e.g.:
- https://webdev.dartlang.org/examples/ng/doc/lifecycle-hooks#spy

---

**Edit**: live examples are hosted on webdev, but no longer have `ng/doc` path segments. E.g., 
- https://webdev.dartlang.org/examples/lifecycle-hooks#spy

**Comment by kwalrath** [comment]
@chalin, those webdev URLs (e.g. https://webdev.dartlang.org/examples/ng/doc/lifecycle-hooks#spy) don't work, causing 404s due to people clicking links on http://angular-examples.github.io/.

What happened?

**Comment by chalin** [comment]
@kwalrath https://github.com/angular-examples/angular-examples.github.io/pull/3 fixes the invalid links in http://angular-examples.github.io/.

> What happened?

When I updated the dart-doc-syncer to support the ACX tutorial, I faced a design trade-off of having the example URLs match the _flat_ project organization of the https://github.com/angular-examples group, or have them match the source path (e.g., `examples/acx` vs `examples/ng/doc`). It was much easier to do the former, (and I saw no gain in writing extra dds code to implement the latter.

**Comment by chalin** [comment]
This issue is still relevant. Here are the API docs that need updating:
```nocode
./angular/lib/src/common/directives/ng_class.dart:48:/// [ex]: http://angular-examples.github.io/template-syntax/#ngClass
./angular/lib/src/common/directives/ng_style.dart:56:/// [ex]: http://angular-examples.github.io/template-syntax/#ngStyle
./angular/lib/src/common/directives/ng_switch.dart:84:/// [ex]: http://angular-examples.github.io/template-syntax/#ngSwitch
./angular/lib/src/core/metadata/lifecycle_hooks.dart:54:/// [ex]: http://angular-examples.github.io/lifecycle-hooks#onchanges
./angular/lib/src/core/metadata/lifecycle_hooks.dart:221:/// [ex]: http://angular-examples.github.io/lifecycle-hooks#docheck
./angular/lib/src/core/metadata/lifecycle_hooks.dart:275:/// [ex]: http://angular-examples.github.io/lifecycle-hooks#after-content
./angular/lib/src/core/metadata/lifecycle_hooks.dart:329:/// [ex]: http://angular-examples.github.io/lifecycle-hooks#after-content
./angular/lib/src/core/metadata/lifecycle_hooks.dart:380:/// [ex]: http://angular-examples.github.io/lifecycle-hooks#after-view
./angular/lib/src/core/metadata/lifecycle_hooks.dart:431:/// [ex]: http://angular-examples.github.io/lifecycle-hooks#after-view
./angular_forms/lib/src/directives/ng_model.dart:58:/// [ex]: http://angular-examples.github.io/template-syntax/#ngModel
```

**Comment by kwalrath** [comment]
I'll fix those links, since API docs are easier for me to edit. But since people won't see the new generated docs for quite a while... How hard would it be to create angular-examples.github.io pages that link to the new locations?

**Comment by kwalrath** [comment]
I've submitted an internal CL (180951638) that fixes the API doc URLs.

**Comment by chalin** [comment]
> ... create angular-examples.github.io pages that link to the new locations?

We've agreed not to do this.

**Comment by kwalrath** [comment]
Closing, since we've done all the work we can reasonably do for this.
