### ISSUE TITLE
samples files not found

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#8]
_From @foundatron on February 7, 2016 18:7_

Sample application fails because the sample file is not found

Example: https://www.dartlang.org/docs/tutorials/fetchdata/#making-a-get-request
File not found: https://www.dartlang.org/samples-files/portmanteaux.json

```
Error: Not Found

The requested URL /samples-files/portmanteaux.json was not found on this server.
```

_Copied from original issue: dart-lang/www.dartlang.org#1549_

**Comment by chalin** [comment]
There are two Gists for Dartpad, one was updated to use the new URL (https://www.dartlang.org/f/portmanteaux.json) but the other (https://gist.github.com/Sfshaza/83f7779d18a8bbe8ccb1) was not. @Sfshaza should be revising the 83f7779d18a8bbe8ccb1 Gist soon. I'll complete the fix to this issue soon after.
