### ISSUE TITLE
angular2 codelab TOC problem -- all entries are just "Use"

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#82]
In the angular2 codelab autogenerated TOC all entries are just “Use” … that is because the `<foo>` element gets embedded as html. See the following image:
![screen shot 2016-11-14 at 1 11 08 pm](https://cloud.githubusercontent.com/assets/4140793/20283254/10298bc2-aa6d-11e6-9b9b-bb4a3518ea4d.png)

**Comment by kwalrath** [comment]
Fixed in https://webdev.dartlang.org/codelabs/angular2_components/2-easystart (and elsewhere) by removing the `<` from the titles.
