### ISSUE TITLE
Remove references to resolved_identifiers with Angular 4

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-webdev#824]
CC @ferhatb 

---
@chalin's edits: update
- [x]  this site's examples #924
- [x] the codelabs published on this site, but whose code is in https://github.com/dart-lang/one-hour-codelab

**Comment by chalin** [comment]
I've added this to our 4.0 to-do list (#670).

Can this be done as of 4.0.0-alpha? If not, for which release?

Do we just drop `resolved_identifiers` w/o a need to do anything else? Otherwise, what needs to be done instead?

**Comment by chalin** [comment]
Angular examples updated by #924.

**Comment by chalin** [comment]
All done!
