### ISSUE TITLE
Ensure that basic project setup and build process is beginner friendly

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#830]
- [x] README install instructions need updating #829
- [x] `scripts/serve_local.sh`: switch to using superstatic so that developers can avoid having to deal with firebase project access permissions (switching to superstatic is what we did for the Travis build process).
- ~Setup for use of [browsersync](https://www.browsersync.io). Also see [this fb post](https://firebase.googleblog.com/2015/12/a-host-of-improvements_61.html).~ --> #902

---
- Also see #833

**Comment by chalin** [comment]
Cf. #833.

**Comment by kwalrath** [comment]
@Sfshaza is there anything else we need to do to make working on webdev at least as friendly as working on www?
