### ISSUE TITLE
[4-dev] Update versions page

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#831]
This is a followup to https://github.com/dart-lang/site-webdev/pull/827#issuecomment-316139954.

We need to decide how to populate the [versions table for the 4-dev](https://webdev-dartlang-org-dev.firebaseapp.com/angular/version) branch. 

On master, the versions table reads:
> ![screen shot 2017-07-18 at 1 47 44 pm](https://user-images.githubusercontent.com/4140793/28331626-caccd812-6bbf-11e7-80c8-0da9a4545c86.png)

We can easily change the site config variables so that 4.0 appears at the top of pages by assigning 4.0 to the "stable version" variable(s), but that will cause the "Stable" row entry of the versions table to contain 4.0.0-alpha (and the "Dev" row to be empty). Is that ok with you, @kwalrath?

**Comment by kwalrath** [comment]
Hmmmm... Would it be possible to have text that only shows up when you aren't on webdev.dartlang.org/master? Then we could put a big warning in this page that it's a pre-release version of the docs, and look at webdev.dartlang.org/angular/version for the latest info about versions.

Heck, I think I want this warning on all the pages, somehow...

**Comment by chalin** [comment]
Something I've been wanting to suggest for a while now, is to include the ng version number in the main nav and the sidenav. We could name the version "4.0 PREVIEW". That would make ensure that the version is visible on all pages. WDYT?

**Comment by kwalrath** [comment]
SGTM!

**Comment by chalin** [comment]
Done via rebase of master (after #835 was merged).
