### ISSUE TITLE
Add this repo to up-for-grabs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#832]
In a very meta moment, this issue (adding us to http://up-for-grabs.net/) is up for grabs. :)

See the instructions at https://github.com/up-for-grabs/up-for-grabs.net. Our entry should be similar to what we have in https://github.com/MunGell/awesome-for-beginners.

**Comment by Kapnobatai3434** [comment]
Hi, I'd like to tackle this.

**Comment by kwalrath** [comment]
http://up-for-grabs.net/#/tags/dart looks great. Thank you so much, @Kapnobatai3434!
