### ISSUE TITLE
File a bug link: populate a template?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-webdev#845]
We could auto-populate the page URL

If we're smart, we could populate the deployment date

See https://kevmoo.github.io/better_issue/

**Comment by chalin** [comment]
Dup/extra requirement for #696?

**Comment by kevmoo** [comment]
pretty much

**Comment by chalin** [comment]
Merged into #696. Closing.

**Comment by kevmoo** [comment]
Duplicate of #696
