### ISSUE TITLE
Fix issues in angular/api homepage

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#852]
I noticed a few issues in https://webdev.dartlang.org/angular/api (in addition to #787):

* [ ] Deprecated APIs aren't crossed out. For example, EventEmitter and View should be crossed out.
* [x] Some rows have nothing in the 1st & 2nd columns (just the 3rd). For example, under angular2.core:
![image](https://user-images.githubusercontent.com/2164483/28437383-41886e04-6d4f-11e7-888b-be9d3acd4a9e.png) Fixed by #853
* [x] Some API items are uncategorized. For example, in the above screenshot, GetterFn & MethodFn have no icon. A more complete list: BaseHRefFromDOMProvider, baseHRefFromDOM, TrackByFn, reflector, SetterFn, MethodFn, GetterFn, ComponentStateCallback, ValidatorFn, TouchFunction, ChangeFunction. Fixed by #853

**Comment by chalin** [comment]
All bugs have been fixed. I've moved the remaining item to #929.
