### ISSUE TITLE
Update codelabs that use angular_components

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#859]
Once angular 4 & the corresponding angular_components release are stable, we need to update our codelabs that use angular_components (only one of which is on webdev):

- [ ] https://codelabs.developers.google.com/codelabs/your-first-angulardart-web-app/
- [ ] https://codelabs.developers.google.com/codelabs/angulardart-firebase-web-app/
- [x] https://webdev.dartlang.org/codelabs/angular_components - #1037

Changes:
- `<glyph>` -> `<material-icon>` (GlyphComponent -> MaterialIconComponent), according to https://github.com/dart-lang/angular_components/pull/129.

I don't know if any other changes affect our code (besides changing the version in the pubspec).

/cc @filiph, @nshahan

**Comment by nshahan** [comment]
One thing you might need to change is that the new compiler does not use the resolved_identifiers listed in the pubspec.yaml. You can remove that section from any examples when you update them to an angular 4.0.0 release.

**Comment by chalin** [comment]
Right. FYI, we're using #824 to track that (Kathy: I just added a note to ensure that we do all the examples, include the codelabs).

**Comment by chalin** [comment]
FYI, I'll be working on https://webdev.dartlang.org/codelabs/angular_components. First, as previously agreed, I'll be moving the source (currently under https://github.com/dart-lang/one-hour-codelab/tree/master/angular_components) to this repo.

**Comment by chalin** [comment]
@kwalrath, @filiph - I'm looking at ways to better support the updating of the prose of codelabs (like `angular_components`) that contain code diffs (especially since `angular_components` actually contains code diffs as _images_).

Beyond that, there are parts of the codelab that are of the form: "Edit xyz.dart ..." followed by a code excerpt that uses manually inserted highlighting to highlight code differences. Here is an example from the [Use acx-scorecard](https://webdev.dartlang.org/codelabs/angular_components/2-easystart#--use-acx-scorecard) example:
> <img width="603" alt="screen shot 2017-08-25 at 13 45 50" src="https://user-images.githubusercontent.com/4140793/29725908-c42b3888-899b-11e7-99e6-d8a2ef4bd6db.png">

Would you be open to having the code excerpt replaced by a(n autogenerated) diff like this (w/ or w/o line numbers, a title, etc):
> <img width="567" alt="screen shot 2017-08-25 at 13 47 01" src="https://user-images.githubusercontent.com/4140793/29726009-1f70d1b2-899c-11e7-9d26-6977c33537b6.png">

**Comment by kwalrath** [comment]
Absolutely, that's a much better solution!

**Comment by chalin** [comment]
The codelab in webdev has been updated. How are the others coming along? If they aren't done, should we close this issue and track the changes for the other codelabs in their via their GitHub projects?

**Comment by kwalrath** [comment]
That makes sense. The other codelabs are on internal infrastructure, so I'll file an internal feature request.

**Comment by kwalrath** [comment]
https://codelabs.developers.google.com/codelabs/your-first-angulardart-web-app/ was updated 2 weeks ago. (The code is in https://github.com/dart-lang/io_2017_components_codelab.)

I'll follow up on https://codelabs.developers.google.com/codelabs/angulardart-firebase-web-app/, which uses code in https://github.com/Janamou/firebase-counter-steps.

**Comment by kwalrath** [comment]
Filed a bug about the Firebase app: Janamou/firebase-counter-steps#6
