### ISSUE TITLE
Rework json-web-service article

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-webdev#864]
[This is a popular article](https://webdev.dartlang.org/articles/get-data/json-web-service) full of useful info. As far as we know, it's not too out of date, though async/await should be added.

There's also this doc: https://github.com/dart-lang/json_serializable

cc: @kwalrath

**Comment by kwalrath** [comment]
We approached Chris about an update but haven't heard from him, so it looks like we'll do the update ourselves. We might rewrite it to fit into real docs, somehow, rather than being an article off to the side.

**Comment by chalin** [comment]
Closing, see https://github.com/dart-lang/site-webdev/issues/1634#issuecomment-398082666 for details.
