### ISSUE TITLE
Site search still generates URLs to angular/api/angular2.common which are 404s

### ISSUE THREAD

**Issue by michschn** [dart-lang/site-webdev#877]
URL: https://webdev.dartlang.org/angular/api/angular2.common/NgClass-class
Expected page: https://webdev.dartlang.org/angular/api/angular2/NgClass-class

The bad URL was generated from the site search

see 1st result:
https://webdev.dartlang.org/search?cx=011220921317074318178%3Ata2gkewbtuu&ie=UTF-8&hl=en&q=ngClass

**Comment by kwalrath** [comment]
Thanks for the report. We didn't do redirects because most of those pages are found via the index or Google search; I'm going to try again to get Google to update its search index.

**Comment by kwalrath** [comment]
7/24 I requested a recrawl of /angular/api and /angular/api/angular2/NgFor-class. I thought that might cover everything, but although search results for NgFor are correct, search results for NgClass still aren't.

I've requested a recrawl of NgClass. I'll go through the analytics to find other pages people visit most often, and recrawl them.

Keeping this bug open until I confirm that NgClass, at least, is indexed correctly.

**Comment by kwalrath** [comment]
Firebase doesn't seem to have very expressive redirect support, but I could do an interim fix by adding something like this to `firebase.json`:

```
     { "source": "/angular/api/angular2.common/**",
       "destination": "/angular/api/angular2/angular2-library",
       "type": 302
     },
```

**Comment by kwalrath** [comment]
I wonder if adding the API pages to https://webdev.dartlang.org/sitemap.xml might help.

**Comment by kwalrath** [comment]
As an experiment, I went to the Search Console > Google Index > Remove URLs and asked to temporarily hide https://webdev.dartlang.org/angular/api/angular2.common. Status is Pending.

**Comment by chalin** [comment]
@kwalrath - let me know how that works out. (If needed, we could just add a redirect rules for each (top-level) entry that used to be under https://webdev.dartlang.org/angular/api/angular2.common; there aren't that many. Of course, we might want to have a better solution when we migrate to 4.x).

**Comment by kwalrath** [comment]
I'm now seeing a mix of angular2.common and angular2 results.

**Comment by kwalrath** [comment]
I just checked the Search Console. The status of https://webdev.dartlang.org/angular/api/angular2.common is "Removed", but that didn't really seem to help search results. I just requested that /angular/api/angular2/angular2-library and its directly linked URLs be re-indexed (I'd wanted to do that last time, but I ran out of requests).

**Comment by kwalrath** [comment]
I'm still seeing **NgClass class - angular2.common library - Dart API** as the top result, but at least it redirects to https://webdev.dartlang.org/angular/api/angular2.common/angular2.common-library, which has a link to the correct page. I'm hoping that now that we have a site index, the next update won't be as hairy. But clearly, we'll have to be prepared to update/add some redirects.
