### ISSUE TITLE
[Angular][example] tutorial/toh-5: 

### ISSUE THREAD

**Issue by phbroc** [dart-lang/site-webdev#879]
Hi,
There is something strange to me with the code, as I'm trying to understand Dart/Angular. For instance, this scenario : 
1) Start at https://webdev.dartlang.org/examples/ng/doc/toh-5/dashboard
2) Click on Narco hero, arrive to the page https://webdev.dartlang.org/examples/ng/doc/toh-5/detail/12
3) Update Narco name by typing its new name = Narcool
4) Click on button Heroes on top of the page, arrive to https://webdev.dartlang.org/examples/ng/doc/toh-5/heroes. OK while Narcool appears with its new name on the page (= Narcool).
5) Hit Enter on the address bar of the page (idest https://webdev.dartlang.org/examples/ng/doc/toh-5/heroes), the page reloads but now Narcool is no more Narcool = he came back to its initial name Narco. :(

I have a similar issue in my work in progress, because my heroService is loading a json file. Every change on a hero name is disappearing quickly by the never ending reloading of getHeroes in Hero_service.

What is the solution for getting the Hero List once, and keeping it in the session, even if someone could press Enter key in the addressbar of the web browser?

Thanks if you can help. It's a big mystery to me.

**Comment by kwalrath** [comment]
Thanks for filing this issue, @phbroc. The good news is that routing is next on our list of docs to work on.

@chalin can you explain what's going on?

**Comment by chalin** [comment]
Hi @phbroc. As you might know already, Angular apps are [Single Page Apps](https://en.wikipedia.org/wiki/Single-page_application), so every time you "hit Enter on the address bar of the page" that causes the app to be reloaded. You can see this by looking at the Network view of the Chrome dev tools after performing step 5 above:

<img width="1094" alt="Network view in Chrome dev tools after reload" src="https://user-images.githubusercontent.com/4140793/28874823-7e850422-7761-11e7-9db2-8a5da8f9f4de.png">

The tutorial app doesn't get hero data from a server; instead, [mock data is just stored in memory](https://webdev.dartlang.org/angular/tutorial/toh-pt4#return-mocked-hero-data). Any changes you make are kept in memory. So when a new instance of the app is loaded, a fresh version of the mock data is created, which causes changes to be lost. 

> What is the solution for getting the Hero List once, and keeping it in the session, even if someone could press Enter key in the addressbar of the web browser?

You'll need to store data separately from the app to avoid the behavior you are seeing.

I hope that this helps clarify the app behavior. I'll close this for now. You are welcome to post more questions here, or you can try [Stackoverflow](http://stackoverflow.com/questions/tagged/dart) where the community is quick at responding.

**Comment by phbroc** [comment]
Hi @chalin 
It's kind to you for this answer. I have a better understanding of this example. 
Thank you for your help.
