### ISSUE TITLE
Clarify search engine tabs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#883]
When you do a site search on webdev (e.g., [search for NgClass](https://webdev.dartlang.org/search?cx=011220921317074318178%3Ata2gkewbtuu&ie=UTF-8&hl=en&q=NgClass)), you see 5 tabs. If you click the "API docs" tab, you're likely to get nothing because it refers to api.dartlang.org, not the API docs on webdev. That seems confusing.

![image](https://user-images.githubusercontent.com/2164483/28797451-351673e6-75f6-11e7-9968-439b4cecf887.png)

**Comment by chalin** [comment]
Is this something I can address?

**Comment by kwalrath** [comment]
IIRC, search engine permissions are strange. I might need to do it, unless we create a new search engine.

**Comment by kwalrath** [comment]
I've removed the API docs tab, since I think the *.dartlang.org tab is good enough.
