### ISSUE TITLE
TOH-6 Right side Navigation is missing links

### ISSUE THREAD

**Issue by Stargator** [dart-lang/site-webdev#908]
[Tour of Heroes Par 6](https://webdev.dartlang.org/angular/tutorial/toh-pt6) has a navigation list on the right side. It currently only shows "Where you left off". Instead of showing all the major sections of the page like the previous parts.

**Comment by chalin** [comment]
Yes, thanks for the issue. I'll look into this shortly.

**Comment by kwalrath** [comment]
It looks like there's an h1 in the page that's blocking TOC generation. I'll take this one.
