### ISSUE TITLE
[ng] api reference: styling of filter form group needs to be fixed

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#95]
`api-list` has the following patch to remove the `clearfix` style. The result is
> ![screen shot 2016-11-15 at 2 13 04 pm](https://cloud.githubusercontent.com/assets/4140793/20326438/ab17f418-ab3d-11e6-8b01-852f9564b735.png)

----

With the `clearfix` style in place the API Reference page loads like this
> ![screen shot 2016-11-15 at 1 59 41 pm](https://cloud.githubusercontent.com/assets/4140793/20326421/915980be-ab3d-11e6-9e60-ac14bd68e34f.png)

And after scrolling the page up just a bit it becomes
> ![screen shot 2016-11-15 at 1 59 55 pm](https://cloud.githubusercontent.com/assets/4140793/20326428/98af7030-ab3d-11e6-8288-c2b40ed6f5f7.png)

Find a way to get the proper formatting to work again for the forms group.

cc @ericjim

**Comment by chalin** [comment]
Even with this workaround in place, the API reference page isn't displayed properly when initially loaded and viewed ... until the page is scrolled a bit.

**Comment by chalin** [comment]
Btw, this is related to #50.

**Comment by Sfshaza** [comment]
Also, set "toc: false" in the front matter for that page to prevent the empty "On this page" column.

**Comment by chalin** [comment]
@Sfshaza - good idea, thanks. I was hoping to get the toc to display the h2 representing each of the libraries, but that will require closer integration between the jquery and ng directives. I'll do what you suggest in the meantime.

**Comment by chalin** [comment]
Fixed by #111
