### ISSUE TITLE
Improve API reference navigation

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#959]
There's no easy way to get from the new API docs to the API homepage (or anywhere else on webdev.dartlang.org).

We could work around this using text in the package READMEs and library doc comments, but it'd be better to have this automated, somehow.

**Comment by chalin** [comment]
I propose a home icon link this that links to "/api":
> <img width="843" alt="screen shot 2017-08-25 at 17 04 21" src="https://user-images.githubusercontent.com/4140793/29733751-c41ba08c-89bc-11e7-8308-0309d9ab19a8.png">

> <img width="403" alt="screen shot 2017-08-25 at 17 04 45" src="https://user-images.githubusercontent.com/4140793/29733765-cb590dee-89bc-11e7-9ae2-72430af27c39.png">

WDYT?
