### ISSUE TITLE
Add angular_test to api/?

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#960]

**Comment by chalin** [comment]
@matanlurey WDYT?

**Comment by matanlurey** [comment]
You mean `angular_test`? Sure!

**Comment by chalin** [comment]
> You mean angular_test? Sure!

Done.

@matanlurey: should `angular_test.compatibility` be included too?

**Comment by matanlurey** [comment]
No. Not a real public API

**Comment by chalin** [comment]
Done in 4-dev branch: https://webdev-dartlang-org-dev.firebaseapp.com/api#!?package=angular_test
