### ISSUE TITLE
Typo ("Classess") and nits for Angular docs

### ISSUE THREAD

**Issue by ninachen** [dart-lang/site-webdev#974]
Apologies if I shouldn't be mixing multiple things into one bug, but they are fairly minor.

1. Here: https://webdev.dartlang.org/angular/tutorial/toh-pt1#!#libapp_componentdart-appcomponent-class
one String variable is type annotated `String` and the other one `var`.
Ideally, they'd both be `String` or both be `var`; the delta threw me off slightly.
1. There is a typo here: https://webdev.dartlang.org/angular/guide/template-syntax#!#ngClass
where it says `setCurrentClassess()`.
1. Here: https://webdev.dartlang.org/angular/tutorial/toh-pt3#!#libapp_componentdart-template
It says "Click a heroe." instead of "Click a hero."
1. https://webdev.dartlang.org/angular/tutorial/toh-pt4#!#use-asyncawait
Extra second comma: "Thankfully, Dart’s async/await language feature, lets you..." should be "Thankfully, Dart’s async/await language feature lets you..."

**Comment by kwalrath** [comment]
One bug is fine. Thanks, @ninachen!

**Comment by chalin** [comment]
Hi @ninachen. Thank you for reporting these; they have all been fixed except for (1), and here is why ...

> 1. ... one String variable is type annotated String and the other one var.

Use of `var` is a common Dart programmer's idiom when incrementally developing software. We use `var` in situations where, for example: at a given stage of development, we don't know / don't care about the type of a variable, or we haven't yet defined the type that we'd like to use. Dart doesn't force us to put an arbitrary static type annotation. Later, as we've done a few paragraphs down in the tutorial (i.e., after we've defined the `Hero` type) we replace the `var hero` with `Hero hero`. I hope that this helps clarify the use of `var`.

**Comment by ninachen** [comment]
Sure, I understand the use cases for `var`; it was more that the delta seemed a bit odd.

For context, I filed the issues as I was making my way through the tutorial, so I didn't yet know that `hero` was going to change from a `String` to a `Hero`. I see two Strings, but only one is explicitly type-annotated...was this an accident?
And then if `var hero` get changed to get an explicit type annotation anyway, I don't see how changing from `var` to `Hero` is much different than from `String` to `Hero`. :)

Anyway, it's your call. Thanks for making the changes!

**Comment by chalin** [comment]
> Anyway, it's your call. Thanks for making the changes!

Thanks for your feedback!

> 1. ... Ideally, they'd both be `String` or both be `var`; the delta threw me off slightly.

FYI, I've revised the code, dropping the `String` type annotation:
```dart
class AppComponent {
  final title = 'Tour of Heroes';
  var hero = 'Windstorm';
}
```
See https://github.com/dart-lang/site-webdev/pull/1016/files#diff-ccc52c204f8768290dbf31d830727f82
