### ISSUE TITLE
Add another sidenav section

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#975]
The RESOURCES part of our current sidenav (pictured below) has a couple of problems:

* It contains 2 angular-specific resources. The other resources are more general web development resources. The angular-specific resources:
  * [API Reference](https://webdev.dartlang.org/api): has an angular icon although it's top-level; contains only angular* classes
  * [Changelog](https://webdev.dartlang.org/angular/changelog): has an angular icon, is under the /angular path; it theoretically could contain non-angular changes... perhaps we should move it.
* It's too long to be easily scanned.

Current sidenav: 

![image](https://user-images.githubusercontent.com/2164483/29734955-2a650e9a-89aa-11e7-8dd7-3243a540eb2b.png)

Possible new sidenav (removes links to Articles, Glossary, & one Codelab):

ANGULAR DART
About
Guide >
Tutorial > 
Advanced >

ANGULAR DART
COMPONENTS
About
Example

ANGULAR DART
REFERENCE
API Documentation
Changelog
Cheat Sheet

RESOURCES
Codelabs
Community and Support
Libraries
Tools
Tutorials

**Comment by chalin** [comment]
Good suggestion. Here is a variant staged at https://angulardart-org-dev.firebaseapp.com as it would look like on a phone:
> <img width="414" alt="screen shot 2017-08-26 at 09 15 37" src="https://user-images.githubusercontent.com/4140793/29741646-29ef08e0-8a3f-11e7-81cd-005e18c03925.png">

I think that it is important to keep a direct link to the Glossary.

We can further reclaim vertical real estate by:
- Dropping the "About" entries and making the headers link. (Yes, we've discussed this before :)
- By adopting the previous suggestion, we could then make "Get Started" a linked top-level entry (as opposed to an overly padded button :)

**Comment by kwalrath** [comment]
I like your ideas for reclaiming vertical real estate, and with those changes I'm fine with keeping Glossary in the sidenav. (I just looked at the analytics, and it's the 61st most visited page on webdev, behind 13 of 17 always-visible sidenav pages; changelog, articles, & community have fewer views. I suspect the glossary wouldn't get nearly as many visits if it weren't in the sidenav.)

Do you have any objection to shortening and alphabetizing the RESOURCES links, as in my original suggestion above?
 
Finally, we should probably change site-www to reflect whatever we do here.

**Comment by chalin** [comment]
> I like your ideas for reclaiming vertical real estate

Ok, I'll work on those.  (Surprising that the glossary isn't used more. Maybe we need to link to it more from individual pages.)

> Do you have any objection to shortening and alphabetizing the RESOURCES links, as in my original suggestion above?

Not at all. Done.

**Comment by chalin** [comment]
All updates done to #977 except converting the "Get Started" button (which seems to be working better now. 

Staged at https://angulardart-org-dev.firebaseapp.com

The sidenav now fits completely on an iPhone 5 screen; e.g.:

> <img width="506" alt="screen shot 2017-08-29 at 14 04 30" src="https://user-images.githubusercontent.com/4140793/29836471-5ab3e208-8cc3-11e7-853b-24802ba24a6d.png">

**Comment by chalin** [comment]
Fixed by #977
